devtron-labs/dashboard

src/components/app/details/cicdHistory/TriggerDetails.tsx
src/components/app/service.ts

feat: force abort build ci

---

package.json
src/components/app/details/triggerView/workflow.service.ts
src/components/common/edge/rectangularEdge.tsx
src/components/workflowEditor/Workflow.tsx
src/css/base.scss

Adding support for tooltip in addCDButtons for workflow

feat: add support for tooltip in addCDButtons

---

src/components/app/details/appDetails/AppDetails.tsx
src/components/app/details/appDetails/DeploymentStatusCard.tsx
src/components/app/details/appDetails/DeploymentStatusDetailModal.tsx
src/components/app/details/appDetails/DeploymentStatusDetailRow.tsx
src/components/app/details/appDetails/appDetails.type.ts
src/components/v2/appDetails/AppDetails.component.tsx

Fixed the following issues
- The timeline data disappears from the timeline modal after sometime due to incorrect API call
- On refreshing, the timeline modal closes despite being controlled via search param
- When opening the modal for the first time, stale data is displayed due to lack of initial loading state

fix: data refresh issue on deployment timeline on app detail page

---

src/components/app/details/appDetails/utils.tsx

- Fix the issue with timed out wfr status on app detail showing as In Progress

fix: the issue with timed out wfr status

---

src/components/app/ResourceTreeNodes.tsx
src/components/app/details/appDetails/appDetails.scss

fix for fe issue when no pods exist
Fixes #4419

fix: css nopod

---

package.json
src/components/gitOps/GitOpsConfiguration.tsx

feat: Generalized custom input
Fixes https://github.com/devtron-labs/devtron/issues/4437

feat: Updated version for Custom Input

---

src/components/ciPipeline/Webhook/WebhookDetailsModal.tsx
src/components/cluster/ClusterForm.tsx
src/components/material/MaterialView.tsx
src/components/notifications/SESConfigModal.tsx

Labels missing in Git Provider
Fixes https://github.com/devtron-labs/devtron/issues/4445

fix: missing labels due to missing callback

---

src/components/ciPipeline/Webhook/WebhookDetailsModal.tsx
src/components/deploymentGroups/BulkActionEdit.tsx
src/components/material/MaterialView.tsx
src/css/base.scss

Fixes https://github.com/devtron-labs/devtron/issues/4445
1. Label for webhook token.
2. Deployment group UIi broken

fix: Label for webhook token

---

config.md

docs: added new variable for manual trigger of ci-pipeline

---

src/components/CIPipelineN/Build.tsx
src/components/CIPipelineN/CIPipeline.tsx
src/components/ciPipeline/SourceMaterials.tsx
src/components/ciPipeline/types.ts

Migrating all the existing async requests in CIPipeline to async-await instead and having a loader for all calls in initial mount

fix: CIPipeline loading

---

src/components/CIPipelineN/AdvancedConfigOptions.tsx
src/components/CIPipelineN/CIPipeline.tsx
src/components/CIPipelineN/DockerArgs.tsx
src/components/CIPipelineN/types.ts
src/components/ciConfig/CIConfig.tsx
src/components/ciConfig/CIConfigForm.tsx

Extracting out Docker args component and creating a specific handler to update setFormData for it.

fix: docker args component

---

src/components/CIPipelineN/AdvancedConfigOptions.tsx
src/components/CIPipelineN/Build.tsx
src/components/CIPipelineN/CIPipeline.tsx
src/components/ciConfig/CIConfig.tsx
src/components/ciConfig/CIConfigForm.tsx
src/components/ciPipeline/SourceMaterials.tsx
src/components/ciPipeline/types.ts

fix: read-only view for delete override

---

src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateEditorView.tsx

fix for wrong link of schema.json 
ref: https://cdn.discordapp.com/attachments/819922034363727932/1189798772818055178/Screenshot_2023-12-28_at_10.45.18_AM.png?ex=659f7974&is=658d0474&hm=7bb15a5034a2bd3c48e99bdea89727ac9fb2de557daced978bc9f24a329c81b3&
Fixes #3535

fix: wrong chart name

---

src/components/ciConfig/BuildContext.tsx
src/components/ciConfig/CIConfig.utils.ts
src/components/ciConfig/CICreateDockerfileOption.tsx
src/components/ciConfig/CIDockerFileConfig.tsx
src/components/ciConfig/types.tsx

Creating a separate component for Build Context and removing its duplicate instances, have also shifted the corresponding states and useEffects into that component only and since its flag based so would also be performance optimisation.

fix: ci pipeline build context

---

src/components/ciConfig/BuildContext.tsx
src/components/ciConfig/CICreateDockerfileOption.tsx
src/components/ciConfig/CIDockerFileConfig.tsx
src/components/ciConfig/CISelfDockerBuildOption.tsx
src/components/ciConfig/types.tsx

Migrating Self Docker build from render method to separate component

fix: migrate self docker build to a separate component

---

src/components/ciConfig/CIAdvancedConfig.tsx
src/components/ciConfig/CIBuildpackBuildOptions.tsx
src/components/ciConfig/CIDockerFileConfig.tsx
src/components/ciConfig/types.tsx

Simplifying conditions and removing unreachable statements from buildpackOptions

fix: build pack options component conditions

---

src/components/CIPipelineN/AdvancedConfigOptions.tsx
src/components/ciConfig/CIBuildpackBuildOptions.tsx
src/components/ciConfig/CIDockerFileConfig.tsx

Would be fixing the following prod issues in CIPipeline and Build Configuration:
- BuildContext isDefault condition
- Custom tag, docker args hidden after going to build pack and deleting override and if its not build buildpack in global.
- Buildpack stuck in loading in moving to and froth between build options

Fix(ci pipeline)/prod issues

---

src/components/app/details/appConfig/AppComposeRouter.tsx

Unable to Access Secret Named "secrets" in Application > App Configuration > Env Override
Fixes https://github.com/devtron-labs/devtron/issues/4487

fix: Unable to Access Secret Named "secrets" in Env ovr Application

---

src/components/CIPipelineN/DockerArgs.tsx
src/components/CIPipelineN/types.ts
src/components/ciConfig/CIAdvancedConfig.tsx
src/components/ciConfig/CIConfig.tsx

Removing the duplication of docker build args in case of build pack.

fix: duplicate build args

---

src/components/ciConfig/CIConfigDiffView.tsx
src/components/ciConfig/CIDockerFileConfig.tsx
src/components/ciConfig/types.tsx

Will be now redirecting to linked ci modal instead of ci pipeline modal from ci config on click of linked ci node.

fix: config diff linked redirection

---

src/components/CIPipelineN/AdvancedConfigOptions.tsx

Showing custom image tag in case we have buildpack option enabled in ci pipeline modal

fix: custom tag build pack

---

package.json
src/components/common/helpers/Helpers.tsx

Adding check for empty string and string in TRIGGER_API_TIMEOUT
Fixes https://github.com/devtron-labs/devtron/issues/4504

fix: add check for string type in TRIGGER_API_TIMEOUT

---

src/components/app/create/CreateApp.tsx
src/components/deploymentConfig/DeploymentTemplateView/DeploymentConfigFormCTA.tsx

- Fix the loading issues in create app and build configuration
Fixes https://github.com/devtron-labs/devtron/issues/4508

fix: loading issue in create app and build configuration

---

src/components/ciPipeline/ciPipeline.service.ts

Deriving CI Trigger from DEFAULT_CI_TRIGGER_TYPE_MANUAL
Fixes https://github.com/devtron-labs/devtron/issues/4516

fix: update check for default  manual trigger

---

src/components/CIPipelineN/DockerArgs.tsx
src/components/CIPipelineN/types.ts
src/components/ciConfig/BuildContext.tsx
src/components/ciConfig/CISelfDockerBuildOption.tsx
src/components/ciConfig/CreateDockerFileLanguageOptions.tsx

Fixing ESLint issues in ci-pipeline modal

chore: ci-pipeline linting

---

src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx

Uanble to render data  for the list  of approvals via getConfig api.
Fixes

fix: Prod bug for config api rendering

---

src/components/userGroups/AppPermissions.tsx

This PR include the fix for Unassigned app all app list selection  and added the check of EA mode in JOB RBAC
Fixes https://github.com/devtron-labs/devtron/issues/4606
Manually verified all the scenario by providing diff permission

fix: Helm app unassigned project all app selection fix

---

package.json
src/components/common/helpers/Helpers.tsx
src/css/base.scss

Move highlight text to common and add base classes

chore: move highlight text to common and add base classes

---

src/Pages/GlobalConfigurations/BuildInfra/ProfileForm.tsx

Removing hideCancel prop and adding preventDefault in infra form

fix: infra handle cancel

---

package.json
src/components/cdPipeline/PullImageDigestToggle.tsx
src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateGUIView.tsx
src/config/constants.ts
src/css/base.scss

fix: content added for global only & pipeline

---

src/components/ciPipeline/SourceMaterials.tsx
src/components/v2/appDetails/sourceInfo/EnvironmentSelector.component.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.scss

1.  Helm app page gets non-responsive in specific case eg while opening inspect
2. Linked CI Input UI Distoted
3. Scale Workload flickering issue fix
Fixes https://github.com/devtron-labs/devtron/issues/4627

fix: Miscellaneous Bug fixes

---

src/components/common/helpers/Helpers.tsx
src/config/constants.ts

1. Issue in Search of resource browser with escape characters
2. Handling in case of all errors
Fixes https://github.com/devtron-labs/devtron/issues/4642

fix: Issue in Search of resource browser with escape characters

---

index.html
src/App.tsx

- Multiple Style issues in the dashboard
- Service worker handling for without ssl 
Fixes

fix: vite exploration issues

---

README.md
vite.config.ts
yarn.lock

Update Yarn lock for vite config

chore: update yarn.lock

---

src/components/v2/values/chartValuesDiff/ChartValuesView.component.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.type.ts
src/components/v2/values/chartValuesDiff/constant.ts

Refactor for better userflow handling and reduce state

fix: better state handling for helm-apps in user-gitops-repo

---

src/components/CodeEditor/CodeEditor.tsx

this PR consist the fix for Diff view is showing inline when less space available.
Fixes https://github.com/devtron-labs/devtron/issues/4688
Manually tested by running diff scenarios

fix: inline diff issue fix

---

src/components/app/details/appConfig/AppComposeRouter.tsx
src/components/app/details/appConfig/AppConfig.tsx
src/components/ciConfig/CIConfig.tsx
src/components/ciConfig/CIConfigForm.tsx
src/components/ciConfig/types.tsx
src/components/deploymentConfig/DeploymentConfig.tsx
src/components/deploymentConfig/types.tsx

Fix the redirection logic when save and next button is pressed in Git Repository and Build Configuration while creating app

fix: redirection for save and next

---

src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx

fix: return from bulk ci trigger function on validation error

fix: return from bulk ci trigger function on validation error

---

package.json
src/components/ApplicationGroup/AppGroup.types.ts
src/components/ApplicationGroup/Details/TriggerView/BulkCITrigger.tsx
src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/app/details/triggerView/TriggerView.tsx
src/components/app/details/triggerView/TriggerView.utils.ts
src/components/app/details/triggerView/ciMaterial.tsx
src/components/app/details/triggerView/types.ts
src/components/common/GitInfoMaterial.tsx
src/css/base.scss

Giving users to add runtime params to trigger build
Fixes https://github.com/devtron-labs/devtron/issues/4344
QA

feat: runtime params

---

src/components/app/details/triggerView/TriggerView.tsx
src/components/app/details/triggerView/types.ts
src/components/app/details/triggerView/workflow/Workflow.tsx
src/css/icons.scss

feat: Image Promotion

---

src/components/ApplicationGroup/AppGroup.service.ts
src/components/ApplicationGroup/AppGroup.types.ts
src/components/ApplicationGroup/AppGroup.utils.ts
src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/app/details/triggerView/TriggerView.tsx
src/components/app/details/triggerView/types.ts
src/components/app/details/triggerView/workflow.service.ts
src/components/app/details/triggerView/workflow/Workflow.tsx
src/components/ciConfig/CIConfigDiffView.tsx
src/components/ciConfig/types.tsx
src/components/ciPipeline/types.ts
src/components/workflowEditor/Workflow.tsx
src/components/workflowEditor/nodes/CINode.tsx
src/components/workflowEditor/types.ts

Importing WorkflowType, Material from fe-common-lib and making CommonNodeAttr as source of truth instead of NodeAttr

chore: import common types from fe-common-lib

---

src/components/v2/chartDeploymentHistory/ChartDeploymentHistory.component.tsx

Fixes https://github.com/devtron-labs/devtron/issues/4752

fix: bug inside deployment history, docker icon

---

package.json
src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx
src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/app/details/triggerView/cdMaterial.tsx
src/components/app/details/triggerView/types.ts
src/components/app/details/triggerView/workflow.service.ts

Feat: app group bulk trigger

---

src/components/ResourceBrowser/Utils.ts

Add an optional check in resourceBrowser/utils.tsx from the changes in https://github.com/devtron-labs/dashboard/pull/1653
Fixes https://github.com/devtron-labs/devtron/issues/4757

fix: add optional chaining in Utils.tsx

---

package.json
src/App.tsx
src/components/app/details/cdDetails/CDDetails.tsx
src/components/app/details/cicdHistory/Artifacts.tsx
src/components/app/details/cicdHistory/History.components.tsx
src/components/app/details/cicdHistory/types.tsx
src/components/app/details/triggerView/cdMaterial.tsx
src/components/common/helpers/Helpers.tsx

Adding route for promotion notification

feat: notify promotion

---

src/Pages/Shared/LinkedCIDetailsModal/LinkedCIAppList.tsx
src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
src/Pages/Shared/LinkedCIDetailsModal/constants.ts
src/Pages/Shared/LinkedCIDetailsModal/linkedCIAppList.scss
src/Pages/Shared/LinkedCIDetailsModal/service.ts
src/Pages/Shared/LinkedCIDetailsModal/types.ts
src/Pages/Shared/LinkedCIDetailsModal/utils.ts
src/components/app/details/triggerView/workflow/nodes/triggerCINode.tsx
src/components/app/list-new/Constants.ts
src/components/workflowEditor/Workflow.tsx
src/components/workflowEditor/nodes/CINode.tsx

feat: linked ci modal

---

package.json

Fixes https://github.com/devtron-labs/devtron/issues/4812
QA

fix: webhook parent pipeline

---

src/components/v2/appDetails/sourceInfo/rotatePods/RotatePodsModal.component.tsx

Deployment window: fix for rotate pod modal click

Deployment window: fix for rotate pod modal click

---

package.json
src/components/app/details/triggerView/cdMaterial.tsx
src/css/base.scss

fix forms css

---

src/components/ApplicationGroup/Details/EnvironmentOverview/EnvironmentOverview.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateModal.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/UnhibernateModal.tsx
src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx
src/css/base.scss

Bw app group hibernate/Unhibernate loader

App group: Bw app group hibernate/Unhibernate loader

---

package.json
src/components/app/details/cicdHistory/Artifacts.tsx
src/components/app/details/triggerView/cdMaterial.tsx

uat: image promotion

---

src/components/ApplicationGroup/AppGroup.types.ts
src/components/ApplicationGroup/AppGroupDetailsRoute.tsx
src/components/ApplicationGroup/AppGroupRoute.tsx
src/components/ApplicationGroup/Details/EnvCDDetails/EnvCDDetails.tsx
src/components/ApplicationGroup/List/EnvironmentListView.tsx
src/components/app/details/AppHeader.tsx
src/components/app/details/triggerView/cdMaterial.tsx
src/components/app/list-new/AppList.tsx
src/components/app/list/DevtronAppListContainer.tsx
src/components/app/list/types.tsx
src/components/common/Contexts/AppContext.ts
src/components/common/navigation/NavigationRoutes.tsx

add value of env and app in app context

feat: add value of env and app in app context

---

src/components/app/details/appDetails/AppDetails.tsx
src/components/app/details/appDetails/appDetails.type.ts
src/components/v2/appDetails/sourceInfo/rotatePods/RotatePodsModal.component.tsx

Fix: Dw qa fixes

---

src/components/common/security/ScanDetailsModal.tsx
src/components/security/SecurityScansTab.tsx

Security scan modal not opening on tab click

fix: security scan modal not opening on tab click

---

package.json
src/components/common/navigation/NavigationRoutes.tsx
src/css/base.scss

feat: create release and release track modal

---

src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/app/details/triggerView/TriggerView.tsx

fix:- on select material page breaks on error

---

src/components/ApplicationGroup/Details/EnvironmentOverview/EnvironmentOverview.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateStatusRow.tsx

fix: Dw qa files 2

---

src/components/AppSelector/AppSelector.tsx
src/components/AppSelector/AppSelectorUtil.tsx
src/components/ApplicationGroup/AppGroup.service.ts
src/components/ApplicationGroup/AppGroup.utils.ts
src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/ApplicationGroup/EnvSelector.tsx
src/components/app/details/triggerView/TriggerView.tsx
src/components/app/service.ts
src/components/cdPipeline/NewCDPipeline.tsx
src/components/cdPipeline/types.ts
src/components/notifications/AddNotification.tsx
src/components/workflowEditor/Workflow.tsx
src/components/workflowEditor/nodes/CDNode.tsx
src/components/workflowEditor/types.ts
src/components/workflowEditor/workflowEditor.tsx

Cancelling context of previous api calls from:
- CIMaterials (App Group and App view)
- AppHeader
- EnvHeader
- Notification app selector
Fixes https://github.com/devtron-labs/devtron/issues/4880
QA

fix: cancel token

---

src/components/ApplicationGroup/AppGroup.types.ts
src/components/ApplicationGroup/Details/EnvironmentOverview/EnvironmentOverview.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateStatusListDrawer.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateStatusRow.tsx

wrong message is showing in case of bulk hibernate of an app

fix: Appgroup hibernate message

---

src/components/app/details/triggerView/cdMaterial.tsx
src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx

This PR contains fix for below issues caught in packet testing.
1) Deploy button not working
2) Copy on resource tree not working correctly

fix: Packet testing issues

---

src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.api.ts
src/components/v2/appDetails/k8Resource/nodeType/NodeDelete.component.tsx

Enable resource scan for child nodes in app details

fix: child node scan

---

src/components/ClusterNodes/ClusterTerminal.tsx
src/components/common/ClusterMetaDataBar/ClusterMetaData.scss
src/components/common/ClusterMetaDataBar/ClusterMetaDataBar.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/Terminal.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/TerminalWrapper.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/terminal.type.ts
src/css/base.scss

fixes: Css fixes for link app

---

src/css/base.scss

Add dashed border right base class

chore: add dashed border right base class

---

src/components/common/navigation/NavigationRoutes.tsx
src/config/constants.ts
src/css/base.scss

feat: add image selection utility provider

feat: add image selection utility provider

---

package.json
src/components/ciPipeline/CiPipelineSourceConfig.tsx
src/css/base.scss
src/services/service.ts

chore: replace getWebhookEventsForEventId from common

chore: replace getWebhookEventsForEventId from common

---

src/components/app/details/cdDetails/CDDetails.tsx
src/components/app/details/cicdHistory/types.tsx
src/components/app/details/triggerView/TriggerView.utils.ts
src/components/app/details/triggerView/cdMaterial.tsx
src/components/app/details/triggerView/types.ts
src/components/app/service.ts
src/css/base.scss

feat: migrate deployment stage type to common, add box-shadow classes

---

src/components/ApplicationGroup/Details/EnvironmentOverview/RestartStatusListDrawer.tsx

message of blocked deployment  user

---

src/components/app/details/appDetails/SecurityVulnerabilityCard.tsx
src/components/app/details/appDetails/SourceInfo.tsx
src/components/common/helpers/Helpers.tsx
src/components/v2/appDetails/sourceInfo/environmentStatus/EnvironmentStatus.component.tsx

chore: removed resource scan new Feat

---

src/components/app/details/appDetails/SecurityVulnerabilityCard.tsx

chore: Added hack to prevent clicked outside

---

src/components/app/details/appDetails/SecurityVulnerabilityCard.tsx
src/components/gitOps/GitOpsConfiguration.tsx

fix: fixed bitbucket issue

---

src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/app/details/appDetails/AppDetailsCDButton.tsx
src/components/app/details/appDetails/SourceInfo.tsx
src/components/app/details/triggerView/TriggerView.tsx
src/components/app/details/triggerView/cdMaterial.tsx
src/components/app/types.ts
src/components/common/helpers/Helpers.tsx

Integration of Approval modal integration in AppDetails CDModal

feat: approval modal integration

---

src/components/dockerRegistry/Docker.tsx

fixed if condition
Fixes #5107

fix: condition fix in container registry (global config)

---

.eslintignore
src/components/ApplicationGroup/AppGroup.types.ts
src/components/ApplicationGroup/Details/EnvironmentOverview/EnvironmentOverview.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateModal.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateStatusListDrawer.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/UnhibernateModal.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/service.ts
src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/app/service.ts
src/components/cdPipeline/NewCDPipeline.tsx
src/css/icons.scss
yarn.lock

feat: use ApiQueuingWithBatch for bulk operations in App Group (hibernation/un-hibernate & branch-change)

---

.eslintignore
src/components/ApplicationGroup/AppGroup.types.ts
src/components/ApplicationGroup/Details/EnvironmentOverview/EnvironmentOverview.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateModal.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateStatusListDrawer.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/RestartWorkloadModal.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/UnhibernateModal.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/service.ts
src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/app/service.ts
src/components/cdPipeline/NewCDPipeline.tsx
src/css/icons.scss
vite.config.ts
yarn.lock

Fixes https://github.com/devtron-labs/devtron/issues/5121

feat: use ApiQueuingWithBatch in bulk operations of App Group (bulk  hibernate/un-hibernate & change branch)

---

src/components/cluster/ClusterForm.tsx
src/components/cluster/cluster.type.ts
src/components/dockerRegistry/Docker.tsx
src/components/dockerRegistry/dockerType.tsx

Fixes devtron-labs/devtron#5135,

fix: text fix in case of registry

---

src/components/ApplicationGroup/Constants.ts
src/components/ApplicationGroup/Details/EnvironmentOverview/service.ts
src/components/app/service.ts

Fixes https://github.com/devtron-labs/devtron/issues/5121

fix: error message on bulk hibernate/unhibernate call timeout

---

src/components/CIPipelineN/PreBuild.tsx

fix: pre build modal retains state for select between pre-build & post-build tabs

---

src/components/cluster/Cluster.tsx
src/components/dockerRegistry/Docker.tsx

Fixes devtron-labs/devtron#5151

fix: added optional check on remote connection config

---

src/components/app/details/appDetails/SecurityVulnerabilityCard.tsx

This PR contains the fix for Security modal not opening from app details

chore: Security modal not opening on app details

---

package.json
src/components/common/helpers/Helpers.tsx
src/components/gitOps/GitOpsConfiguration.tsx
src/components/gitOps/UserGitRepo.tsx
src/components/gitProvider/GitProvider.tsx
src/components/material/CreateMaterial.tsx
src/components/material/MaterialView.tsx
src/components/material/UpdateMaterial.tsx
src/components/material/material.types.ts
src/components/scopedVariables/utils.tsx
src/config/constants.ts
src/services/service.ts
yarn.lock

Deprecating DEFAULT_SECRET_PLACEHOLDER, since moved it to common and adding authMode in service of isGitOpsConfigured

fix: aws code commit

---

src/components/ResourceBrowser/Constants.ts
src/components/ResourceBrowser/ResourceList/K8SResourceList.tsx
src/components/ResourceBrowser/ResourceList/ResourceFilterOptions.tsx
src/components/ResourceBrowser/Types.ts
src/components/ResourceBrowser/Utils.tsx

Fix: events sorting and k8s list default page size variable

---

src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/app/details/appDetails/AppDetailsCDButton.tsx
src/components/app/details/triggerView/TriggerView.tsx
src/components/app/details/triggerView/cdMaterial.tsx
src/components/common/navigation/NavigationRoutes.tsx

feat: release history

---

src/components/ApplicationGroup/Details/EnvironmentOverview/UnhibernateModal.tsx

fix: App group Unhibernate message fix

fix: App group Unhibernate message fix

---

src/components/ApplicationGroup/AppGroup.types.ts
src/components/ApplicationGroup/Details/EnvironmentOverview/EnvironmentOverview.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateModal.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/RestartWorkloadModal.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/UnhibernateModal.tsx

Fixes https://github.com/devtron-labs/devtron/issues/5212

fix: App group resistant input in Overview

---

Dockerfile

chore: remove obsolete call from Dockerfile

---

src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateModal.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/UnhibernateModal.tsx

fix for non blocked state
Fixes https://github.com/devtron-labs/devtron/issues/5237

fix: Deployment window fix for hibernate

---

src/components/cdPipeline/NewCDPipeline.tsx
src/components/workflowEditor/nodes/CDNode.tsx

fix: delete modal disappears if CD pipeline delete fails

---

src/components/ResourceBrowser/ResourceList/K8SResourceList.tsx
src/components/ResourceBrowser/ResourceList/ResourceFilterOptions.tsx
src/components/ResourceBrowser/Types.ts
src/config/searchWorker.ts

Revert the change that changed the search behaviour in resource browser.

chore: revert the search behaviour of resource browser search

---

src/components/cdPipeline/NewCDPipeline.tsx
src/components/workflowEditor/nodes/CDNode.tsx

Fixes https://github.com/devtron-labs/devtron/issues/5249

fix: cdPipeline deletion causes error modal to close & doesn't open cluster not reachable modal

---

src/components/ConfigMapSecret/ConfigMapSecret.components.tsx
src/components/EnvironmentOverride/DeploymentTemplateOverrideForm.tsx
src/components/app/EventsLogs.tsx
src/components/app/details/appDetails/appDetails.scss
src/components/deploymentConfig/DeploymentConfig.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/nodeDetailTab.scss
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/TerminalWrapper.component.tsx

Sending appId and envId to ConfigToolbar and DeploymentTemplateLockedDiff to ensure valid RBAC.
Fixes https://github.com/devtron-labs/devtron/issues/5245
https://github.com/devtron-labs/devtron/issues/5262

fix: send appId, envId to ConfigToolbar and DeploymentTemplateLockedDiff

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/TerminalWrapper.component.tsx

fix: page break on render connection strip for terminal

---

src/components/ConfigMapSecret/ConfigMapSecret.components.tsx
src/components/EnvironmentOverride/DeploymentTemplateOverrideForm.tsx
src/components/deploymentConfig/DeploymentConfig.tsx
src/css/base.scss

fix: lock params, image approval message

fix: lock params, image approval message

---

src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/app/details/triggerView/CIMaterialModal.tsx
src/components/app/details/triggerView/TriggerView.tsx
src/components/app/details/triggerView/cdMaterial.tsx
src/components/app/details/triggerView/types.ts
src/components/charts/charts.service.ts
src/components/charts/list/DiscoverCharts.tsx
src/components/charts/modal/ChartGroupBasicDeploy.tsx
src/components/external-apps/ExternalAppService.ts
src/components/v2/values/chartValuesDiff/ChartValuesView.reducer.ts
src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.type.ts
src/components/v2/values/common/chartValues.api.ts

add prompts and abort controller in deploy chart store, update and deploy chart store,  create preset value

feat: add prompts and abort controller in chart store

---

src/components/ApplicationGroup/AppGroup.types.ts
src/components/ApplicationGroup/AppGroupRoute.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/EnvironmentOverview.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateModal.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/RestartWorkloadModal.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/UnhibernateModal.tsx

This PR includes following fixes and optimisations in Environment Overview:
- Key for AppGroupRoute
- Derive appIds in event handlers instead of each re-render

fix: clone env

---

src/components/app/config.tsx
src/components/app/list-new/AppList.tsx
src/components/app/list-new/AppListService.ts
src/components/app/list-new/AppListType.ts
src/components/app/list-new/Constants.ts
src/components/app/list-new/ExternalArgoList.tsx
src/components/app/list-new/ExternalFluxAppDetails.tsx
src/components/app/list-new/ExternalFluxAppDetailsRoute.tsx
src/components/app/list/list.scss
src/components/app/types.ts
src/components/common/navigation/NavigationRoutes.tsx
src/components/external-apps/ExternalApps.tsx
src/components/externalArgoApps/ExternalArgoApp.tsx
src/components/globalConfigurations/GlobalConfiguration.tsx
src/components/v2/appDetails/AppDetails.component.tsx
src/components/v2/appDetails/appDetails.type.ts
src/components/v2/headers/EAHeader.component.tsx
src/components/v2/headers/appHeader.type.ts
src/config/routes.ts

feat: fluxcd app details

---

src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx
src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateGUIView.tsx
src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateReadOnlyEditorView.tsx

fix: stuck editor type toggle in case of published view of statefulset & rollout charts

---

src/components/EnvironmentOverride/DeploymentTemplateOverride.tsx
src/components/EnvironmentOverride/DeploymentTemplateOverrideForm.tsx
src/components/EnvironmentOverride/service.ts
src/components/deploymentConfig/DeploymentConfig.tsx
src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateGUIView.tsx
src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateOptionsTab.tsx
src/components/deploymentConfig/constants.tsx
src/components/deploymentConfig/fallbackJobsNCronJobGuiSchema.json
src/components/deploymentConfig/service.tsx
src/components/deploymentConfig/utils.tsx

fix: lock gui when hide locked keys & new schema for jobs

---

src/components/chartRepo/ChartRepo.tsx

feat: chart repo v10

---

src/components/app/list/list.scss
src/components/chartRepo/ChartRepo.tsx

feat: chart repo

---

src/components/chartRepo/ChartRepo.tsx

feat: handle collapse

---

src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/app/details/triggerView/TriggerView.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
src/config/constants.ts

retain ci modal on refresh, update prompt message in dirty state

fix: retain ci modal on refresh

---

.eslintignore
src/components/ResourceBrowser/ResourceList/K8SResourceList.tsx
src/components/ResourceBrowser/Utils.tsx
src/config/searchWorker.ts

User is able to click on the table header and sort the list based on the column selected in ascending or descending order.
Fixes https://github.com/devtron-labs/devtron/issues/5316

feat: Resource Browser: Add sorting functionality to K8sResourcesList Table

---

src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/app/details/triggerView/TriggerView.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
src/config/constants.ts

Fixing check on ciNodeId and workflowId in TriggerView

chore: retain ci modal on refresh

---

src/components/v2/values/chartValuesDiff/ChartValuesView.reducer.ts
src/components/v2/values/chartValuesDiff/ChartValuesView.scss
src/config/searchWorker.ts

fix: add scroll above delete button in configure helm app

chore: add scroll above delete button in configure helm app

---

src/components/EnvironmentOverride/DeploymentTemplateOverrideForm.tsx
src/components/deploymentConfig/DeploymentConfig.tsx
vite.config.ts

fix: Lock config page break

---

package.json
yarn.lock

This PR includes changes to update react select version to 5.8.0
Fixes https://github.com/devtron-labs/devtron/issues/5460

feat: update react select version to 5.8.0

---

src/components/scopedVariables/utils.tsx

This PR includes changes to remove ts no check from utils file of scoped variables

fix: remove ts-no-check from scoped variables utils

---

package.json
src/components/ciConfig/CIContainerRegistryConfig.tsx
src/components/material/MaterialView.tsx
src/css/base.scss
yarn.lock

- add select picker
Fixes https://github.com/devtron-labs/devtron/issues/5474

feat: add single select picker

---

src/components/EnvironmentOverride/DeploymentTemplateOverrideForm.tsx

This PR includes the changes to fix the deployment template override lock config issue

fix: Deployment-template-override-lock-fix

---

src/Pages/Shared/CollapsibleList/CollapsibleList.component.tsx
src/Pages/Shared/CollapsibleList/CollapsibleList.scss
src/Pages/Shared/CollapsibleList/CollapsibleList.types.ts
src/Pages/Shared/CollapsibleList/index.ts
src/Pages/Shared/index.ts
src/assets/icons/ic-stamp.svg

Add New Component - Collapsible List

feat: collapsible list component add

---

src/components/ciPipeline/LinkedCIPipelineEdit.tsx
src/components/workflowEditor/Workflow.tsx
src/components/workflowEditor/WorkflowOptionsModal.tsx
src/components/workflowEditor/workflowEditor.constants.ts

This PR includes fixes for change ci review comments

fix: change ci review

---

src/css/base.scss

feat: add util classes

---

src/components/security/security.service.ts

fix: handle zero time string for security scan listing

fix: handle zero time string for security scan listing

---

src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateOptionsTab.tsx
src/css/base.scss

feat: add css grid styles for split views

---

src/components/gitProvider/GitProvider.tsx

fix: remove default secret placeholder from password field when selected auth mode is not username password

fix: remove default secret placeholder from password field when selected auth mode is not username password

---

src/css/base.scss

chore: refactor dc__striped-row into dc__striped-table

---

package.json
src/App.tsx
src/components/common/navigation/navigation.scss
yarn.lock

feat: add wrapper div for custom theme override

---

src/App.tsx
vite.config.ts

This PR includes fixes of code editor error highlighting and tooltip on deployment template
Fixes https://github.com/devtron-labs/sprint-tasks/issues/734

chore: codeEditor error highlight issue

---

src/App.tsx
src/components/common/navigation/NavigationRoutes.tsx

This PR includes fixes of code editor error highlighting and tooltip on deployment template

fix: codeEditor error highlight issue

---

src/components/CIPipelineN/CreatePluginModal/types.ts
src/components/CIPipelineN/CreatePluginModal/utils.tsx
src/components/CIPipelineN/PluginDetailHeader/CreatePluginButton.tsx

Update input/output variable struct for create plugin.

fix: create plugin

---

src/assets/icons/ic-update-animated.svg
src/components/CIPipelineN/PluginDetailHeader.tsx
src/components/CIPipelineN/TaskTitle.tsx
src/components/app/details/appConfig/constants.ts
src/components/deploymentConfig/DeploymentConfig.tsx
src/components/gitOps/GitProviderTabIcons.tsx
src/components/gitOps/UpdateConfirmationDialog.tsx
src/components/gitOps/UserGitRepo.tsx
src/components/gitOps/utils.ts
src/components/gitProvider/types.ts
src/components/scopedVariables/DescriptionTab.tsx
src/components/scopedVariables/SavedVariablesContent.tsx
src/components/workflowEditor/utils.tsx
src/custom.d.ts

chore: add copyright text

---

src/components/v2/appDetails/sourceInfo/EnvironmentSelector.component.tsx

chore: Release candidate v0.16.0

---

src/components/ConfigMapSecret/ConfigMapSecretForm.tsx

Incorrect api payload for secret ESO data type

fix: secret - incorrect payload in case of ESO data type

---

.github/CODEOWNERS
.github/workflows/pr-issue-validator.yaml

Adds patterns for PR issue validation for repos :  i) devops-sprint
ii) sprint-tasks

chore: Update pr-issue-validator.yaml

---

src/components/ConfigMapSecret/ConfigMapSecretForm.tsx

Incorrect api payload for secret ESO data type
Fixes devtron-labs/devops-sprint#760

chore: secret - incorrect payload in case of ESO data type

---

src/components/security/VulnerabilityExposure.tsx

fix: CVE policy

---

src/components/cdPipeline/CDPipeline.tsx

fix: show delete pipeline button in migrate helm release

---

package.json
src/components/ResourceBrowser/ResourceList/ResourceFilterOptions.tsx
yarn.lock

chore: sync main

---

package.json
src/components/app/details/triggerView/cdMaterial.tsx
src/components/app/details/triggerView/utils.ts
src/components/app/details/triggerView/workflow.service.ts
src/components/cdPipeline/BuildCD.tsx
src/components/cdPipeline/CDPipeline.tsx
src/components/cdPipeline/cdPipeline.types.ts
src/components/workflowEditor/types.ts
src/css/forms.scss
src/css/icons.scss
yarn.lock

feat: add support for any & specific approval type in cd pipeline

feat: add support for any & specific approval type in cd pipeline

---

package.json
src/components/app/details/triggerView/cdMaterial.tsx
yarn.lock

fix: getIsImageApprover check in cdMaterial

---

package.json
src/components/cdPipeline/CDPipeline.tsx
yarn.lock

fix: show error state in deploy tab

---

package.json
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentConfigCompare/utils.tsx
yarn.lock

chore: DeploymentConfigCompare - env selector protected options coming for non-protected envs fix

---

src/components/ApplicationGroup/List/EnvironmentsList.tsx

app group listing for multiple apps 

feat: app group listing search in double click

---

src/components/app/details/appDetails/AppDetails.tsx

fix: app details page breaking in virtual env
Fixes # https://github.com/devtron-labs/sprint-tasks/issues/836

fix: app details page breaking in virtual env

---

src/components/app/details/triggerView/cdMaterial.tsx
src/components/common/GitInfoMaterial.tsx

feat: cd material search

---

package.json
src/components/common/DynamicTabs/useTabs.ts
yarn.lock

fix: replace unsupported Promise.withResolvers with new Promise
Fixes https://github.com/devtron-labs/sprint-tasks/issues/853

chore: fix: replace unsupported Promise.withResolvers with new Promise

---

package.json
yarn.lock

chore: update common-lib version

---

src/components/app/details/appDetails/SourceInfo.tsx

fix: check for image approval configuration in app details from empty length to type

fix: check for image approval configuration in app details from empty length to type

---

src/components/app/details/appDetails/SourceInfo.tsx

fix: check for image approval configuration in app details from empty length to type 
Fixes https://github.com/devtron-labs/devtron/issues/5776

fix: check for image approval configuration in app details from empty length to type 

---

src/components/security/SecurityScansTab/SecurityScansTab.tsx
src/components/security/security.service.ts
src/components/security/security.types.ts

fix: security scans error screen position and error code

fix: security scans error screen

---

src/Pages/Shared/ConfigMapSecret/ConfigMapSecret.container.tsx
src/Pages/Shared/ConfigMapSecret/ProtectedConfigMapSecretDetails.tsx

[Sentry Issue](https://devtron-a6.sentry.io/issues/5786567519/?project=6232011&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&statsPeriod=14d&stream_index=1)

fix: ConfigMapSecret - Null check missing for delete requested cm/secret draft data

---

src/Pages/Shared/ConfigMapSecret/ConfigMapSecret.container.tsx
src/Pages/Shared/ConfigMapSecret/ProtectedConfigMapSecretDetails.tsx

[Sentry](https://devtron-a6.sentry.io/issues/5786567519/?project=6232011&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&statsPeriod=14d&stream_index=1)
Fixes https://github.com/devtron-labs/sprint-tasks/issues/863

chore: ConfigMapSecret - Null check missing for delete requested cm/secret draft data

---

package.json
src/components/ClusterNodes/ClusterSelectionList.tsx
src/css/base.scss
src/css/formulae.scss
yarn.lock

Fixes https://github.com/devtron-labs/devtron/issues/5814

chore: add kube config button to cluster selection list

---

package.json
src/components/ClusterNodes/ClusterSelectionList.tsx
src/css/base.scss
src/css/formulae.scss
yarn.lock

chore: main sync

---

src/components/app/list-new/AppListService.ts
src/components/app/list-new/HelmAppList.tsx
src/components/cluster/Cluster.tsx
src/components/common/navigation/Navigation.tsx
src/components/globalConfigurations/GlobalConfiguration.tsx

chore: sync ea fixes

---

Dockerfile

chore: V0.18 build fix

---

package.json
src/components/globalConfigurations/GlobalConfiguration.tsx
yarn.lock

fix: global config routing

---

package.json
src/components/globalConfigurations/GlobalConfiguration.tsx
yarn.lock

chore: fix global config routes

---

src/components/common/security/ScanDetailsModal.tsx
src/components/security/security.scss

chore: fix security modal scroll height

---

src/Pages/Shared/EnvironmentOverviewTable/EnvironmentOverviewTable.component.tsx
src/Pages/Shared/EnvironmentOverviewTable/EnvironmentOverviewTable.types.ts
src/Pages/Shared/EnvironmentOverviewTable/index.ts
src/components/ApplicationGroup/AppGroup.types.ts
src/components/ApplicationGroup/Details/EnvironmentOverview/EnvironmentOverview.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateModal.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateStatusListDrawer.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/RestartWorkloadModal.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/envOverview.scss

EnvironmentOverview - add support for individual app action

---

package.json
src/components/security/security.scss
yarn.lock

chore: main sync for release candidate 18

---

src/components/charts/discoverChartDetail/DiscoverChartDetails.tsx
src/components/common/formFields/Widgets/Widgets.tsx
src/components/common/helpers/compareVersion.ts
src/components/deploymentConfig/ChartSelectorDropdown.tsx
src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateEditorView.tsx
src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateView.component.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.utils.ts
src/components/v2/values/common/chartValues.api.ts

fix: versionComparatorBySort order & remove unneeded util func

---

src/components/app/list-new/GenericAppList.tsx

remove all cluster call from argo apps listing, show argo apps on cluster selection only

chore: remove all cluster call from argo apps listing

---

package.json
src/components/ResourceBrowser/ResourceList/ResourceBrowserActionMenu.tsx
src/components/app/details/appDetails/AppSecurity.tsx
src/components/app/details/appDetails/SecurityVulnerabilityCard.tsx
src/components/app/details/appDetails/appDetails.type.ts
src/components/app/details/cIDetails/CIDetails.tsx
src/components/app/details/cIDetails/CISecurity.utils.tsx
src/components/app/details/cIDetails/types.tsx
src/components/app/details/triggerView/cdMaterial.tsx
src/components/security/SecurityScansTab/SecurityScansTab.tsx
src/components/v2/appDetails/k8Resource/nodeType/NodeDelete.component.tsx
src/services/service.ts

feat: security migration

---

src/components/app/details/appDetails/AppDetails.tsx
src/components/app/details/appDetails/SourceInfo.tsx
src/components/app/details/appDetails/appDetails.scss
src/components/common/ClusterMetaDataBar/ClusterMetaDataBar.tsx
src/components/common/DeploymentTypeIcon/DeploymentTypeIcon.tsx
src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx
src/components/v2/appDetails/sourceInfo/EnvironmentSelector.component.tsx
src/components/v2/appDetails/sourceInfo/environmentStatus/HelmAppConfigApplyStatusCard.tsx
src/css/base.scss

Fixes https://github.com/devtron-labs/sprint-tasks/issues/928

feat: Virtual Env App Details for Devtron App

---

src/components/app/list-new/AppList.tsx
src/components/app/list-new/AppListService.ts
src/components/app/list-new/AppListType.ts
src/components/app/list-new/HelmAppList.tsx

fix: clusterList/ projectList undefined on refresh so page breaks
fix: app status filter not working on helm apps
fix: clear template type filters on clearing cluster filters

fix: app list filters

---

src/App.tsx
src/components/app/details/triggerView/CiWebhookDebuggingModal.tsx

fix: race condition for offline toast

fix: race condition for offline toast

---

src/components/security/AddCVEPolicy/ExposureList.tsx
src/components/security/AddCVEPolicy/VulnerabilityExposure.tsx
src/components/security/AddCVEPolicy/index.tsx
src/components/security/SecurityPoliciesTab.tsx
src/components/security/security.types.ts

feat: extract cve list and filters from vulnerability exposure

---

src/components/ApplicationGroup/AppGroupDetailsRoute.tsx

Fixes https://github.com/devtron-labs/devtron/issues/5466

fix: App group filter reseting but ui says filter applied after doing any bulk actions on applied filter

---

src/components/ApplicationGroup/Details/EnvironmentOverview/EnvironmentOverview.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/RestartWorkloadModal.tsx
vite.config.mts

Access Denied (error 404) when we Refresh Restart Workload in AppGroup
Fixes https://github.com/devtron-labs/devtron/issues/5338

fix: Access Denied (error 404) when we Refresh Restart Workload in AppGrou

---

src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentConfigCompare/DeploymentConfigCompare.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentConfigCompare/utils.ts
src/Pages/Applications/DevtronApps/Details/AppConfigurations/Navigation/EnvConfigurationsNav.tsx
src/Pages/Shared/ConfigMapSecret/ProtectedConfigMapSecretDetails.tsx
src/components/ApplicationGroup/Details/EnvCDDetails/EnvCDDetails.tsx
src/components/app/details/cdDetails/CDDetails.tsx
src/components/app/details/cdDetails/cdDetail.scss
src/components/app/details/triggerView/PipelineConfigDiff/PipelineConfigDiff.tsx
src/components/app/details/triggerView/PipelineConfigDiff/usePipelineDeploymentConfig.ts
src/components/app/details/triggerView/cdMaterial.tsx

feat: cdDetails, EnvCDDetails - DeploymentHistoryConfigDiff - revamp UI - using DeploymentConfigDiff

---

src/components/ClusterNodes/ClusterOverview.tsx
src/components/globalConfigurations/GlobalConfiguration.tsx

fix: redirection to chart store and hide scope variables in EA only mode
Fixes https://github.com/devtron-labs/sprint-tasks/issues/972

chore: fix: redirection to chart store and hide scope variables in EA only mode

---

package.json
src/assets/icons/ic-close.svg
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/Terminal.tsx
src/components/v2/assets/icons/ic-close.svg
yarn.lock

fix: close icon override for ic-close

fix: close icon override for ic-close

---

src/components/app/details/triggerView/CiWebhookDebuggingModal.tsx
src/components/app/list/list.scss
src/css/base.scss

fix: styling issue for config toolbar

fix: styling issue for command bar

---

package.json
src/components/ApplicationGroup/AppGroup.service.ts
src/components/ClusterNodes/ClusterOverview.tsx
src/components/ResourceBrowser/ResourceList/ResourceBrowserActionMenu.tsx
src/components/app/details/appDetails/AppSecurity.tsx
src/components/app/details/appDetails/SecurityVulnerabilityCard.tsx
src/components/app/details/cIDetails/CIDetails.tsx
src/components/app/details/triggerView/cdMaterial.tsx
src/components/v2/appDetails/k8Resource/nodeType/NodeDelete.component.tsx
src/components/v2/appDetails/sourceInfo/environmentStatus/EnvironmentStatus.component.tsx
src/components/v2/chartDeploymentHistory/ChartDeploymentHistory.component.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
src/css/base.scss
yarn.lock

feat: add column for security policy in security modal

feat: add column for security policy in security modal

---

package.json
yarn.lock

fix: add null check in tab group

---

src/components/ApplicationGroup/Details/EnvironmentOverview/EnvironmentOverview.tsx

chore: EnvironmentOverview - Enterprise check missing for deploymentWindow loading

---

package.json
yarn.lock

chore: version bump

---

src/components/ClusterNodes/ClusterTerminal.tsx
src/components/app/list-new/AppListService.ts
src/components/app/list-new/AppListType.ts
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/TerminalWrapper.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/terminal.utils.tsx
src/css/base.scss

1. Node Tab issue fix
2. Helm cluster csv bug
Fixes https://github.com/devtron-labs/sprint-tasks/issues/992

chore: cluster terminal node issue fix

---

package.json
yarn.lock

chore: common-lib version bump

---

src/components/ApplicationGroup/AppGroup.service.ts
src/components/app/details/appDetails/AppDetails.tsx
src/components/app/list-new/AppListService.ts
src/components/app/list-new/AppListType.ts

fix: app group listing

---

src/components/app/list-new/HelmAppList.tsx

fix: helm app search based on chart name

chore: fix helm app search based on chart name

---

package.json
src/components/v2/appDetails/sourceInfo/environmentStatus/EnvironmentStatus.component.tsx
src/components/v2/chartDeploymentHistory/ChartDeploymentHistory.component.tsx
src/css/base.scss
yarn.lock

chore: V19-sync-to-v20

---

package.json
src/Pages/Applications/DevtronApps/Details/AppConfigurations/Navigation/EnvironmentOverrideRouter.tsx
src/components/CIPipelineN/TaskTypeDetailComponent.tsx
yarn.lock

1. Job select picker UI
2. CD Container Image Select Picker

fix: select picker UI

---

src/components/cdPipeline/BuildCD.tsx
src/components/cdPipeline/CDPipeline.tsx

fix: approval toggle break

---

src/components/app/details/appDetails/AppDetails.tsx

fix: AppDetails - Env SelectPicker - menu z-index

---

package.json
src/components/CIPipelineN/EnvironmentList.tsx
src/components/app/details/appDetails/AppDetails.tsx
yarn.lock

1. Code revert in Release due to dropdown diff view like value container should be a chip.
2. In job > Shrinken label to avoid wrapping text
3. Job > Excute runbook
4. User permission list > Action text jumping
5.
6. Overlapping of environment in App details
7. ![Image](https://github.com/user-attachments/assets/12ff6655-5b9d-453e-9b35-7849708ba4a9)

fix: select picker

---

package.json
yarn.lock

chore: bump common to 0.5.0

---

.github/workflows/pr-issue-validator.yaml

chore: sync rc v20 with main

---

src/components/app/list-new/AppList.tsx
yarn.lock

fix: export csv button

---

src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx

fix: z-index fix

---

package.json
src/Pages/Shared/LinkedCIDetailsModal/LinkedCIDetailsModal.tsx
yarn.lock

1. chart select label
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1059

fix: Hotfix v0.20.0

---

src/Pages/Applications/DevtronApps/Details/AppConfigurations/Navigation/Navigation.helper.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretContainer.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretDeleteModal.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretForm.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretProtected.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretReadyOnly.tsx
src/Pages/Shared/ConfigMapSecret/styles.scss
src/Pages/Shared/ConfigMapSecret/types.ts
src/Pages/Shared/ConfigMapSecret/utils.ts
src/Pages/Shared/ConfigMapSecret/validations.ts

fix: ConfigMapSecret - UAT changes

---

package.json
src/Pages/GlobalConfigurations/Authorization/Shared/components/AppPermissions/AppPermissionDetail.tsx
src/Pages/GlobalConfigurations/Authorization/Shared/components/AppPermissions/AppPermissions.component.tsx
src/Pages/GlobalConfigurations/Authorization/Shared/components/AppPermissions/DirectPermission.tsx
src/Pages/GlobalConfigurations/Authorization/Shared/components/AppPermissions/common.tsx
src/Pages/GlobalConfigurations/Authorization/Shared/components/AppPermissions/constants.ts
src/Pages/GlobalConfigurations/Authorization/Shared/components/AppPermissions/types.ts
src/Pages/GlobalConfigurations/Authorization/Shared/components/AppPermissions/utils.ts
src/Pages/GlobalConfigurations/Authorization/Shared/components/K8sObjectPermissions/K8sListItemCard.tsx
src/Pages/GlobalConfigurations/Authorization/Shared/components/K8sObjectPermissions/utils.tsx
src/Pages/GlobalConfigurations/Authorization/Shared/components/PermissionConfigurationForm/PermissionConfigurationFormProvider.tsx
src/Pages/GlobalConfigurations/Authorization/authorization.service.ts
src/Pages/GlobalConfigurations/Authorization/constants.ts
src/Pages/GlobalConfigurations/Authorization/types.ts
src/Pages/GlobalConfigurations/Authorization/utils.ts
src/components/ciPipeline/Webhook/WebhookDetailsModal.tsx
src/config/constants.ts
src/index.tsx
src/services/service.ts
src/services/service.types.ts
vite.config.mts
yarn.lock

terminal permission for devtron and helm apps

feat: terminal permission for devtron and helm apps

---

src/Pages/Shared/ConfigMapSecret/ConfigMapSecretContainer.tsx
src/Pages/Shared/ConfigMapSecret/types.ts
src/Pages/Shared/ConfigMapSecret/utils.ts

fix: ConfigMapSecret - scope variables not resolving in some cases - logic revamped

---

package.json
src/Pages/Applications/DevtronApps/Details/AppConfigurations/AppConfig.types.ts
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/AppComposeRouter.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentConfigCompare/DeploymentConfigCompare.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentTemplate/DeploymentTemplate.scss
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentTemplate/DeploymentTemplate.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/Navigation/AppNavigation.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/Navigation/EnvConfigurationsNav.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/Navigation/Navigation.helper.tsx
src/Pages/Releases/Detail/Configurations/Configurations.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretContainer.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretReadyOnly.tsx
src/Pages/Shared/ConfigMapSecret/styles.scss
src/Pages/Shared/ConfigMapSecret/types.ts
src/Pages/Shared/ConfigMapSecret/utils.ts
src/Pages/Shared/ConfigMapSecret/validations.ts
src/Pages/Shared/EnvironmentOverride/environmentOverride.scss
src/components/ApplicationGroup/Details/EnvironmentConfig/ApplicationRoutes.tsx
src/components/ApplicationGroup/Details/EnvironmentConfig/EnvConfig.tsx
src/components/app/details/cdDetails/cdDetail.scss
src/css/base.scss
yarn.lock

fix: Release App Configurations Bug Fixes

---

package.json
yarn.lock

chore: sync rc-21 with develop

---

src/components/ciPipeline/Webhook/WebhookDetailsModal.tsx

Fixes https://github.com/devtron-labs/devops-sprint/issues/1161

fix: api token creation payload in webhook details modal

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/TerminalWrapper.component.tsx

fix: - TerminalWrapperComponent - z-index fix

---

src/components/app/details/triggerView/PipelineConfigDiff/PipelineConfigDiff.tsx
src/components/app/details/triggerView/PipelineConfigDiff/usePipelineDeploymentConfig.ts
src/components/app/details/triggerView/cdMaterial.tsx
src/components/v2/appDetails/NodeTreeDetailTab.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/TerminalWrapper.component.tsx
src/config/routes.ts

Fixes https://github.com/devtron-labs/devops-sprint/issues/1204

fix: PipelineConfigDiff - refactored path handling

---

src/components/app/details/triggerView/PipelineConfigDiff/PipelineConfigDiff.tsx
src/components/app/details/triggerView/PipelineConfigDiff/usePipelineDeploymentConfig.ts
src/components/app/details/triggerView/cdMaterial.tsx
src/components/v2/appDetails/NodeTreeDetailTab.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/TerminalWrapper.component.tsx
src/config/routes.ts

chore: sync with main

---

package.json
src/components/ApplicationGroup/AppGroupAppFilter.components.tsx
src/components/ApplicationGroup/AppGroupAppFilter.tsx
src/components/app/list-new/AppList.tsx
src/components/app/list-new/AppListFilters.tsx
src/components/app/list-new/Constants.ts
src/components/app/list-new/list.utils.ts
yarn.lock

chore: sync persist filters

---

package.json
src/components/ResourceBrowser/Constants.ts
src/components/ResourceBrowser/ResourceList/ClusterSelector.tsx
src/components/ResourceBrowser/ResourceList/ResourceList.tsx
src/components/ResourceBrowser/Types.ts
src/components/ResourceBrowser/Utils.tsx
src/components/app/types.ts
src/components/common/DynamicTabs/DynamicTabs.tsx
src/components/common/DynamicTabs/Types.ts
src/components/common/DynamicTabs/Utils.ts
src/components/common/DynamicTabs/useTabs.ts
src/config/routes.ts
yarn.lock

This PR includes changes:
- to support monitoring tab in resource browser by making changes and migration of types for DynamicTabs.
- to add new view through fixedTabComponents.

feat: rb monitoring

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx
src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx

chore: retain resource tree health status filters on resource change

---

src/components/dockerRegistry/Docker.tsx

fix: docker registry page break

---

src/components/dockerRegistry/Docker.tsx
src/components/v2/appDetails/sourceInfo/EnvironmentSelector.component.tsx

chore: sync rc 22 with main

---

src/components/ClusterNodes/NodeActions/NodeActionsMenu.tsx
src/components/ClusterNodes/NodeDetailsList.tsx
src/components/ClusterNodes/clusterNodes.scss
src/components/cluster/ClusterForm.tsx

fix: node list ui issues and cluster form breaking

---

src/components/common/navigation/Navigation.tsx

feat: Release Watcher available in EA mode

---

src/components/app/details/triggerView/cdMaterial.tsx

fix: redirection issue in cd material

fix: redirection issue in cd material

---

src/components/app/details/triggerView/cdMaterial.tsx

chore: fix: redirection issue in cd material

---

package.json
src/components/ClusterNodes/NodeDetailsList.tsx
yarn.lock

fix: resizable columns and node list overflow

fix: resizable columns and node list overflow

---

src/Pages/ResourceBrowser/ClusterList/ClusterMap/ClusterMap.tsx
src/components/ClusterNodes/NodeDetailsList.tsx

fix: node listing scroll and error column

fix: node listing scroll and error column

---

src/components/ClusterNodes/ClusterSelectionList.tsx
src/components/ClusterNodes/NodeDetailsList.tsx

fix: sorting issue with cpu usage and z index for cluster listing

---

package.json
yarn.lock

fix: hide config diff for external secret

---

src/Pages/ResourceBrowser/ClusterList/ClusterMap/ClusterMap.tsx
src/components/ClusterNodes/ClusterSelectionList.tsx
src/components/ClusterNodes/NodeDetailsList.tsx

chore: sync kubecon-2024 with develop

---

src/components/app/list-new/AppListFilters.tsx
src/components/app/list-new/AppListService.ts
src/components/app/list/DevtronAppListContainer.tsx

fix: export csv devtron app list 

fix: export csv devtron app list 

---

src/components/ApplicationGroup/AppGroup.utils.ts
src/components/ApplicationGroup/Details/TriggerView/BulkCITrigger.tsx

fix: payload for webhook type in mandatory plugin data

fix: payload for webhook type in mandatory plugin data

---

src/components/ApplicationGroup/Details/TriggerView/BulkCITrigger.tsx
src/components/app/details/triggerView/BranchRegexModal.tsx
src/components/app/details/triggerView/CiWebhookDebuggingModal.tsx
src/components/app/details/triggerView/WebhookReceivedPayloadModal.tsx
src/components/app/details/triggerView/types.ts
src/components/common/helpers/GitInfoMaterialCard/GitInfoMaterial.tsx

fix: css fixes for webhook

---

src/components/ApplicationGroup/Details/TriggerView/BulkCITrigger.tsx

chore: back icon support in bulk webhook modal

---

src/components/ResourceBrowser/ResourceList/BaseResourceList.tsx
src/components/ResourceBrowser/ResourceList/K8SResourceList.tsx

fix: wrong bulk selection checkbox status on namespace change

---

src/components/CIPipelineN/AdvancedConfigOptions.tsx
src/components/CIPipelineN/Build.tsx

Fixes https://github.com/devtron-labs/devtron-enterprise/issues/1780

fix: state override issue with target platform select in docker config override

---

package.json
yarn.lock

chore: bump common to 1.1.0

---

src/components/CIPipelineN/ciPipeline.utils.tsx
src/components/ResourceBrowser/ResourceList/BaseResourceList.tsx
src/components/ResourceBrowser/ResourceList/ColumnSelector.tsx
src/components/ResourceBrowser/ResourceList/utils.tsx
src/components/ResourceBrowser/Types.ts
src/css/base.scss

- Add support for field decorations for specific columns as in node details list
- Replace column selector with select picker

fix: add error icon for errors column & colors in status column; replace column selector with select picker

---

src/components/ResourceBrowser/ResourceList/BaseResourceList.tsx
src/components/ResourceBrowser/ResourceList/K8SResourceList.tsx
src/components/ResourceBrowser/ResourceList/ResourceList.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1336

fix: key mismatch for resource list and redirection for events

---

src/Pages/Releases/Detail/Configurations/Configurations.tsx
src/Pages/Shared/EnvironmentOverride/EnvironmentOverride.tsx

fix: Release Configurations, EnvironmentOverride - incorrect key, data is getting persisted while switching cm/cs

---

src/components/ResourceBrowser/ResourceList/ResourceList.tsx
src/components/common/DynamicTabs/useTabs.ts

fix: dont render tab components unless tabs get initialized

---

src/components/charts/charts.service.ts
src/components/charts/charts.types.tsx

fix: force flag instead of forceDelete in installed charts
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1241

fix: force flag instead of forceDelete in installed charts

---

src/components/ApplicationGroup/AppGroupDetailsRoute.tsx
src/components/app/details/main.tsx

fix: app group filters loading

---

src/components/ResourceBrowser/ResourceList/K8SResourceTabComponent.tsx

fix: show error screen manager for 403 from k8s/api-resources

---

src/components/ApplicationGroup/Details/TriggerView/BulkCITrigger.tsx

fix: material prop to WebhookReceivedPayloadModal in BulkCITrigger

chore: material prop to WebhookReceivedPayloadModal in BulkCITrigger

---

package.json
yarn.lock

fix: diff viewer title issue

---

package.json
yarn.lock

chore: rc 24 main sync

---

package.json
src/components/app/details/appDetails/AppDetails.tsx
src/components/app/details/appDetails/appDetails.type.ts
src/components/app/details/triggerView/cdMaterial.tsx
src/components/app/service.ts
src/components/workflowEditor/nodes/CDNode.tsx
yarn.lock

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1426

fix: handle 7000 status code from BE for env delete case

---

src/Pages/Applications/DevtronApps/Details/AppConfigurations/AppConfig.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/AppConfig.types.ts
src/Pages/Applications/DevtronApps/Details/AppConfigurations/AppConfiguration.provider.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/AppComposeRouter.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/ConfigToolbar.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentConfigCompare/DeploymentConfigCompare.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentTemplate/DeploymentTemplate.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentTemplate/constants.ts
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/types.ts
src/Pages/Applications/DevtronApps/Details/AppConfigurations/Navigation/AppNavigation.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/Navigation/EnvConfigurationsNav.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/Navigation/EnvironmentOverrideRouter.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/Navigation/Navigation.helper.tsx
src/Pages/Releases/Detail/Configurations/Configurations.tsx
src/Pages/Releases/Detail/Configurations/types.ts
src/Pages/Shared/ConfigMapSecret/ConfigMapSecret.service.ts
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretContainer.tsx
src/Pages/Shared/EnvironmentOverride/EnvironmentOverride.tsx
src/Pages/Shared/EnvironmentOverride/EnvironmentOverrides.types.ts
src/components/ApplicationGroup/AppGroup.types.ts
src/components/ApplicationGroup/Details/EnvironmentConfig/ApplicationRoutes.tsx
src/components/ApplicationGroup/Details/EnvironmentConfig/EnvConfig.tsx
src/components/app/details/triggerView/TriggerView.tsx
src/components/app/details/triggerView/workflow.service.ts

fix: code review changes

---

.github/workflows/pr-issue-validator.yaml
src/components/common/DatePickers/calendar.css

fix: z-index for day picker
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1458

fix: z-index for day picker

---

.github/workflows/pr-issue-validator.yaml
src/components/common/DatePickers/calendar.css

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1458

fix: app detail date picker main

---

src/components/common/Description/GenericDescription.tsx

fix: cluster description not authorized issue
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1463

fix: cluster description not authorized issue

---

src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/AppComposeRouter.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentTemplate/DeploymentTemplate.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentTemplate/types.ts

fix: check for hiding chart change iff base is saved and use merged template check to derive scoped variable base state in published values

fix: check for hiding chart change iff base is saved and use merged template check to derive scoped variable base state in published values

---

package.json
src/Pages/GlobalConfigurations/Authorization/constants.ts
yarn.lock

chore: fix hidden selected input in user auth

---

src/components/app/details/appDetails/AppMetrics.tsx

fix: add optional chaining for pod labels in AppMetrics component

fix: add optional chaining for pod labels in AppMetrics component

---

package.json
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentConfigCompare/DeploymentConfigCompare.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretContainer.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretDryRun.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretForm.tsx
src/Pages/Shared/ConfigMapSecret/utils.ts
yarn.lock

fix: CM CS Patch Bug Fixes

---

package.json
src/Pages/Applications/DevtronApps/Details/AppConfigurations/AppConfig.constants.ts
src/Pages/Applications/DevtronApps/Details/AppConfigurations/AppConfig.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/AppConfig.utils.ts
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/ConfigToolbar.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentTemplate/DeploymentTemplate.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/types.ts
src/Pages/Applications/DevtronApps/Details/AppConfigurations/Navigation/EnvConfigurationsNav.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretContainer.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretForm.tsx
src/components/app/details/appDetails/SourceInfo.tsx
src/components/app/types.ts
yarn.lock

fix: migrate to use isApprovalPolicyApplicable

---

src/components/externalLinks/ExternalLinks.component.tsx
src/components/externalLinks/ExternalLinks.service.ts
src/components/externalLinks/ExternalLinks.type.ts
src/components/externalLinks/ExternalLinksCRUD/AddExternalLink.scss
src/components/externalLinks/ExternalLinksCRUD/AddExternalLink.tsx
src/components/externalLinks/ExternalLinksCRUD/ConfigureLinkAction.tsx
src/components/externalLinks/externalLinks.component.scss
src/config/constants.ts
src/css/base.scss

Add query parameter to show overlay or redirection 
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1408

feat: add check to open overlay by clicking on icon

---

package.json
yarn.lock

chore: fix dependabot for nanoid

---

src/components/CIPipelineN/VariableDataTable/utils.tsx

fix: VariableDataTable - incorrect check for payload fix

---

src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentConfigCompare/DeploymentConfigCompare.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentConfigCompare/types.ts
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentConfigCompare/utils.ts
src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx
src/components/ApplicationGroup/Details/TriggerView/BulkCITrigger.tsx
src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/app/details/triggerView/cdMaterial.tsx
src/components/app/details/triggerView/ciMaterial.tsx

chore: config compare & runtime params

---

src/components/security/SecurityPolicyEdit.tsx
src/components/security/security.scss
src/components/security/security.types.ts

fix: scroll does not retain on updating severity in security policies

chore: scroll does not retain on updating severity in security policies

---

package.json
src/components/CIPipelineN/VariableDataTable/ValueConfigOverlay.tsx
src/components/CIPipelineN/VariableDataTable/VariableDataTablePopupMenu.tsx
yarn.lock

chore: variable data table popup menu

---

src/components/CIPipelineN/VariableDataTable/VariableDataTable.component.tsx

chore: VariableDataTable - hide row action config for oss

---

package.json
yarn.lock

chore: bump common

---

package.json
src/components/app/details/appDetails/AppDetails.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/TerminalWrapper.component.tsx
src/css/base.scss

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1580

fix: z-index issue for terminal selector

---

src/css/base.scss

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1580

fix: z-index for env selector and page header

---

package.json
src/css/base.scss
yarn.lock

fix: pattern start end alphanumeric

---

.github/workflows/sentry-source-map-upload.yaml

chore: sentry source map upload action

---

src/css/base.scss

fix: replace break-all to break-word in clamp-3

fix: replace break-all to break-word in clamp-3

---

package.json
src/Pages/GlobalConfigurations/Authorization/Shared/components/AppPermissions/EnvironmentSelector.tsx
yarn.lock

fix: EnvironmentSelector - missing clusterName data in option fix

---

package.json
yarn.lock

chore: update devtron-fe-common-lib to version 1.3.6

chore: update devtron-fe-common-lib to version 1.3.6

---

package.json
yarn.lock

chore: update devtron-fe-common-lib to version 1.3.0-patch-3
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1605

chore: update devtron-fe-common-lib to version 1.3.0-patch-3

---

package.json
src/components/app/details/appDetails/SecurityVulnerabilityCard.tsx
src/components/app/details/cIDetails/CIDetails.tsx
src/components/app/details/triggerView/cdMaterial.tsx
src/components/v2/appDetails/sourceInfo/environmentStatus/EnvironmentStatus.component.tsx
src/components/v2/chartDeploymentHistory/ChartDeploymentHistory.component.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.reducer.ts
src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
yarn.lock

fix: integrate scans

---

src/components/app/details/appDetails/SecurityVulnerabilityCard.tsx

chore: security card not showing in helm app details

---

package.json
src/components/ApplicationGroup/Details/TriggerView/BulkCITrigger.tsx
src/components/CIPipelineN/VariableDataTable/ValueConfigOverlay.tsx
yarn.lock

fix: misc issues

---

src/Pages/Applications/DevtronApps/Details/AppConfigurations/AppConfig.types.ts
src/Pages/Applications/DevtronApps/Details/AppConfigurations/Navigation/AppNavigation.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/Navigation/EnvConfigurationsNav.tsx
src/Pages/Releases/Detail/Configurations/Configurations.tsx
src/components/ApplicationGroup/Details/EnvironmentConfig/ApplicationRoutes.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1629

fix: use paramsToCheck for approval config

---

package.json
src/css/base.scss
yarn.lock

chore: enhance dc__unset-pre class for better text wrapping

---

package.json
src/components/app/Overview/Overview.tsx
yarn.lock

feat: add useBuildXDriver for build infra
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1658
QA

feat: add useBuildXDriver for build infra

---

src/components/externalLinks/ExternalLinks.service.ts
src/components/externalLinks/ExternalLinksCRUD/AddExternalLink.tsx

Fixes https://github.com/devtron-labs/devtron/issues/6271

fix: re-generate the encoded url for external links

---

src/components/notifications/WebhookConfigurationTable.tsx

fix: webhook header changed to sticky

---

package.json
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentConfigCompare/DeploymentConfigCompare.tsx
src/components/app/details/triggerView/PipelineConfigDiff/PipelineConfigDiff.tsx
src/components/app/details/triggerView/PipelineConfigDiff/usePipelineDeploymentConfig.ts
yarn.lock

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1652

feat: PipelineConfigDiff, DeploymentConfigCompare - add default sorting - ASC order

---

src/components/app/details/triggerView/CIMaterialModal.tsx

chore: fix: unnecessary parentheses in ci material modal

---

src/components/charts/charts.helper.ts
src/components/v2/values/chartValuesDiff/ChartValuesEditor.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.component.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1749

fix: helm chart version sorting

---

src/components/notifications/SMTPConfigModal.tsx

fix: smtp payload fix

---

index.css

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1641

fix: initial loader color

---

package.json
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentConfigCompare/DeploymentConfigCompare.tsx
src/components/app/details/triggerView/PipelineConfigDiff/PipelineConfigDiff.tsx
src/components/app/details/triggerView/PipelineConfigDiff/usePipelineDeploymentConfig.ts
src/components/app/details/triggerView/cdMaterial.tsx
yarn.lock

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1652

refactor: DeploymentConfigCompare, PipelineConfigDiff - sorting logic refactor

---

package.json
src/components/app/details/appDetails/SecurityVulnerabilityCard.tsx
yarn.lock

Fixes  https://github.com/devtron-labs/sprint-tasks/issues/1782

chore: check codeScan and manifestScan for card status

---

package.json
src/css/base.scss
yarn.lock

chore: add vertical modifier for dc__separated-flexbox

---

src/components/app/details/triggerView/ciMaterial.tsx

In  Regex webhook modal 2 calls of material api hitting on save

fix: Regex webhook call triggerred

---

package.json
src/css/base.scss
yarn.lock

chore: rc 27 sync

---

src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.api.ts

chore: short circuit appDetails check using isResourceBrowserView in getManifestResource

---

src/components/app/details/appDetails/utils.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1816

fix: time range selector issue in app metrics

---

src/components/app/details/appDetails/utils.tsx
src/components/app/details/triggerView/cdMaterial.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1816

fix: time range selector issue in app metrics & config diff sorting

---

src/components/app/details/appDetails/utils.tsx
src/components/app/details/triggerView/cdMaterial.tsx

chore: sync develop with main

---

src/components/app/details/appDetails/AppMetrics.tsx
src/components/app/details/appDetails/GraphsModal.tsx
src/components/app/details/appDetails/constants.ts
src/components/app/details/appDetails/utils.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1816

fix: parsing issues with date and time

---

package.json
src/Pages/Applications/DevtronApps/Details/AppConfigurations/AppConfig.tsx
src/Pages/GlobalConfigurations/Authorization/APITokens/DeleteAPITokenModal.tsx
src/Pages/GlobalConfigurations/Authorization/UserPermissions/AddEdit/UserForm.tsx
src/Pages/GlobalConfigurations/Authorization/UserPermissions/DeleteUserPermission.tsx
src/Pages/GlobalConfigurations/ClustersAndEnvironments/EnvironmentDeleteComponent.tsx
src/components/cluster/Cluster.tsx
src/components/cluster/ClusterForm.tsx
src/components/dockerRegistry/Docker.tsx
src/components/gitProvider/GitProvider.tsx
src/components/material/MaterialView.tsx
src/components/notifications/NotificationTab.tsx
src/components/project/Project.tsx
src/components/v2/appDetails/k8Resource/nodeType/NodeDelete.component.tsx
src/components/workflowEditor/workflowEditor.tsx

1. Removed data test id from deleteConfirmation modal
2. UAT fixes

chore: uat fixes

---

src/Pages/GlobalConfigurations/Authorization/Shared/components/AppPermissions/AppPermissions.component.tsx
src/components/Jobs/Service.ts

chore: sync job sorting

---

src/components/ResourceBrowser/ResourceList/ResourceList.tsx
src/components/ResourceBrowser/ResourceList/Sidebar.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1825

fix: reload k8s resource map on new custom resource definition

---

src/components/ResourceBrowser/ResourceList/ResourceList.tsx
src/components/common/DynamicTabs/types.ts
src/components/common/DynamicTabs/useTabs.ts

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1825

fix: override tab selection on url change in resource list

---

package.json
src/components/ResourceBrowser/ResourceList/BaseResourceList.tsx
src/components/ResourceBrowser/ResourceList/utils.tsx
src/index.tsx
yarn.lock

chore: version bump for common and sync with main

---

package.json
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentConfigCompare/DeploymentConfigCompare.tsx
src/components/app/details/triggerView/PipelineConfigDiff/usePipelineDeploymentConfig.ts
src/components/app/details/triggerView/cdMaterial.tsx
yarn.lock

chore: Sort Order resetting when changing comparison option fix

---

src/components/v2/values/chartValuesDiff/ChartValuesView.reducer.ts

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1878

fix: helm deployment app type

---

src/components/v2/values/chartValuesDiff/ChartValuesView.reducer.ts

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1878

fix: helm app deployment type

---

.github/CODEOWNERS
.github/workflows/sentry-source-map-upload.yaml
Dockerfile

chore: fix issue with git hash in sentry release version

---

package.json
src/components/onboardingGuide/OnboardingGuide.tsx
src/components/onboardingGuide/onboarding.utils.ts
src/config/constants.ts
src/services/service.ts
yarn.lock

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1872

fix: Panic in orchestrator in /orchestrator/telemetry/event

---

package.json
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentTemplate/GUIView/GUIView.component.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretDryRun.tsx
src/components/ResourceBrowser/ResourceList/CreateResource.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
yarn.lock

chore: CodeEditor Styling Fixes

---

src/components/v2/values/chartValuesDiff/ChartValuesView.reducer.ts

chore: add null check for reading valuesSchemaJson from installedConfigFromParent

---

src/components/globalConfigurations/GlobalConfiguration.tsx
src/components/globalConfigurations/globalConfigurations.scss
src/components/globalConfigurations/utils.ts
src/css/base.scss

feat: hide global config page-header & sidebar on DevtronAppTemplateDetail page

---

src/css/base.scss

feat: template create

---

src/Pages/App/CreateAppModal/CreateAppModal.component.tsx
src/components/globalConfigurations/GlobalConfiguration.tsx

fix: integration issues for application templates

---

src/Pages/App/CreateAppModal/Workflow/Workflow.tsx
src/Pages/App/CreateAppModal/Workflow/utils.tsx

fix: AppTemplate Workflow - handling of nodes when id is same, null state when no workflows are present

---

package.json
yarn.lock

chore: update common-lib verion

---

src/Pages/App/CreateAppModal/CreateAppModal.component.tsx
src/Pages/App/CreateAppModal/styles.scss

feat: show only one loader in create app from template

---

src/components/app/list/DevtronAppListContainer.tsx
src/components/app/list/list.scss
src/components/cluster/ClusterForm.tsx

fix: re-align settings icon in app list when argo is not installed and stick edit/create cluster footer to bottom

---

package.json
src/Pages/GlobalConfigurations/Authorization/UserPermissions/DeleteUserPermission.tsx
src/Pages/GlobalConfigurations/ClustersAndEnvironments/EnvironmentDeleteComponent.tsx
src/Pages/Shared/ApplicationDeletionInfo/ApplicationDeletionInfo.tsx
src/Pages/Shared/ApplicationDeletionInfo/types.ts
src/assets/icons/ic-rollback-medium.svg
src/components/app/list-new/AppList.tsx
src/components/v2/values/chartValuesDiff/DeleteChartDialog.tsx
src/stories/Textarea.stories.tsx
yarn.lock

chore: bump common to 1.7.0

---

src/Pages/GlobalConfigurations/DeploymentCharts/List/DeploymentChartsList.component.tsx

This PR includes QA fixes and UAT enhancements for hibernation patch

fix: hibernation patch

---

src/components/cdPipeline/MigrateToDevtron/MigrateFromArgo.tsx
src/components/cdPipeline/MigrateToDevtron/service.ts
src/components/cdPipeline/MigrateToDevtron/utils.tsx
src/components/cdPipeline/cdPipeline.types.ts
src/components/cluster/Cluster.tsx
src/components/cluster/ClusterForm.tsx
src/components/cluster/cluster.type.ts

Add nesting for argo level struct in validate migration source and fix redirection on cluster update.

fix: update validate migration spec

---

src/components/common/DynamicTabs/useTabs.ts

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1920

fix: only initialize local storage data if persistence key match

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Events.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/EventsTable.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1826

fix: theming issue in cluster events

---

src/Pages/Releases/Detail/Configurations/Configurations.tsx

chore: Release Configurations - fix redirection on app change

---

package.json
src/components/CIPipelineN/VariableDataTable/VariableDataTable.component.tsx
src/components/CIPipelineN/VariableDataTable/constants.ts
src/components/CIPipelineN/VariableDataTable/utils.tsx
src/components/CIPipelineN/VariableDataTable/validations.ts
yarn.lock

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1965

feat: enhance variable data table to support boolean values and validations

---

src/Pages/GlobalConfigurations/Authorization/Shared/components/AppPermissions/AppPermissions.component.tsx

fix: authorization projects

---

.github/workflows/pr-issue-validator.yaml

misc: Update pr-issue-validator.yaml

---

src/components/Jobs/ExpandedRow/ExpandedRow.scss
src/components/app/list/expandedRow/ExpandedRow.tsx
src/components/app/list/expandedRow/expandedRow.css

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1971

fix: app listing status line overflow

---

src/Pages/GlobalConfigurations/Authorization/APITokens/APITokenList.tsx
src/Pages/GlobalConfigurations/Authorization/APITokens/apiToken.scss
src/components/bulkEdits/BulkEdits.tsx
src/components/bulkEdits/bulkEdit.scss
src/components/bulkEdits/bulkedit.utils.tsx
src/components/bulkEdits/constants.ts
src/components/externalLinks/ExternalLinkList.tsx
src/components/externalLinks/ExternalLinks.component.tsx
src/components/externalLinks/ExternalLinks.utils.tsx
src/components/externalLinks/ExternalLinksCRUD/ConfigureLinkAction.tsx
src/components/externalLinks/styles.scss

feat: calc cleanup dashboard

---

package.json
src/components/cdPipeline/CDPipeline.tsx
src/components/cdPipeline/MigrateToDevtron/ClusterSelect.tsx
src/components/cdPipeline/MigrateToDevtron/MigrateToDevtron.component.tsx
src/components/cdPipeline/MigrateToDevtron/MigrateToDevtronValidationFactory.tsx
src/components/cdPipeline/MigrateToDevtron/service.tsx
src/css/base.scss
src/css/iconTheming.scss
src/index.tsx
src/stories/InfoBlock.stories.tsx
yarn.lock

Add required changes for UAT:
- Add border for loading state and error state in feasibility view.
- Replace InfoColourBar to InfoBlock in Validation Factory.
- Replace Helm fallback icon.
- Update messages for loading and error.

UAT: migrate helm app

---

src/components/app/details/triggerView/CIMaterialModal.tsx
src/components/app/details/triggerView/CiWebhookDebuggingModal.tsx
src/components/app/details/triggerView/MaterialSource.tsx
src/components/app/details/triggerView/WebhookReceivedPayloadModal.tsx
src/components/app/details/triggerView/triggerView.scss
src/components/app/details/triggerView/types.ts
src/components/common/helpers/GitInfoMaterialCard/GitInfoMaterial.tsx
src/components/globalConfigurations/globalConfigurations.scss
src/css/triggerView.scss

feat: calc cleanup v2

---

src/components/cdPipeline/DeleteCDNode.tsx
src/components/cluster/ClusterForm.tsx
src/css/base.scss

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1977

fix: On Cluster deletion throw irrelevant error of cannot delete 

---

src/Pages/Applications/DevtronApps/Details/AppConfigurations/AppConfig.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentTemplate/DeploymentTemplate.scss
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentTemplate/DeploymentTemplate.tsx
src/Pages/Releases/Detail/Configurations/Configurations.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretContainer.tsx
src/Pages/Shared/ConfigMapSecret/styles.scss
src/components/ApplicationGroup/Details/EnvironmentConfig/EnvConfig.tsx
src/css/base.scss

fix: remove calc from dt/cm/cs for comments view

fix: remove calc from dt/cm/cs for comments view

---

src/Pages/GlobalConfigurations/Authorization/APITokens/CreateAPIToken.tsx
src/Pages/GlobalConfigurations/Authorization/APITokens/EditAPIToken.tsx
src/Pages/GlobalConfigurations/Authorization/PermissionGroups/AddEdit/PermissionGroupForm.tsx
src/Pages/GlobalConfigurations/Authorization/Shared/components/AppPermissions/AppPermissions.component.tsx
src/Pages/GlobalConfigurations/Authorization/Shared/components/AppPermissions/RoleSelector.tsx
src/Pages/GlobalConfigurations/Authorization/Shared/components/AppPermissions/constants.ts
src/Pages/GlobalConfigurations/Authorization/Shared/components/AppPermissions/types.ts
src/Pages/GlobalConfigurations/Authorization/Shared/components/AppPermissions/utils.ts
src/Pages/GlobalConfigurations/Authorization/Shared/components/PermissionConfigurationForm/PermissionConfigurationFormProvider.tsx
src/Pages/GlobalConfigurations/Authorization/Shared/components/PermissionConfigurationForm/types.ts
src/Pages/GlobalConfigurations/Authorization/UserPermissions/AddEdit/UserForm.tsx
src/Pages/GlobalConfigurations/Authorization/utils.ts

feat: hide deployment approver

---

src/components/app/details/cIDetails/ciDetails.scss
src/components/app/details/triggerView/CiWebhookDebuggingModal.tsx
src/components/bulkEdits/bulkEdit.scss

refactor: improve layout and styling of CI webhook debugging modal and bulk edit components

---

src/components/ResourceBrowser/ResourceList/ResourceList.tsx

chore: key for useTabs in ResourceList.tsx

---

src/components/v2/appDetails/NodeTreeDetailTab.tsx
src/components/v2/appDetails/appDetails.scss
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/Terminal.tsx

fix: terminal fullscreen z-index

---

src/components/Jobs/JobList/JobsList.tsx
src/components/bulkEdits/BulkEdits.tsx
src/components/common/navigation/NavigationRoutes.tsx
src/components/security/Security.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/terminal.scss
src/components/v2/appDetails/sourceInfo/environmentStatus/environmentStatus.scss
src/components/v2/chartDeploymentHistory/ChartDeploymentHistory.component.tsx
src/components/v2/devtronStackManager/devtronStackManager.scss
src/components/v2/index.tsx
src/components/v2/values/ChartValues.component.tsx
src/css/base.scss
src/css/normalize.scss

feat: global calc cleanup

---

src/Pages/GlobalConfigurations/Authorization/Shared/components/AppPermissions/AppPermissions.component.tsx
src/Pages/GlobalConfigurations/Authorization/authorization.service.ts

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1827

fix: avoid calls for ea mode

---

src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentConfigCompare/DeploymentConfigCompare.tsx
src/components/ApplicationGroup/AppGroup.types.ts
src/components/ApplicationGroup/Details/EnvironmentOverview/EnvironmentOverview.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateModal.tsx
src/components/ApplicationGroup/Details/EnvironmentOverview/RestartWorkloadModal.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1827

fix: DeploymentConfigCompare - incorrect identifierId in case of manifest view fix

---

src/components/app/details/cIDetails/CIDetails.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
src/css/base.scss

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1827

fix: RC-31 UI Issues

---

src/components/cdPipeline/CDPipeline.tsx

fix: linked argo gitops check
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1827
Packet

fix: linked argo gitops check

---

package.json
yarn.lock

chore: bump common and sync with main

---

src/components/app/service.ts
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/EventsTable.tsx

Fixes https://github.com/devtron-labs/devtron/issues/6445

fix: Events timestamp should be in browser timezone and not indian

---

src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentTemplate/DeploymentTemplate.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretContainer.tsx
src/components/workflowEditor/service.ts
yarn.lock

fix: app template issues

---

package.json
src/Pages/Shared/SwitchThemeDialog/SwitchThemeDialog.component.tsx
vite.config.mts
yarn.lock

fix: update user preference payload

---

src/components/v2/appDetails/NodeTreeDetailTab.tsx

fix: app details dynamic tabs useStickyEvent querySelector

---

src/components/gitOps/GitOpsConfiguration.tsx
src/components/gitOps/UserGitRepConfiguration.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1957

fix: sticky footer for gitops and user gitops

---

src/components/CIPipelineN/CIPipeline.tsx
src/components/cdPipeline/BuildCD.tsx
src/components/cdPipeline/CDPipeline.tsx
src/components/cdPipeline/types.ts
src/components/workflowEditor/workflowEditor.tsx

fix: QA issues in application template

---

package.json
src/components/common/DynamicTabs/useTabs.ts
src/components/workflowEditor/nodes/CDNode.tsx
yarn.lock

chore: use fallbackTabIndex prop instead of FALLBACK_TAB const in useTabs

---

package.json
src/components/login/Login.tsx
src/components/login/LoginForm.tsx
src/components/login/login.scss
src/components/login/login.types.ts
yarn.lock

chore: login rerendering on login page

---

package.json
src/App.tsx
src/components/common/navigation/NavigationRoutes.tsx
yarn.lock

feat: show license data

---

src/components/ResourceBrowser/ResourceBrowser.scss

chore: refactor ResourceBrowser.scss to reorganize create-resource-container styles

---

src/Pages/GlobalConfigurations/Authorization/SSOLoginServices/SSOLogin.component.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1830

fix: sso login component footer

---

package.json
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretData.tsx
yarn.lock

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1830

fix: update ConfigMapSecretData to use CodeEditor.Container for improved layout

---

package.json
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretData.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
src/components/workflowEditor/Workflow.tsx
src/components/workflowEditor/workflowEditor.tsx
vite.config.mts
yarn.lock

chore: sync rc with main

---

src/components/common/navigation/Navigation.tsx
src/components/common/navigation/NavigationRoutes.tsx
src/components/v2/devtronStackManager/DevtronStackManager.service.tsx
src/components/v2/devtronStackManager/DevtronStackManager.tsx
src/components/v2/devtronStackManager/DevtronStackManager.utils.ts
src/css/base.scss
src/utils.tsx

feat: show stack manager for licensed enterprises

---

src/Pages/Shared/ConfigMapSecret/ConfigMapSecretContainer.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1830

fix: update class for ConfigMapSecretContainer to prevent width issues

---

package.json
src/Pages/GlobalConfigurations/Authorization/SSOLoginServices/SSOLogin.component.tsx
yarn.lock

feat: devtron license GA

---

src/components/v2/devtronStackManager/DevtronStackManager.component.tsx

feat: about devtron licensed

---

package.json
yarn.lock

chore: sync hotfix 31

---

package.json
src/components/v2/devtronStackManager/DevtronStackManager.component.tsx
src/config/constants.ts
src/utils.tsx
yarn.lock

feat: add support for upgrade version for enterprise

---

src/components/v2/devtronStackManager/AboutDevtronView.tsx
src/components/v2/devtronStackManager/DevtronStackManager.tsx

chore: update check of oss helm for stack manager

---

src/components/v2/devtronStackManager/AboutDevtronView.tsx
src/components/v2/devtronStackManager/DevtronStackManager.tsx

chore: sync stack manager version

---

package.json
src/stories/Button.stories.tsx
yarn.lock

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2043

feat: add support for anchor tag in Button component

---

src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/ConfigToolbar.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentTemplate/deploymentTemplateReducer.ts
src/Pages/Applications/DevtronApps/Details/AppConfigurations/Navigation/EnvConfigurationsNav.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/Navigation/Navigation.helper.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/Navigation/constants.ts
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretContainer.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretData.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretDeleteModal.tsx
src/Pages/Shared/ConfigMapSecret/constants.ts

refactor: approval policy exceptions UAT changes

---

package.json
src/components/app/details/cIDetails/ciDetails.scss
src/css/base.scss
yarn.lock

fix: css for artifacts in release and open check live status for deployment history empty state in new tab
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1775
Dev testing

fix: css for artifacts in release

---

package.json
src/components/app/details/cIDetails/ciDetails.scss
src/css/base.scss
yarn.lock

CSS Layout for release
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2046
Dev testing

fix: release css

---

package.json
src/components/common/navigation/NavigationRoutes.tsx
src/components/common/navigation/types.ts
src/components/v2/devtronStackManager/DevtronStackManager.component.tsx
src/utils.tsx
yarn.lock

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2047

fix: render null icon

---

src/components/ResourceBrowser/ResourceBrowser.service.tsx
src/components/ResourceBrowser/ResourceList/BaseResourceList.tsx

Show Add environment button against unmapped namespaces

feat: add environment column in namespace list

---

src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/CompareConfigView.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/ConfigToolbar.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentTemplate/DeploymentTemplate.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentTemplate/types.ts
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentTemplate/utils.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/NoPublishedVersionEmptyState.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/types.ts
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretContainer.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretData.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretForm.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretProtected.tsx
src/Pages/Shared/ConfigMapSecret/types.ts
src/Pages/Shared/ConfigMapSecret/utils.ts

refactor: UAT approval policy exceptions

---

src/components/AppSelector/AppSelector.tsx
src/components/AppSelector/constants.ts
src/components/app/details/main.tsx
src/components/ciPipeline/LinkedCIPipelineEdit.tsx

fix: recently visited app selector

---

package.json
src/components/v2/values/chartValuesDiff/ChartValuesEditor.tsx
yarn.lock

chore: ChartValuesEditor - loading position

---

package.json
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/ConfigToolbar.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentTemplate/DeploymentTemplate.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentTemplate/deploymentTemplateReducer.ts
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentTemplate/types.ts
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretContainer.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretData.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretForm.tsx
src/Pages/Shared/ConfigMapSecret/constants.ts
src/Pages/Shared/ConfigMapSecret/types.ts
yarn.lock

fix: approval policy exceptions

---

package.json
yarn.lock

chore: update vite to version 5.4.17

---

nginx.conf
package.json
vite.config.mts
yarn.lock

feat: enhance gzip configuration in nginx for improved performance resulting from initial network transfer from 16.8 MB to approx 5 MB
Dev testing

chore: enhance gzip configuration in nginx for improved performance

---

src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentTemplate/DeploymentTemplateForm.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretContainer.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretData.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretForm.tsx
src/Pages/Shared/ConfigMapSecret/types.ts
src/Pages/Shared/ConfigMapSecret/utils.ts

fix: ConfigMapSecret - hide patch option for external CM/CS

---

src/components/ResourceBrowser/ResourceList/ClusterUpgradeCompatibilityInfo.tsx

This PR includes fix for silver surfer layout
Currently the sidebar has become navbar
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2103
Dev tested

fix: layout for silver surfer

---

src/components/app/details/triggerView/config.ts
src/components/app/details/triggerView/workflow.service.ts
src/components/app/details/triggerView/workflow/Workflow.tsx
src/components/workflowEditor/nodes/WebhookNode.tsx
src/components/workflowEditor/types.ts

feat: TriggerView - Webhook Node - add image button UI

---

src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/app/details/triggerView/TriggerView.tsx
src/components/app/details/triggerView/types.ts
src/components/app/details/triggerView/workflow/Workflow.tsx
src/components/workflowEditor/nodes/WebhookNode.tsx
src/components/workflowEditor/types.ts

feat: TriggerView, EnvTriggerView - integrate webhook add image modal

---

package.json
src/components/app/details/triggerView/cdMaterial.tsx
yarn.lock

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2121

fix: Conditional rendering of generic commit info header

---

src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/app/details/triggerView/TriggerView.tsx
src/components/app/details/triggerView/TriggerView.utils.tsx
src/components/app/details/triggerView/workflow/Workflow.tsx
src/components/workflowEditor/nodes/WebhookNode.tsx
src/components/workflowEditor/types.ts

fix: webhook external image

---

src/components/dockerRegistry/Docker.tsx
src/config/constants.ts

feat: rename credentialType key to registryCredentialsType

---

package.json
src/App.tsx
src/Pages/License/ActivateLicense.tsx
src/Pages/License/service.tsx
src/components/globalConfigurations/GlobalConfiguration.tsx
yarn.lock

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2122

feat: add activate license page in dashboard

---

package.json
src/App.tsx
src/Pages/License/ActivateLicense.tsx
src/Pages/License/service.tsx
src/components/ResourceBrowser/ResourceList/ClusterUpgradeCompatibilityInfo.tsx
src/components/cdPipeline/CDPipeline.tsx
src/components/globalConfigurations/GlobalConfiguration.tsx
src/css/themeUtils.scss
yarn.lock

chore: sync activate license

---

package.json
yarn.lock

Empty state svg CSS removed
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2149

chore: Empty state svg CSS removed

---

src/css/base.scss

feat: add new height utility class for 2px

feat: add new height utility class for 2px

---

src/components/ClusterNodes/ClusterList/ClusterSelectionBody.tsx
src/components/ClusterNodes/ClusterList/types.ts
src/components/ResourceBrowser/ResourceBrowser.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2165

fix: bulk selection action widget position in KubeConfig Bulk selection

---

src/Pages/GlobalConfigurations/Authorization/APITokens/APITokenList.tsx
src/Pages/GlobalConfigurations/Authorization/Authorization.component.tsx
src/Pages/GlobalConfigurations/Authorization/AuthorizationProvider.tsx
src/Pages/GlobalConfigurations/Authorization/PermissionGroups/List/PermissionGroupListHeader.tsx
src/Pages/GlobalConfigurations/Authorization/UserAndGroupPermissions.tsx
src/Pages/GlobalConfigurations/Authorization/UserPermissions/List/UserPermissionContainer.tsx
src/Pages/GlobalConfigurations/Authorization/UserPermissions/List/UserPermissionListHeader.tsx
src/Pages/GlobalConfigurations/Authorization/types.ts
src/components/dockerRegistry/Docker.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2003

fix: user permission bulk selection action widget placement

---

src/Pages/GlobalConfigurations/Authorization/Shared/components/AppPermissions/AppPermissions.component.tsx
src/components/ApplicationGroup/AppGroupDetailsRoute.tsx
src/components/ApplicationGroup/CreateAppGroup.tsx
src/components/CIPipelineN/CIPipeline.tsx
src/components/ClusterNodes/NodeDetails.tsx
src/components/Jobs/JobDetails/JobDetails.tsx
src/components/app/details/AppHeader.tsx
src/components/app/details/cIDetails/CIDetails.tsx
src/components/app/list-new/AppList.tsx
src/components/cdPipeline/CDPipeline.tsx
src/components/ciPipeline/Webhook/WebhookDetailsModal.tsx
src/components/notifications/Notifications.tsx
src/components/security/Security.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/EphemeralContainerDrawer.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx
src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx
src/components/v2/appDetails/k8Resource/nodeType/PodHeader.component.tsx
src/components/v2/appDetails/sourceInfo/scaleWorkloads/ScaleWorkloadsModal.component.tsx
src/components/v2/chartDeploymentHistory/ChartDeploymentHistory.component.tsx
src/components/v2/devtronStackManager/AboutDevtronView.tsx
src/components/v2/headers/AppHeader.component.tsx
src/components/v2/headers/ChartHeader.component.tsx
src/components/v2/headers/EAHeader.component.tsx

feat: remove prop for align active border in tab group

---

src/components/common/helpers/Helpers.tsx
src/components/v2/appDetails/k8Resource/k8resources.scss

chore: return false for ai button if flag is false

---

nginx-default.conf

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2189

feat: Added support for ipv6 clusters

---

package.json
src/components/ApplicationGroup/AppGroup.types.ts
src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx
src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/ApplicationGroup/Details/TriggerView/TriggerModalTableRow.tsx
src/components/ApplicationGroup/Details/TriggerView/TriggerResponseModal.tsx
src/components/app/details/appDetails/SourceInfo.tsx
src/components/v2/appDetails/sourceInfo/environmentStatus/EnvironmentStatus.component.tsx
src/components/v2/chartDeploymentHistory/ChartDeploymentHistory.component.tsx
src/components/v2/chartDeploymentHistory/chartDeploymentHistory.service.ts
src/components/v2/index.tsx
yarn.lock

fix: derive isolated env chart download file name from BE and fix runner query payload for that.

fix: derive isolated env chart download file name from BE and fix runner query payload for that.

---

src/App.tsx
src/components/common/Banner/utils.tsx
src/components/common/hooks/useVersionUpdate/types.ts
src/components/common/hooks/useVersionUpdate/useVersionUpdateReload.tsx
src/components/common/navigation/NavigationRoutes.tsx
src/components/common/navigation/types.ts

TESTING: toastEligibleRoutes added for toast rendering

---

src/Pages/GlobalConfigurations/Authorization/APITokens/CreateAPIToken.tsx
src/Pages/GlobalConfigurations/Authorization/APITokens/EditAPIToken.tsx
src/Pages/GlobalConfigurations/Authorization/PermissionGroups/AddEdit/PermissionGroupForm.tsx
src/Pages/GlobalConfigurations/Authorization/UserPermissions/AddEdit/UserForm.tsx

Before:
After:
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1829
QA

fix: padding classes across API token, user and permission group forms

---

src/components/login/Login.tsx
src/components/login/constants.ts
src/components/login/login.scss

feat: add animation in login and sso variants

---

src/components/cdPipeline/CDPipeline.tsx

fix: cd pipeline strategy auto select

chore: cd pipeline strategy auto select

---

src/components/ApplicationGroup/AppGroup.utils.ts

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2271

chore: cd node in progress redirecting to app details

---

src/components/ClusterNodes/ClusterOverview.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2250

fix: super admin check for cluster config

---

.eslintignore
src/Pages/Shared/EnvironmentOverviewTable/EnvironmentOverview.constants.ts
src/Pages/Shared/EnvironmentOverviewTable/EnvironmentOverviewBulkSelectionActionWidget.tsx
src/Pages/Shared/EnvironmentOverviewTable/EnvironmentOverviewPopupMenu.tsx
src/Pages/Shared/EnvironmentOverviewTable/EnvironmentOverviewTable.component.tsx
src/Pages/Shared/EnvironmentOverviewTable/EnvironmentOverviewTable.types.ts
src/Pages/Shared/EnvironmentOverviewTable/index.ts
src/assets/icons/ic-checkbox-selected-error.svg
src/components/ApplicationGroup/AppGroup.utils.ts
src/components/ApplicationGroup/Details/EnvironmentOverview/EnvironmentOverview.tsx
src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx
src/components/ApplicationGroup/Details/TriggerView/utils.ts
src/components/app/details/appDetails/AppDetailsCDButton.tsx
src/css/forms.scss

feat: EnvironmentOverview - integrate ManageTraffic, BulkSelectionActionWidget

---

package.json
src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
yarn.lock

handle missing, suspended and unknown deployment status in helm apps deployed via gitops
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2299
Dev tested

fix: handle missing, suspended and unknown deployment status in helm apps deployed via gitops

---

.eslintignore
src/components/ApplicationGroup/AppGroup.types.ts
src/components/ApplicationGroup/AppGroupAppFilter.tsx
src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx
src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/ApplicationGroup/Details/TriggerView/utils.ts
src/css/colorPalette.scss
src/css/themeUtils.scss

feat: add util for getting workflows which can be triggered

---

src/Pages/GlobalConfigurations/ClustersAndEnvironments/CreateCluster/Sidebar.tsx
src/Pages/GlobalConfigurations/ClustersAndEnvironments/CreateCluster/constants.tsx
src/Pages/GlobalConfigurations/ClustersAndEnvironments/CreateCluster/types.ts
src/components/v2/values/chartValuesDiff/ChartValuesView.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2301

feat: hide virtual cluster in EA Mode

---

src/components/v2/devtronStackManager/DevtronStackManager.component.tsx
src/components/v2/devtronStackManager/DevtronStackManager.service.tsx
src/components/v2/devtronStackManager/DevtronStackManager.tsx
src/components/v2/devtronStackManager/DevtronStackManager.utils.ts
src/components/v2/devtronStackManager/devtronStackManager.component.scss

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2176

feat: add current version in release notes api

---

src/components/common/navigation/NavigationRoutes.tsx

chore: NavigationRoutes - update className for conditional margin

---

.eslintignore
package.json
src/Pages/Applications/DevtronApps/Details/AppConfigurations/Navigation/EnvironmentOverrideRouter.tsx
src/Pages/GlobalConfigurations/Authorization/Shared/components/BulkSelection/BulkSelectionClearConfirmationModal.tsx
src/Pages/GlobalConfigurations/Authorization/UserPermissions/List/UserPermissionContainer.tsx
src/components/charts/discoverChartDetail/ChartDeploymentList.tsx
src/components/gitOps/UpdateConfirmationDialog.tsx
src/components/v2/chartDeploymentHistory/chartDeploymentHistory.scss
src/components/v2/devtronStackManager/DevtronStackManager.component.tsx
src/components/v2/devtronStackManager/SuccessModalComponent.tsx
src/components/v2/devtronStackManager/devtronStackManager.component.scss
src/components/v2/devtronStackManager/devtronStackManager.scss
src/components/workflowEditor/NoGitOpsRepoConfiguredWarning.tsx
src/components/workflowEditor/Workflow.tsx
src/components/workflowEditor/nodes/CDNode.tsx
src/components/workflowEditor/types.ts
yarn.lock

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2352

feat: remove confirmation dialog and replace with modal

---

src/components/common/navigation/NavigationRoutes.tsx
src/index.tsx

chore: move confirmation modal provider inside main context provider

---

src/components/common/SidePanel/SidePanelDocumentation.tsx

chore: add check to conditionally show side panel documentation open in new tab button

---

src/Pages/GlobalConfigurations/ClustersAndEnvironments/ClusterForm.tsx
src/components/charts/list/DiscoverCharts.tsx

chore: edit flag added  while saving cluster via token

---

src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/app/details/appDetails/AppDetails.tsx
src/components/app/details/appDetails/AppDetailsCDModal.tsx
src/components/app/details/appDetails/SourceInfo.tsx
src/components/app/details/triggerView/cdMaterial.tsx
src/components/app/types.ts

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2272

fix: multiple instance of cd modal on app details

---

package.json
src/components/common/Banner/Banner.tsx
yarn.lock

chore: Banner distorts on side panel tab switch

---

package.json
src/components/CIPipelineN/VariableDataTable/validations.ts
yarn.lock

fix: app details manifest scroll on resolution change
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2417
Dev tested

fix: app details manifest scroll on resolution change

---

Dockerfile
nginx.conf
vite.config.mts

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2416

fix: revert brotli compression

---

src/components/common/navigation/NavigationRoutes.tsx
src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx
src/components/workflowEditor/workflowEditor.scss
src/components/workflowEditor/workflowEditor.tsx

chore: enhance navbar animation and workflow editor empty states

---

Dockerfile
src/components/common/navigation/NavigationRoutes.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2416

fix: dockerfile 2nd stages fixes 

---

package.json
src/Pages/App/CreateAppModal/ProjectSelector.tsx
yarn.lock

chore: remove defaultMenuIsOpen from ProjectSelector component

---

package.json
src/components/ClusterNodes/NodeDetails.tsx
src/components/ClusterNodes/types.ts
src/components/ResourceBrowser/ResourceList/K8SResourceList.tsx
src/components/ResourceBrowser/ResourceList/NodeDetailWrapper.tsx
src/components/ResourceBrowser/ResourceList/ResourceList.tsx
yarn.lock

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2035

fix: node detail url in RB

---

package.json
yarn.lock

fix: update @devtron-labs/devtron-fe-common-lib to version 1.17.0

fix: update @devtron-labs/devtron-fe-common-lib to version 1.17.0

---

src/components/v2/values/chartValuesDiff/ChartValuesView.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2453

fix: deploy button not visible in gui view

---

src/components/common/SidePanel/SidePanelContent.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2454

fix: ask devtron empty state in oss

---

src/components/ResourceBrowser/ResourceList/K8SResourceList.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2474

fix: k8s list error state when filters are applied

---

src/components/ClusterNodes/ClusterTerminal.tsx
src/components/ClusterNodes/types.ts
src/components/ResourceBrowser/PageHeader.buttons.tsx
src/components/ResourceBrowser/ResourceList/AdminTerminal.tsx
src/components/ResourceBrowser/ResourceList/CreateResource.tsx
src/components/ResourceBrowser/ResourceList/K8sResourceListTableCellComponent.tsx
src/components/ResourceBrowser/ResourceList/NodeActionsMenu.tsx
src/components/ResourceBrowser/ResourceList/ResourceList.tsx
src/components/ResourceBrowser/ResourceList/constants.ts
src/components/ResourceBrowser/ResourceList/types.ts
src/components/ResourceBrowser/Types.ts

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2484

fix: show node error in list & use tabs reinit

---

src/Pages/GlobalConfigurations/Authorization/Shared/components/AppPermissions/AppOrJobSelector.tsx
src/Pages/GlobalConfigurations/Authorization/Shared/components/AppPermissions/AppPermissions.component.tsx
src/Pages/GlobalConfigurations/Authorization/authorization.service.ts
src/Pages/GlobalConfigurations/Authorization/types.ts
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretContainer.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2498

fix: CM/Secret Incorrect Error State, Permissions - job workflows api endpoint

---

package.json
src/Pages/GlobalConfigurations/ClustersAndEnvironments/EnvironmentList.tsx
src/Pages/GlobalConfigurations/ClustersAndEnvironments/cluster.util.tsx
src/components/ApplicationGroup/Details/TriggerView/BulkCITrigger.tsx
yarn.lock

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2425

feat: show namespace count for virtual clusters

---

src/Pages/ChartStore/ChartDetails/ChartDetailsAbout.tsx

chore: adjust image container for better layout in ChartDetailsAbout

---

package.json
src/Pages/GlobalConfigurations/ClustersAndEnvironments/ClusterList.components.tsx
src/Pages/GlobalConfigurations/ClustersAndEnvironments/ClusterList.tsx
src/Pages/GlobalConfigurations/ClustersAndEnvironments/EnvironmentList.tsx
src/components/common/ExportToCsv/ExportToCsv.tsx
src/components/login/LoginForm.tsx
yarn.lock

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2517

chore: focus trap and misc fixes

---

src/components/ApplicationGroup/AppGroup.utils.ts

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2517

fix: pick status for linked ci similar to ci node

---

index.css
src/components/ResourceBrowser/ResourceList/ResourceFilterOptions.tsx
src/css/base.scss
src/css/formulae.scss

chore: add IBM Plex font

---

src/components/app/details/appDetails/IssuesCard.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2537

fix: issues modal not opening on click

---

src/css/base.scss

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2536

revert: dc__truncate

---

src/components/app/details/appDetails/DeployedCommitCard.tsx
src/components/v2/appDetails/sourceInfo/environment.type.ts
src/components/v2/appDetails/sourceInfo/environmentStatus/EnvironmentStatus.component.tsx
src/components/v2/appDetails/sourceInfo/environmentStatus/NotesDrawer.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2555

fix: notes drawer closing on click

---

package.json
src/Pages/App/Configurations/WorkflowEditor/CreateCICDPipeline/CIStepperContent.tsx
src/Pages/App/Configurations/WorkflowEditor/SourceMaterialsSelector/SourceMaterialsSelector.tsx
src/Pages/App/Configurations/WorkflowEditor/SourceMaterialsSelector/types.ts
src/Pages/GlobalConfigurations/ClustersAndEnvironments/ClusterList.tsx
src/Pages/License/ActivateLicense.tsx
src/Pages/Shared/UpgradeToEnterprise/UpgradeToEnterpriseDialog.tsx
src/Pages/Shared/UpgradeToEnterprise/index.ts
src/components/CIPipelineN/Build.tsx
src/components/ClusterNodes/ClusterList/ClusterSelectionBody.tsx
src/components/ResourceBrowser/PageHeader.buttons.tsx
src/components/ResourceBrowser/ResourceBrowser.tsx
src/components/app/details/appDetails/DeployedCommitCard.tsx
src/components/ciPipeline/SourceMaterials.tsx
src/components/ciPipeline/ciPipeline.service.ts
src/components/gitProvider/GitProvider.tsx
src/components/material/MaterialView.tsx
src/components/v2/appDetails/sourceInfo/environment.type.ts
src/components/v2/appDetails/sourceInfo/environmentStatus/EnvironmentStatus.component.tsx
src/components/v2/appDetails/sourceInfo/environmentStatus/NotesDrawer.tsx
src/components/workflowEditor/Workflow.tsx
src/components/workflowEditor/nodes/CINode.tsx
src/components/workflowEditor/nodes/StaticNode.tsx
src/components/workflowEditor/nodes/types.ts
src/components/workflowEditor/types.ts
src/css/icons.scss
yarn.lock

chore: sync develop kubecon 22 aug

---

package.json
yarn.lock

chore: update devtron-fe-common-lib to version 1.19.4-pre-3

---

package.json
yarn.lock

chore: ai chat app fullscreen support

---

src/components/CIPipelineN/VariableDataTable/ValueConfigOverlay.tsx
src/components/workflowEditor/workflowEditor.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2560

fix: input variable popover opening on screen corner

---

src/components/app/details/triggerView/PipelineConfigDiff/usePipelineDeploymentConfig.ts

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2566

fix: update secretsData handling for pipeline deployment configurations

---

package.json
yarn.lock

chore: breakdown list version bump.

chore: breakdown list version bump

---

src/Pages/Shared/CommandBar/CommandBarBackdrop.tsx
src/Pages/Shared/CommandBar/constants.ts
src/Pages/Shared/CommandBar/types.ts
src/Pages/Shared/CommandBar/utils.ts

This pull request enhances the `CommandBar` component by improving search functionality, updating UI styles, and expanding the data model for navigation items. The most significant changes are grouped below.
**Feature Enhancements:**
* The command bar search now matches not only item titles but also keywords associated with each item, making search results more comprehensive and relevant.
* The `CommandBarItemType` now includes a required `keywords` field, and all navigation items and app list items are updated to include this property (currently as empty arrays where not used). [[1]](diffhunk://#diff-16f680eda8c54268898fd9021206b14cd67e132841fdbdd76ae5076772f76bd1L16-R18) [[2]](diffhunk://#diff-54cab7d2bf82ac4f96140c41cc09de3b1392aaa4065b0db10a03d3954974dca3R37) …

chore: enhance CommandBarBackdrop with keyword search and icon mapping

---

package.json
src/Pages/GlobalConfigurations/Authorization/SSOLoginServices/SSOLogin.component.tsx
src/Pages/GlobalConfigurations/Authorization/SSOLoginServices/constants.ts
yarn.lock

oidc auto assign support added.
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2572

feat: oidc auto assign support added

---

package.json
src/App.tsx
src/components/common/ClusterNotReachableDialog/ClusterNotReachableDialog.tsx
src/components/common/ClusterNotReachableDialog/ClusterNotReachableDialog.type.ts
src/components/externalArgoApps/ExternalArgoAppDetail.tsx
src/components/v2/appDetails/ea/EAAppDetail.component.tsx
src/components/v2/appDetails/sourceInfo/EnvironmentSelector.component.tsx
src/components/v2/index.tsx
yarn.lock

chore: main pull

---

src/components/Navigation/Navigation.tsx
src/components/Navigation/constants.ts

chore: coming soon nav

---

src/components/app/details/appDetails/DeployedCommitCard.tsx
src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx

fix: handle potential null value in materials check and improve node health status check
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2616

fix: handle potential null value in materials check and improve node health status check
