devtron-labs/dashboard

src/components/app/details/cIDetails/CIDetails.tsx
src/components/app/details/cdDetails/CDDetails.tsx
src/components/app/service.ts
src/components/common/RepoBranch.tsx
src/config/constants.tsx

Following timestamp fixed: 
- CI Material list -> commit time
- CD Material list -> deployed time, commit time
- Deployment History -> start time, finished time, commit time
- Trigger History -> start time, finished time, commit time
Local and 12 hour format

time format

---

src/components/login/SSOLogin.tsx
src/components/login/login.css
src/components/login/ssoConfig.types.tsx

closes devtron-labs/devtron#262

Added URL text field in SSO Config

---

src/components/app/list/appList.modal.ts
src/services/service.ts

closes devtron-labs/devtron#261

docker registry new api

---

src/components/charts/ChartGroupDetails.tsx
src/components/charts/discoverChartDetail/DiscoverChartDetails.tsx
src/components/charts/list/DiscoverCharts.tsx
src/components/gitOps/GitOpsConfiguration.tsx
src/components/gitOps/gitops.service.tsx
src/components/workflowEditor/workflowEditor.tsx
src/config/constants.tsx
src/services/service.ts

Added isGitopsConfigured api on following:
- Chart Group Detail
- Charts Detail
- Discover Chart List
- Workflow Editor

integrate of gitops configured api

---

src/components/app/details/appDetails/AppMetrics.tsx

app metrics empty state condition fix

---

src/components/EmptyState/emptyState.scss
src/components/app/list/AppListContainer.tsx
src/components/app/list/AppListView.tsx
src/components/app/list/emptyView/Empty.tsx
src/config/constants.tsx

closes devtron-labs/devtron#289

Fix empty state conditions on app list

---

src/components/login/SSOLogin.tsx

close https://github.com/devtron-labs/devtron/issues/312

config is added in configuration tab

---

src/components/dockerRegistry/Docker.tsx

close https://github.com/devtron-labs/devtron/issues/310

Docker tooltip

---

src/components/common/formFields/CustomInput.tsx
src/components/gitOps/GitOpsConfiguration.tsx
src/components/gitOps/gitops.type.ts
src/components/globalConfigurations/GlobalConfiguration.tsx
src/components/globalConfigurations/globalConfigurations.scss
src/components/login/login.css

- Form Validation added in gitops Config
- Form fields updated with error CSS
closes https://github.com/devtron-labs/devtron/issues/305

gitops config improvements

---

src/components/checkList/AllChartsCheck.tsx
src/components/checkList/AllCheckModal.tsx
src/components/checkList/AppCheckList.tsx
src/components/checkList/AppCheckModal.tsx
src/components/checkList/ChartCheckList.tsx
src/components/checkList/ChartCheckModal.tsx
src/components/checkList/GlobalAllCheckModal.tsx
src/components/checkList/GlobalChartCheck.tsx
src/components/checkList/GlobalConfigCheckList.tsx

Order of items in app check list made consistent with global configuration
CSS font size fixed to 13px

order of items made consitent with global config | added fs

---

src/components/chartRepo/ChartRepo.tsx

Global config > Chart Repository;
Incorrect message on disable/enable chart repo toggle
https://github.com/devtron-labs/devtron/issues/291

Tooltip Message fixed on Enable/Disable Chart Repo

---

src/components/gitProvider/GitProvider.tsx

Global config > Git Account;
Incorrect message on disable/enable git account toggle
https://github.com/devtron-labs/devtron/issues/294
- [x ] Bug fix (non-breaking change which fixes an issue)
-[x] Enable Chart Repository
-[x] Disable Chart Repository

Tooltip Message fixed on Enable/Disable Git accounts

---

src/components/ciPipeline/CIPipeline.tsx
src/components/ciPipeline/CIPipelineAdvanced.tsx
src/css/forms.scss

docker build args fix

---

src/components/ciPipeline/CIPipelineAdvanced.tsx
src/components/ciPipeline/ciPipeline.service.ts

pre/post-ci Expand CTA fix

---

src/components/EnvironmentOverride/ConfigMapOverrides.tsx
src/components/EnvironmentOverride/SecretOverrides.tsx
src/components/command/Command.tsx
src/components/command/command.util.ts
src/components/common/navigation/Navigation.tsx
src/components/common/pagination/Pagination.tsx

Command bar: API Call in background fixed, discover charts suggestion fix
Environment Override on environment change continues to stay in loading state until refreshed.

api call in commandbar | env override loading state fix

---

src/components/EnvironmentOverride/DeploymentTemplateOverride.tsx
src/components/common/helpers/compareVersion.ts
src/components/deploymentConfig/DeploymentConfig.tsx

Chart Version comparison fixed on deployment template and deployment template override.
Minimum supported remains the same, 3.7.0
Deployment Template Tested with following Chart Versions

Fixed chart version comparison on Deployment Template and Deployment Template Override

---

Dockerfile

Latest node version: 16 is incompatible with dependency node-sass version: 4
Node version has been fixed to version 14 for now.
Docker Image has been created successfully using updated Dockerfile. 
Dashboard has been deployed and tested on the cluster

[INTERNAL] dockerfile update with node version 14

---

src/components/app/details/appDetails/AppMetrics.tsx
src/components/app/details/appDetails/utils.tsx

Fixes # (https://github.com/devtron-labs/devtron/issues/440)
Test Iframe src url for the following graphs:

440. Fixed App metrics Status and throughput graph

---

src/components/app/details/metrics/DeploymentMetrics.tsx
src/components/security/SecurityScansTab.tsx
src/components/security/security.css

- Security scan list bg fix
- Icon color fix
- Security scan list background

[BUG FIX] Security scan list background color fixed

---

src/components/deploymentConfig/DeploymentConfig.tsx

Change of Chart version did not change deployment template config in code editor. 
Fixes # (devtron-labs/devtron#448)
Following actions have been tested on deployment template:

[BUG FIX] Issue#448. deployment template valuesoverride

---

src/components/material/MaterialList.tsx
src/components/material/MaterialView.tsx

Fixes (https://github.com/devtron-labs/devtron/issues/449)

[GIT REPO URL] Remove .git validation from git repo url

---

src/components/userGroups/UserGroup.tsx

Earlier the User was unable to search case sensitive stit was the case sensitive.
Recently there is no case sensitivity in the search bar now
fixes https://github.com/devtron-labs/devtron/issues/477
**Expected behaviour**

[FIX] User access search

---

src/components/app/create/CreateApp.tsx
src/components/cluster/Cluster.tsx
src/css/base.scss

UI/UX bugs including:
1. `App Name*` helper text icon postition
2. Add cluster > Card title shows 'Edit cluster'
3.  Error icon needs to be replaced 
Fixes: https://github.com/devtron-labs/devtron/issues/279

[FIX] UI UX bugs

---

src/components/app/details/appDetails/AppMetrics.tsx
src/components/cluster/Cluster.tsx

Fixes # (https://github.com/devtron-labs/devtron/issues/488);
Fixes # (https://github.com/devtron-labs/devtron/issues/422);

[FIX] k8sVersion parse warning toast | server url validation added on cluster 

---

src/components/app/details/appDetails/AppMetrics.tsx

fixes loading issue in Àpplication metrices`
Fixes https://github.com/devtron-labs/dashboard/issues/134

[FIX] app metrices loading bug

---

src/components/app/create/validationRules.ts
src/config/constants.ts
src/css/forms.scss
src/setupProxy.js

Appropriate messaging below `App Name*` input while creating an app
Fixes https://github.com/devtron-labs/devtron/issues/496

[CREATE APP] Create app input error

---

src/App.tsx
src/components/app/details/appDetails/appDetails.service.ts
src/index.tsx
src/services/fetchWithFullRoute.ts
src/services/service.ts

Fetch posthog api key from telemetry api and remove it from env variable.

feat: Get Posthog api key from api

---

src/components/charts/ChartGroupAdvanceDeploy.tsx

Error icon size fix in chart group advanced deploy.

feat: error icon size

---

src/components/charts/modal/CreateChartGroup.tsx
src/css/forms.scss

Appropriate validation messaging on `Name*` input :
Fixes https://github.com/devtron-labs/dashboard/issues/144

[CHART GROUP ]Validate chartgroup

---

src/components/cluster/Cluster.tsx
src/components/common/helpers/Helpers.tsx
src/components/globalConfigurations/GlobalConfiguration.tsx

issue #276 fixed (validation for cluster name, environment name, namespace)

---

src/components/cluster/Cluster.tsx

bug fix (_ replaced with - in regex)

---

src/components/common/helpers/Helpers.tsx

; was missing

---

src/components/common/helpers/Helpers.tsx

bug fixed # empty array

---

src/components/cluster/Cluster.tsx
src/components/common/helpers/Helpers.tsx

issue#276 validation message bug fixes

---

src/components/cluster/Cluster.tsx

569 validation message

---

src/components/cluster/Cluster.tsx

fix: token non mandatory for default cluster and some validations fixes

---

src/components/cluster/Cluster.tsx

baerer token required fix for non default cluster

---

src/components/bulkEdits/BulkEdits.tsx
src/components/bulkEdits/bulkEdit.css
src/components/bulkEdits/bulkEdits.type.tsx
src/setupProxy.js

Bulk Update support for ConfigMaps & Secrets.
-User can Bulk Update ConfigMaps & Secrets instead of only Deployment Template. Along with updating multiple apps, this feature will also support updating multiple ConfigMaps & Secrets within apps.

Bulk update support for configmaps & secrets

---

src/components/cluster/Cluster.tsx

Fixes:  devtron-labs/devtron#646

issue#646 fixed - disallowing dot from environment name

---

src/components/chartRepo/ChartRepo.tsx
src/components/chartRepo/chartRepo.service.tsx
src/components/common/ValidateForm/ValidateForm.tsx
src/components/common/ValidateForm/validateForm.css
src/components/gitOps/GitOpsConfiguration.tsx
src/components/gitOps/gitops.css
src/components/gitProvider/GitProvider.tsx
src/components/globalConfigurations/globalConfigurations.scss
src/config/constants.ts
src/css/base.scss
src/setupProxy.js

Chart repo validate modal added  in `Global Configuration`> `Chart Repository`
Fixes https://github.com/devtron-labs/devtron/pull/709

FEATURE: To add validation on Helm Chart repo

---

src/components/app/ResourceTreeNodes.tsx
src/components/app/details/appDetails/AppDetails.tsx
src/components/app/details/appDetails/__test__/GenericInfo.test.tsx
src/setupProxy.js

When a user having admin access attempts to delete resources from devtron UI and gets unauthorised message.
Resource delete request posting invalid app id from chart/app detail page.
Fixes # (issue) : https://github.com/devtron-labs/devtron/issues/698

FIX: resource delete request posting invalid app id from chart/app detail page.

---

src/components/security/SecurityScansTab.tsx

Pagination on the Security scans page ( /dashboard/security/scans ) does not work.
Fixes: https://github.com/devtron-labs/devtron/issues/751

FIX: pagination and offset bug fixed in scrity scan

---

src/components/chartRepo/ChartRepo.tsx
src/components/common/ValidateForm/ValidateForm.tsx
src/components/gitOps/GitOpsConfiguration.tsx
src/components/gitOps/gitops.type.ts

Required gitops refactoring
Fixes: https://github.com/devtron-labs/devtron/issues/733

GitOps Code refactoring

---

src/components/chartRepo/ChartRepo.tsx
src/components/common/MultiSelect/MultiSelectCustomisations.tsx
src/components/gitProvider/GitProvider.tsx
src/components/gitProvider/gitProvider.css
src/components/globalConfigurations/globalConfigurations.scss
src/components/material/CreateMaterial.tsx
src/components/material/MaterialList.tsx
src/components/material/MaterialView.tsx
src/components/material/UpdateMaterial.tsx
src/components/material/material.types.ts
src/css/base.scss
src/css/forms.scss
src/setupProxy.js

Fixes: https://github.com/devtron-labs/devtron/issues/568

Git submodule

---

src/components/app/details/cIDetails/CIDetails.tsx
src/components/app/details/cIDetails/types.tsx
src/components/app/details/triggerView/cdMaterial.tsx

On changing the branch and git material, history of CI/CD used to be get updated with the changes. Changed the responses and code structure for showing correct data.

Fixed ci/cd history bug

---

src/components/gitProvider/GitProvider.tsx

bug #883 fixed (static message for github git account to use token instead of password)

---

public/index.html
src/components/common/navigation/Navigation.tsx

discord live chat integration

---

src/components/chartRepo/ChartRepo.tsx
src/components/chartRepo/chartRepo.scss
src/components/chartRepo/chartRepo.service.tsx
src/config/constants.ts
src/css/base.scss

Added functionality  to refetch charts from the chart repos
Fixes # devtron-labs/devtron#935
This is tested by triggering functionality from the UI

feat: added refetch functionality for chart repo

---

src/components/EnvironmentOverride/DeploymentTemplateOverride.tsx
src/components/app/details/appConfig/AppConfig.tsx
src/components/deploymentConfig/DeploymentConfig.tsx
src/components/deploymentConfig/deploymentConfig.scss
src/css/base.scss
src/index.tsx

Devtron should be able to provide multiple chart types for applications. Currently only Rollout type charts are supported by at times users need other types for eg Job type or knative type. This release will allow different chart  types to be added to the repository of Devtron
Fixes # devtron-labs/devtron#949
Tested by creating new applications and adding environment overrides.

feat: Multi chart

---

src/components/cluster/cluster.service.ts

complementary to https://github.com/devtron-labs/devtron/pull/951

external app cluster component url correction

---

src/components/app/details/appDetails/AppMetrics.tsx
src/components/app/details/appDetails/GraphsModal.tsx
src/components/app/details/appDetails/utils.tsx

User should be able to select or provide latency percentile for the latency charts of App metrics.
Also in full screen view latency chart is not visible.
Fixes # devtron-labs/devtron#991
This has been selected via UI by changing values from dropdown

feat: new latency chart and fixed issue with full modal chart

---

package.json
src/App.tsx
src/components/common/navigation/Navigation.tsx
src/services/service.ts
yarn.lock

Remove telemetry call from the webclient.
Fixes: devtron-labs/devtron#1016
This has been tested by running the code

feat: removed telemetry from webclient

---

src/components/cluster/Cluster.tsx

Ea module configuration

---

src/components/app/details/triggerView/workflow.service.ts

Workflow created without CI node resulted in error on workflow page
Fixes # Not created

bug: error in workflow edit page workflow was created without and ci node

---

src/components/userGroups/UserGroup.scss
src/components/userGroups/UserGroup.tsx
src/config/constants.ts

UX feedback

---

src/components/userGroups/UserGroup.scss

minor ui fix

---

src/services/service.ts

BE review chanegs

---

src/assets/icons/ic-info-filled.svg
src/components/EmptyState/emptyState.scss
src/components/app/list-new/AppList.tsx
src/components/app/list-new/HelmAppList.css
src/components/app/list-new/HelmAppList.tsx
src/components/app/list/emptyView/Empty.tsx
src/components/app/list/list.css
src/components/common/filter/filter.css
src/css/base.scss

External app support final css

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/LogViewer.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx

This is to fix logs related issue in the new ui

External helm app debugging logs fixes

---

src/components/app/grepSSEworker.ts
src/components/v2/appDetails/appDetails.api.ts
src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.api.ts
src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx
src/components/v2/appDetails/k8Resource/nodeType/NodeDelete.component.tsx
src/config/constants.ts

Ea logs integration

---

src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.api.ts

BE review changes

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx

formating + loading fix

---

src/assets/icons/appstatus/missing.svg
src/assets/icons/appstatus/unknown.svg
src/components/terminal/TerminalWrapper.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/Terminal.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/terminal.css

1. (109) Icons for "Unknown" and "Missing" status are getting cropped
2. (110) Text in terminal is sticking to the main nav. Pls refer screenshot
3. (111) "Connected" status should  be at bottom-left corner

External icon css

---

src/components/v2/appDetails/appDetails.api.ts
src/components/v2/appDetails/ea/EAAppDetail.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.api.ts
src/components/v2/appDetails/k8Resource/nodeType/NodeDelete.component.tsx
src/components/v2/appDetails/sourceInfo/environmentStatus/EnvironmentStatus.component.tsx

EA app detail polling

---

src/components/v2/appDetails/AppDetails.component.tsx
src/components/v2/appDetails/k8Resource/K8Resource.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx
src/components/v2/values/DeployChart.tsx

1. While opening values.yaml file page yaml not showing from serial no-1
2. Find option not showing in values.yaml file page while finding anything else
3. log analyzer page hidding  resume & clear button

External app support nit

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/nodeDetailTab.scss
src/components/v2/common/message.ui.tsx

Logs manifest bugfixes

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.css

Utkarsh's bugs
1. Remove border-top from Pod container selection row. Although, this border-top should be visible in resource > Logs Tab
2. Alignment of dropdown in Logs/ Terminal/Log Analyzer

External app support ut1

---

src/components/v2/appDetails/index.store.ts
src/components/v2/appDetails/k8Resource/nodeType/NodeDelete.component.tsx

Karik's bug
1. When opting to delete a service, the confirmation box displays the message "Delete Pod". Also, after deleting the service, the service tab does not appear on the UI with missing information.

External app supprt kar

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx

Desired manifest formatting fixed

desired manifest formatting fixed

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Terminal.component.tsx
src/components/v2/common/message.ui.tsx

1. Alignment of dropdown in Terminal
2. Position of "Manifest/Events not available" should be in center.

External app support testing bugs

---

src/components/charts/modal/DeployChart.scss
src/components/charts/modal/DeployChart.tsx
src/components/util/URLUtil.ts
src/components/v2/appDetails/ea/EAAppDetail.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
src/components/v2/appDetails/k8Resource/nodeType/NodeDelete.component.tsx
src/components/v2/index.tsx
src/components/v2/values/DeployChart.tsx

NItish bugs:
1. while updating replicas in values.YAML directly it is resulting, it should initiate whatever the taking action
2. Last update timer not working properly till refreshing the page
3. After opening any pod log scroller one needed for same page (like log Analyzer page)
4. App name hidden not showing properly for any chart

External app support nit2

---

src/components/v2/appDetails/k8Resource/StatusFilterButton.component.tsx
src/components/v2/appDetails/k8Resource/k8resources.css
src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx
src/components/v2/common/message.ui.tsx

Bugs from sheet1
1. Filtered items under the healthy tab doesn't match the count
2. Filter button is not working properly for the right side resource detail
(after filter other than all for eg in case of Healthy, getting other pod resources status like Missing)
3. After rerendering when the data get prefetch, In case we select healthy filter > all the filtered data get replaced with all
4. When no container is selected then the height doesn't cover full space

External app support pra

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/nodeDetailTab.scss

Copy Icon + logs resume on search
1. During the copying log row copy icon not visible properly (it should be in center always)
2. Bug in Filtering while stop condition

Copy Icon + logs resume on search

---

src/components/v2/appDetails/appDetails.store.ts
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/nodeDetailTab.scss

CSS: During the copying log row copy icon not visible properly (it should be in center always)
TS: open tab is already 5 and if i want to open same component(out of those 5) it shows reuse warning whereas it should reuse the tab

Logs bugfixes

---

src/components/v2/index.tsx

polling fix for devtron chart

---

src/components/v2/appDetails/AppDetails.component.tsx

show nodes if available

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
src/components/v2/assets/icons/ic-select-container.svg
src/components/v2/common/message.ui.tsx

1. In case of multiple container UI is missing

EA: multicontainer empty ui

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Terminal.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/Terminal.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/terminal.css

Fixed multiple Terminal related issues.
- Wrong terminal socket connection status upon reconnecting or changing the shell type
- Minor UI/UX bug fixes related to connection status

EA: Terminal - connection status fix, disabled input on disconnect/error states

---

src/components/common/icons/Progressing.tsx
src/components/v2/appDetails/ea/EAAppDetail.component.tsx
src/components/v2/index.tsx
src/css/base.scss

Devtron chart app detail error handling

---

src/components/app/list-new/HelmAppList.tsx
src/components/app/list/AppListView.tsx
src/components/app/list/list.css
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
src/components/v2/utils/tabUtils/tab.json.ts

1. Capitalise Column Headers
2. Rename “Desired manifest” be “Helm Generated manifest”
3. the margin between Environment and tippy

External rename

---

src/components/common/eaEmptyState/EAEmptyState.tsx
src/components/common/eaEmptyState/eaEmptyState.css
src/components/common/navigation/NavigationRoutes.tsx

EA Only >  Empty State
Page UI needs to  update
Mock: https://zpl.io/a7DdJBv
Fixes:  https://github.com/devtron-labs/devtron/issues/1125

EA: know more button moves to the the upward

---

src/components/v2/Constants/index.ts
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.type.ts

Showing info message under manifest for kind - secret.

EA: Manifest - added info text/message for secret kind

---

src/components/app/list-new/AppList.tsx
src/components/app/list-new/HelmAppList.tsx
src/components/app/list/AppListView.tsx
src/components/app/list/list.css
src/components/charts/discoverChartDetail/ChartDeploymentList.tsx
src/components/common/eaEmptyState/EAEmptyState.tsx
src/components/common/eaEmptyState/eaEmptyState.css
src/components/v2/Constants/index.ts
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Terminal.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.type.ts
src/components/v2/utils/tabUtils/tab.json.ts

1. Devtron app list and Helm app list - After page load, clicking on sort icon, then first time it doesn't sort, second time onwards it works (as first time, there is no sortOrder in query param)
2. Do not apply automatic selection of cluster (if only single cluster available) for full mode.
3. Show helm permission message for no app state only (Do not show if any app is being shown)
4. Capitalising Table header for app list
5. Rename “Desired manifest” to “Helm generated manifest”
6. margin added between Environment and tippy in header on app-list
7. CTA on full_mode feature page button text change and layout change (EAEmptyState)
8. fix for state issue when switching internal tabs in app detail
9. Terminal default type changed to sh from bash
10. App detail link changed on view chart …

Critical bugs fixes to release EA on OSS

---

src/components/charts/ChartGroupDeployments.tsx
src/components/cluster/Cluster.tsx
src/components/common/security/ScanDetailsModal.tsx
src/components/v2/appDetails/index.store.ts

Fix : https://github.com/devtron-labs/devtron/issues/1169
1) Chart group deployment list
2) Cluster agent running model
3) Scan result page
And one case fix : 
If node not came in the response of resource tree, then handling that error.

devtron chart app detail link fix and one error case fix

---

src/components/app/list-new/AppList.tsx
src/components/app/list-new/AppListService.ts
src/components/common/filter/filters.tsx
src/components/common/filter/types.tsx
src/config/constants.ts
src/services/service.ts
src/services/service.types.ts

1) Calling GetNamespace API when cluster is selected instead on pageload. and if cluster is selected and on page refresh, GetNamespace API is being called on page load
2) moved environment filter before cluster
3) GetClusterList API signature change
4) GetNamespace API signature change
5) Namespace filter new progressing and error state
Fixes # https://github.com/devtron-labs/devtron/issues/1175

fix: app list performance issue fix

---

src/config/constants.ts

Link of documentation to upgrade from hyperion to full mode has been fixed

FIX: fullmode upgrade broken link fixed

---

src/App.tsx
src/css/base.scss

Devtron update toast message change

Devtron update toast message change

---

src/components/CodeEditor/CodeEditor.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Terminal.component.tsx

- Added hover state  for all select/dropdown in v2 (Logs, Terminal, etc.)
- Added spacing between dropdown and label (Same for placeholder & cursor)
- Indentation fix in Code editor in EA app detail - Using 2 spaces.
Fixes - devtron-labs/devtron#1166

fix: Some bug fixes

---

src/components/terminal/TerminalWrapper.tsx

Allow text to be copied from terminal UI of devtron app - add feature to copy text from terminal
Fixes # https://github.com/devtron-labs/devtron/issues/1252
All changes have been tested manually.

Added -Text copy from devtron app terminal

---

src/components/app/details/main.tsx

Default appName to remove the load of app list

default appName on app Detail page

---

src/components/common/GitInfoMaterial.tsx

Need to fix loading message in ci
Fixes https://github.com/devtron-labs/dashboard/issues/1326

[FIX]: css fixed to centralise  loading  message of CI build

---

src/components/AppSelector/AppSelector.tsx
src/components/AppSelector/AppSelectorUtil.tsx
src/components/AppSelector/ChartSelector.tsx
src/components/AppSelector/index.ts
src/components/app/create/CreateApp.tsx
src/components/app/create/createApp.css
src/components/app/create/validationRules.ts
src/components/app/details/main.tsx
src/components/app/types.ts
src/components/charts/ChartGroupAdvanceDeploy.tsx
src/components/charts/ChartGroupDetails.tsx
src/components/charts/ChartGroupUpdate.tsx
src/components/charts/deploymentDetail/DeploymentDetail.tsx
src/components/charts/discoverChartDetail/DiscoverChartDetails.tsx
src/components/common/dialogs/DialogForm.tsx
src/components/common/formFields/RadioGroup.tsx
src/components/v2/headers/AppHeader.component.tsx
src/components/v2/headers/ChartHeader.component.tsx
src/components/v2/headers/EAHeader.component.tsx
src/config/constants.ts

Removed default app list call on create app and App selector in header section, Changed it to on demand fetch based on user search to optimize performance.
https://github.com/devtron-labs/dashboard/issues/320
https://github.com/devtron-labs/devtron/issues/1268

App list on demand based on user search on header and Create app

---

src/components/charts/charts.service.ts
src/components/external-apps/ExternalAppService.ts

UI phase-1 of #[1270](https://github.com/devtron-labs/devtron/issues/1270)
Fixes # https://github.com/devtron-labs/devtron/issues/1270
- [x ] refactoring
API testing

feat: UI phase-1 of #1270 some fields added

---

src/components/common/navigation/NavigationRoutes.tsx

GA not working.
SENTRY_ENABLED check fixed. Due to this being false it was returning from the function

SENTRY_ENABLED check fixed

---

.eslintrc.js
.prettierrc.js

We need to create a guide to walk through the steps on how to configure typescript-based frontend applications in VSCode to use ESLint & Prettier to auto-fix lint & indentation issues on save.
Fixes # https://github.com/devtron-labs/devtron/issues/1303
Tested manually in local on dashboard app.

Enhancement: Changes in eslintrc & prettierrc configs

---

src/components/external-apps/ExternalAppService.ts
src/components/v2/deployment-history/ea/EADeploymentHistory.component.tsx

Helm app Deployment history API response change to support rollback helm release feature
Fixes # https://github.com/devtron-labs/devtron/issues/1281
Checking the Helm app deployment history page

Helm app Deployment history API response change to support rollback helm release feature

---

src/components/app/details/cdDetails/CDDetails.tsx
src/components/app/details/cdDetails/DeploymentHistoryConfigTabView.tsx
src/components/app/details/cdDetails/DeploymentTemplateWrapper.tsx
src/components/app/details/cdDetails/cd.type.ts

Fixed when Deployment History > Configuration Page is breaking due to an unhandled null result when there is no collected history.
Fixes https://github.com/devtron-labs/devtron/issues/1393

[BUG]: Historical empty bug

---

src/components/app/details/appDetails/AppDetails.tsx
src/components/v2/appDetails/AppDetails.component.tsx
src/components/v2/appDetails/sourceInfo/environmentStatus/AppStatusDetailModal.tsx
src/components/v2/appDetails/sourceInfo/environmentStatus/EnvironmentStatus.component.tsx
src/components/v2/appDetails/sourceInfo/environmentStatus/environmentStatus.scss
src/setupProxy.js

The reason for the degraded status is not visible on devtron. In my case, it's the apiversion which was missing. which is visible on argocd but not on devtron app details page.
Fixes https://github.com/devtron-labs/devtron/issues/1355

Chart messgage 1355

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
src/setupProxy.js

page  breaking while clicking on log analyzer
Fixes https://github.com/devtron-labs/devtron/issues/1440

[BUG] page  breaking while clicking on log analyzer

---

package.json
src/components/AppSelector/AppSelectorUtil.tsx
yarn.lock

App selector seems broken
Change the inline style for selector

App selector issue fixed

---

src/services/api.ts

Fixed undefined response issue logged on sentri
returned default response in case of unauthorized user handle logout

Fixed undefined response issue logged on sentri

---

src/components/common/navigation/NavigationRoutes.tsx
src/components/login/Login.tsx
src/config/constants.ts
src/services/service.ts

Added two posthog events 1 is for login page and another is after login

Posthog events added for first time login page landing and post login

---

src/components/app/create/CreateApp.tsx
src/components/app/details/appDetails/AppDetails.tsx
src/components/app/details/appDetails/index.tsx
src/components/app/details/metrics/DeploymentMetrics.tsx
src/components/bulkEdits/BulkEdits.tsx
src/components/charts/modal/ChartGroupBasicDeploy.tsx
src/components/charts/modal/DeployChart.scss
src/components/charts/modal/DeployChart.tsx
src/components/ciConfig/CIConfig.tsx
src/components/ciPipeline/SourceMaterials.tsx
src/components/ciPipeline/WebhookSelectorCondition.tsx
src/components/common/Select/Select.tsx
src/components/common/Select/select.css
src/components/deploymentConfig/DeploymentConfig.tsx
src/components/dockerRegistry/Docker.tsx
src/components/gitProvider/GitProvider.tsx
src/components/hyperion/EnvironmentSelect.tsx
src/components/material/MaterialView.tsx
src/components/notifications/SESConfigModal.tsx
src/components/security/SecurityScansTab.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Terminal.component.tsx
src/components/v2/common/ReactSelect.utils.tsx
src/components/v2/values/common/ChartValuesSelectors.tsx

Highlight the whole background upon selection or already selected item from dropdown instead of showing tick mark.
[**List of select dropdown**](https://docs.google.com/spreadsheets/d/1FfPM6kqCWPpBBBtmvlbPVmJSEe8ZzZdQhuyYdatob9Y/edit?usp=sharing)
Fixes : https://github.com/devtron-labs/devtron/issues/1285
**Existing Selection** ->
**Expected UX/UI** ->
All tests have been performed manually. The following are the steps,
1. Visit the select-dropdown from above list
2. Click on dropdown
3. Select and Hover on any item 
4. Observe

Changed select dropdown UI/UX

---

src/components/common/navigation/Navigation.tsx
src/components/common/navigation/navigation.scss
src/components/v2/devtronStackManager/AboutDevtronView.scss
src/components/v2/devtronStackManager/AboutDevtronView.tsx
src/components/v2/devtronStackManager/DevtronStackManager.component.tsx
src/components/v2/devtronStackManager/DevtronStackManager.tsx
src/components/v2/devtronStackManager/DevtronStackManager.type.ts
src/components/v2/devtronStackManager/DevtronStackManager.utils.ts
src/components/v2/devtronStackManager/devtronStackManager.component.scss

Changes include the following UI updates in the stack manager,
- Added some new notes for different installation types
- Text change from `Modules` to `Integrations` in integration installed state
- Removed the icon from the Update button
Fixes # https://github.com/devtron-labs/devtron/issues/1637
**Change 1** - 
1. Go to stack manager
2. Go to and check different views - integration details & About Devtron
3. Observe
**Expected:** It should show different notes based on different installation types
**Change 2** - 
1. Go to stack manager
2. Make sure integration is installed
3. Go to the integration details
4. Observe
**Expected:** It should show a note with the text Integrations instead of modules
**Change 3** - 
1. Go to stack manager
2. Make sure …

Enhancement - Added installationType checks with notes & some related changes

---

README.md

Added how to contribute and initial setup steps

Added contribution steps in readme doc

---

src/components/CIPipelineN/Sidebar.tsx

Build stage URL correction

---

src/components/notifications/AddNotification.tsx
src/components/notifications/notifications.css
src/components/notifications/notifications.service.ts
src/services/service.ts

While configuring new notification on global configuration it takes lots of time to load the data since we have lots of applications and pipelines. This should load as an async process like you are doing for others filters.
Fixes - https://github.com/devtron-labs/devtron/issues/1719
Taking a lot of time to load applications, environment & projects. So, loading data on user input will make loading faster & make UX better than the current implementation.
Load data when user give input directly through API

Add notification loading fix

---

src/components/checkList/AppCheckList.tsx
src/components/checkList/AppCheckModal.tsx
src/components/checkList/ChartCheckList.tsx
src/components/checkList/GlobalConfigCheckList.tsx
src/components/common/errorBoundary.tsx

Show only those options which are not done &
Open discord widget OR navigate to join discord as it to functional
Fixes - https://github.com/devtron-labs/devtron/issues/1725
https://github.com/devtron-labs/devtron/issues/1722

Checklist > Show only those options which are not done | [Report feedback] button non functional 

---

src/components/ciConfig/CIConfig.tsx
src/components/material/CreateMaterial.tsx
src/components/material/MaterialView.tsx

If container registry is not configured, Docker Build Config page in App Configuration breaks &
If git account is disabled from global configuration, then Git repository page shows "We encountered an error".
Fixes - https://github.com/devtron-labs/devtron/issues/872 |  https://github.com/devtron-labs/devtron/issues/1348
All tests have been done manually
For Git repository
1. Have only 1 Git Account Added in Git accounts section
2. Create a new app
3. Move to App Configuration > Git Repository
For container registries
1. Create an application (Do not configure the app yet)
2. Delete all container registry configurations from global configuration (To be able to delete a container registry, it should not be used in any application)
3. Revisit the app created in Step 1; Go to App Config > …

Fixed git repo & docker build error page on App config

---

src/components/AppSelector/AppSelectorUtil.tsx
src/components/ciPipeline/LinkedCIPipelineEdit.tsx
src/components/ciPipeline/ciPipeline.css
src/components/ciPipeline/types.ts

Implemented applist on 3 char to avoid the timeout of app list
Fixes
https://github.com/devtron-labs/devtron/issues/1818

Added typeahead in linked ci pipeline

---

src/components/login/Login.tsx
src/config/constants.ts

This change will fix the broken admin password link.
This has been tested manually by visiting the respective page & clicking the link.

Fix - broken admin password link fix

---

package.json
src/App.tsx
src/components/CodeEditor/CodeEditor.tsx
src/components/app/details/cdDetails/deploymentHistoryDiff/DeploymentHistoryDiffView.tsx
src/components/app/details/metrics/DeploymentMetrics.tsx
src/components/app/list/appList.modal.ts
src/components/bulkEdits/BulkEdits.tsx
src/components/common/errorBoundary.tsx
src/components/common/helpers/Helpers.tsx
src/components/common/icons/Progressing.tsx
src/components/configMaps/ConfigMap.tsx
src/components/deploymentConfig/DeploymentConfig.tsx
src/components/deploymentConfig/ReadmeConfig.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/LogViewer.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/Terminal.tsx
src/components/v2/appDetails/sourceInfo/EnvironmentSelector.component.tsx
yarn.lock

These changes will fix multiple issues logged in sentry. Some of them are TypeErrors & some are lib related.
Fixes #https://github.com/devtron-labs/devtron/issues/1852
All tests have been performed manually by executing logged steps & visiting URLs.

Fix - TypeError & lib related issues fixes

---

src/components/EmptyState/EmptyState.tsx
src/components/app/details/triggerView/EmptyStateCIMaterial.tsx
src/components/app/details/triggerView/TriggerView.tsx
src/components/app/details/triggerView/cdMaterial.tsx
src/components/app/details/triggerView/ciMaterial.tsx
src/components/app/details/triggerView/types.ts
src/components/app/details/triggerView/workflow/nodes/triggerCDNode.tsx
src/components/common/GitCommitInfoGeneric.tsx
src/components/common/GitInfoMaterial.tsx

Navigating to app details after triggering cd pipeline | CI material selection select position & fixed trigger deploy UI bugs
Fixes - https://github.com/devtron-labs/devtron/issues/1815

Navigate app details after triggering cd pipeline | CI material selection select position

---

src/components/app/details/metrics/DeploymentMetrics.tsx

These changes will fix the issue around time in the to & from date range on the deployment metrics page. Also, fixed the time range for the same.
All tests have been performed manually by visiting the deployment metrics page & observing the payload in the network calls after changing the dates.

Fix - Deployment metrics: changed to & from time to 24 hrs format

---

src/components/EnvironmentOverride/DeploymentTemplateOverride.tsx
src/components/charts/list/DiscoverCharts.tsx
src/components/charts/useChartGroup.ts

Chart Store > Discover > Repo filter > Sort alphabetically
Demo > No Chart groups > Create Group > Navigates away from page in the background
Env Override > On deleting override the comparison view should go away

#1902 fe bugs

---

src/components/app/details/cIDetails/CIDetails.tsx
src/components/common/helpers/Helpers.tsx

Select and copy doesn't work sometimes (or atleast doesn't gives the feedback).
Pasting copied text from terminal fails to work almost everytime.
Incorrect date is shown after deployment in build history & deployment history
Fixes - https://github.com/devtron-labs/devtron/issues/1642

Fixed copy/paste issue | Incorrect date

---

src/components/app/details/appDetails/AppDetails.tsx
src/css/base.scss

Fixed UI in appdetails when no app is deployed & make the empty UI common
Fixes - https://github.com/devtron-labs/devtron/issues/1917

Fixed empty UI in appDetail

---

src/components/v2/values/chartValuesDiff/ChartValuesView.component.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.type.ts

- Compare values > compare with > Deployed value: show version along with app name in dropdown + selected state
- Compare values > Ability to compare with default values also
- Compare values > Show version for editable values.yaml

Helm values enhancements

---

src/components/charts/SavedValues/SavedValuesList.tsx
src/components/charts/SavedValues/savedValues.scss
src/components/charts/SavedValues/types.ts
src/components/charts/chartValues/ChartValues.tsx
src/components/charts/charts.helper.ts
src/components/charts/charts.service.ts
src/components/charts/discoverChartDetail/DiscoverChartDetails.tsx
src/components/charts/list/DiscoverCharts.tsx
src/components/charts/modal/ManageValues.tsx
src/config/routes.ts

Create listing page with empty state, Provide edit and delete option, Provide user the option to search within saved values
Fixes # [(issue)](https://github.com/devtron-labs/devtron/issues/1921)

#1921 : Saved value list

---

src/components/charts/list/DiscoverCharts.tsx

Empty chart group issue fix
Fixes # [(issue)](https://github.com/devtron-labs/dashboard/issues/412)
Manual testing

Empty Chart group issue fix

---

src/index.tsx

SENTRY_TRACES_SAMPLE_RATE for Sentry performance monitor fixed

SENTRY_TRACES_SAMPLE_RATE issue fixed

---

src/components/app/details/appDetails/AppDetails.tsx
src/components/app/details/appDetails/appDetails.scss

Empty state UI is updated for Appdetails when nothing is configure & deployed
Fixes - https://github.com/devtron-labs/devtron/issues/1958

Added empty state when nothing is deployed

---

src/components/CIPipelineN/CIPipeline.tsx
src/components/CIPipelineN/CustomInputVariableSelect.tsx
src/components/ciPipeline/types.ts
src/components/common/dialogs/DeleteDialog.tsx
src/components/workflowEditor/workflowEditor.tsx

- Delete workflow when user deletes CI pipeline
- CI Pre/post build > Rename 'Global variables' to 'System variables'
Fixes - https://github.com/devtron-labs/devtron/issues/1961

Added workflow delete with CI deleted

---

src/components/charts/discoverChartDetail/DiscoverChartDetails.tsx
src/components/charts/discoverChartDetail/types.tsx
src/components/checkList/AppCheckModal.tsx
src/components/checkList/ChartCheckList.tsx
src/components/checkList/GlobalConfigCheckList.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.api.ts

Made changes as per gitops removed from chart list
Fixes - https://github.com/devtron-labs/devtron/issues/1975

Remove charts gitops

---

src/components/common/helpers/time.ts

Timezone is set according to the Indian time zone which creates incorrect time for user apart from India
Fixes - https://github.com/devtron-labs/devtron/issues/1973

Update timezone according to browser

---

src/components/v2/appDetails/k8Resource/k8resources.css

Helm app details page inconsistent UI when more than 10 or 20 same kinds of resources are present
Fixes - https://github.com/devtron-labs/devtron/issues/2088

Hotfix - Fixed helm UI bug

---

src/components/charts/SavedValues/SavedValuesList.tsx
src/components/charts/SavedValues/savedValues.scss
src/components/charts/SavedValues/types.ts
src/components/charts/discoverChartDetail/DiscoverChartDetails.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
src/config/routes.ts

These changes will enable additional data - last updated by & updated to be displayed in the preset values list/table on the saved preset values view. It'll also enable an action to provide users the ability to deploy charts directly using the preset/saved values.
Resolves https://github.com/devtron-labs/devtron/issues/2038
**Case # 1: Additional metadata**
1. Go to chart store
2. Select desired chart to deploy that contains some saved preset values
3. Select preset values - it'll redirect to preset values listing view
4. Observe
**Expected:** It should display last updated by & updated at (DateTime) against the individual preset value in the list/table.
**Case # 2: Deploy action**
1. Go to chart store
2. Select desired chart to deploy that contains …

Enhancement: Preset values - showing additional metadata & deploy action

---

src/components/app/details/triggerView/EmptyStateCIMaterial.tsx
src/components/app/details/triggerView/MaterialHistory.tsx
src/components/app/details/triggerView/TriggerView.tsx
src/components/app/service.ts
src/components/common/GitInfoMaterial.tsx
src/config/constants.ts
src/css/forms.scss

At the time of select material to create build by default there is only top 15 commits fetched. The user don't have any option to fetch any prior commit. To solve this issue we provide a search box in which user can enter commit hash and search the commit to create build.
Fixes # [(issue)](https://github.com/devtron-labs/dashboard/issues/445)

Search commit based on commit hash

---

src/components/CIPipelineN/Build.tsx
src/components/apiTokens/GroupPermission.tsx
src/components/cdPipeline/CDPipeline.tsx
src/components/cdPipeline/cdpipeline.util.tsx
src/components/ciPipeline/SourceMaterials.tsx
src/components/userGroups/User.tsx
src/components/userGroups/UserGroup.scss
src/components/userGroups/UserGroup.tsx

Dropdown Scrolling is not working for react select when user clicks on dropdown & try to scroll the page
Fixes - https://github.com/devtron-labs/devtron/issues/2112
By manually testing each react-select element from this list
https://docs.google.com/spreadsheets/d/1OQKwbIGmBFk9KwqRHVw0f2-QwWyQFowhFI_pf8FxVGg/edit?usp=sharing

Fixed react-select no scrolling on select

---

src/components/gitProvider/GitProvider.tsx
src/components/material/MaterialView.tsx
src/components/material/material.types.ts

Git account: Need to update documentation for authentication type "Anonymous" while adding the Version controller
Fixes - https://github.com/devtron-labs/devtron/issues/2150
By selecting git account having public account

Added git information for anonymous authentication

---

src/components/ciPipeline/validationRules.ts

Fixes https://github.com/devtron-labs/devtron/issues/2173
tested out manaully

VALIDATION RULE: handling for invalid regex added

---

package.json
src/components/v2/values/chartValuesDiff/ChartValuesView.utils.ts
yarn.lock

Reverting the YAML version from 2.1.1 to 1.7.2 because of some char length validation failures.

Fix - reverting yaml version

---

src/components/app/create/CreateApp.tsx
src/components/app/create/validationRules.ts
src/components/app/types.ts
src/components/material/MaterialView.tsx
src/config/constants.ts

1. In helmapp, user can create an app starting with just number or only number which is not expected
2. App config > Checkout path messaging change
Fixes - https://github.com/devtron-labs/devtron/issues/2170

Changed regex for helm-appName | Checkoutpath message changed

---

src/components/ciPipeline/SourceMaterials.tsx
src/components/ciPipeline/validationRules.ts

App Configuration  > Workflow > Click in create pipeline 
Build & Deploy > Page breaks whenever an invalid regex value passed in source value
Fixes https://github.com/devtron-labs/devtron/issues/2201
Manually tasted

Branch regex validation

---

src/components/app/details/appDetails/AppDetails.tsx
src/components/v2/appDetails/ea/EAAppDetail.component.tsx
src/components/v2/appDetails/index.store.ts
src/components/v2/index.tsx

These changes will fix issues around URL generation for getting manifest, event, and logs in case of no git-ops deployment
Fixes # https://github.com/devtron-labs/devtron/issues/2190
All tests have been performed manually on both GitOps & No-GitOps env.

Fix - updated conditions for getting manifest/event/logs in no-gitops

---

src/components/app/details/appDetails/AppDetails.tsx
src/components/app/details/appDetails/SourceInfo.tsx
src/components/app/details/appDetails/appDetails.type.ts
src/components/app/details/appDetails/utils.tsx

Deployment status triggerd by show different in case of git commit failed
Fixes # [(issue)](https://github.com/devtron-labs/dashboard/issues/481)

Deployment status triggered by from the new API

---

src/components/app/details/appDetails/SourceInfo.tsx
src/components/app/details/appDetails/utils.tsx
src/components/app/details/cdDetails/CDDetails.tsx
src/components/app/details/cdDetails/DeploymentDetailSteps.tsx
src/components/app/details/cdDetails/cd.type.ts
src/components/app/details/cdDetails/cdDetail.scss

Handle case for aborted deployment
Handle when application status available but no KUBCTL_APPLY and/or no GIT_COMMIT
Some other minor bugs

Deployment status bugfixes

---

src/components/app/details/cdDetails/CDDetails.tsx

Fixes # [(issue)](https://github.com/devtron-labs/dashboard/issues/493)
manually tested

PipelineID Fixed for no GitOps

---

src/components/app/details/appDetails/DeploymentStatusDetailModal.tsx
src/components/app/details/appDetails/SourceInfo.tsx

Added fix for empty deployment finished date and missing icon
manually tested

minor UI fix added

---

src/components/app/details/cdDetails/CDDetails.tsx

Deployment history fix in case of No pipeline created

Added check in case of no Pipelinbe created

---

src/components/v2/devtronStackManager/DevtronStackManager.component.tsx

Fixed issue of update button in case of module update. added check for upgrade view and setShowPreRequisiteConfirmationModal only if it is available 

Upgrade view Check added

---

src/components/app/list-new/AppList.tsx

This change will enable support of search term filter to export app metadata to CSV.
Fixes # https://github.com/devtron-labs/dashboard/issues/2272
All tests have been performed manually by exporting data on the app listing with the search filter.

Export To CSV: support of search term filter

---

src/components/common/dialogs/Dialog.type.ts
src/components/common/dialogs/ForceDeleteDialog.tsx
src/components/v2/appDetails/sourceInfo/environmentStatus/AppStatusDetailModal.tsx
src/modals/commonTypes.tsx

UI/UX Multiple issues on the dashboard
1 Data getting out of the div
Fixes https://github.com/devtron-labs/devtron/issues/2298
Manually tested out

UI/UX multi bugs 

---

src/components/common/navigation/NavigationRoutes.tsx
src/components/login/Login.tsx
src/components/login/login.types.ts
src/components/onboardingGuide/OnboardingGuide.tsx

The user is redirecting to the guided onboarding page always after refreshing the dashboard
Fixes https://github.com/devtron-labs/devtron/issues/2316

BUG: fix for onboarding navigation

---

src/index.tsx

Added a check of service worker to prevent it from logging

minor fix to prevent serviceworker error

---

src/components/common/navigation/NavigationRoutes.tsx

fix for navigation bug
Fixes https://github.com/devtron-labs/devtron/issues/2324

Navigation bug

---

src/components/security/SecurityPolicyEdit.tsx

These changes will fix the issue with the security policy inheritance issue.
Fixes #[2340](https://github.com/devtron-labs/devtron/issues/2340)

Fix - added conditions for security policy inheritance issue

---

src/components/app/details/cdDetails/CDDetails.tsx

Getting failed to load the view after clicking on the browser's back button on the deployment history page & clicking on deployment history
Fixes - https://github.com/devtron-labs/devtron/issues/2176
##To Reproduce
1. Go to AppDetails page
2. Navigate to the Deployment history tab
3. Click on the browser's back button
4. Observe

Deployment history - Fixed blank screen

---

src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx

These changes will fix the expanded node details section collapses when data gets refreshed issue on the AppDetails page.
Resolves https://github.com/devtron-labs/devtron/issues/2174
1. Go to the AppDetails page
2. Scroll to node details (k8 resources) & expand any node
3. Wait for 30sec polling to refresh data
4. Observe
**Expected:** It should not collapse the expanded node details

Fix - node details collapse after data refresh issue

---

src/components/app/details/appDetails/AppDetails.tsx
src/components/v2/headers/AppHeader.component.tsx
src/components/v2/headers/ChartHeader.component.tsx
src/components/v2/headers/EAHeader.component.tsx
src/components/v2/headers/header.scss

1. Helm app header
2. deployment status details not working on app-detail.
Fixes https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/495/

header bug  fixes

---

src/components/common/filter/filter.css
src/components/common/gettingStartedCard/GettingStarted.tsx
src/components/onboardingGuide/GuideCommonHeader.tsx
src/components/security/SecurityScansTab.tsx
src/components/security/security.css
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/Terminal.tsx
src/css/base.scss

Multiple CSS bug fixes
1. Onboarding>Cross button coming in background heading line
2. Security scan>while we filter out environment, The no of count environment selection coming downside in the security page
3. Color of the buttons on the tippy is not as expected in OSS
4. CSS of cross buttons of security filters needs to fix
5. In terminal connecting and error messaging both are visible
6. In terminal CSS of resume, button background is misplaced
Fixes https://github.com/devtron-labs/devtron/issues/2363
Tested out all the cases manually

CSS final fixes

---

src/components/EnvironmentOverride/ConfigMapOverrides.tsx
src/components/EnvironmentOverride/SecretOverrides.tsx
src/components/app/details/appDetails/AppMetrics.tsx
src/components/charts/list/DiscoverCharts.tsx
src/components/common/navigation/Navigation.tsx
src/components/deploymentConfig/types.tsx
src/components/secrets/Secret.tsx
src/components/secrets/secret.utils.tsx
src/components/v2/devtronStackManager/DevtronStackManager.component.tsx
src/components/v2/devtronStackManager/DevtronStackManager.service.ts
src/config/constants.ts
src/css/base.scss

Fixed ESO module install check on dropdown open
Tested manually

Module integration bugfixes

---

src/components/common/LogoutCard.tsx
src/components/common/filter/filters.tsx
src/components/common/formFields/Typeahead.tsx

Filters Outer Click is not working in Multiple places
Logout card
App List Filters
Fixes https://github.com/devtron-labs/devtron/issues/2369

added dc to transition

---

src/components/app/details/AboutAppInfoModal.tsx
src/components/app/details/main.tsx
src/components/app/service.ts
src/components/app/types.ts
src/components/common/infocolourBar/InfoColourbar.tsx
src/config/constants.ts
src/css/base.scss

These changes will enable the feature to move apps to a different project based on the user's access to those projects.
Fixes - AB#510
All tests have been performed manually by moving applications between projects from AppDetails - About app modal.

Enhancement - Enabled feature to move app to different project

---

src/components/EnvironmentOverride/ConfigMapOverrides.tsx
src/components/EnvironmentOverride/EnvironmentOverrides.type.ts
src/components/EnvironmentOverride/SecretOverrides.tsx
src/components/app/details/cdDetails/cd.utils.tsx
src/components/deploymentConfig/types.tsx
src/components/secrets/Secret.tsx
src/components/secrets/secret.utils.tsx
src/config/constants.ts

Remove the ESO as module integration. revert all the changes
manually verified

Eso module revert

---

src/components/app/details/triggerView/ciMaterial.tsx
src/components/common/navigation/Navigation.tsx
src/components/globalConfigurations/GlobalConfiguration.tsx

Nav fix after useref update added dummy state. minor text fix on CI material

Security nav fix

---

src/components/v2/devtronStackManager/DevtronStackManager.component.tsx
src/components/v2/devtronStackManager/DevtronStackManager.utils.ts

Only one installation should run at a time. Added the check for the same
Fixes # [(issue)](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/559)
Installed 1 module and visited other module details page installation option is disabled there with message of other installation inprogress

Added check for other installation

---

src/config/constants.ts

Updated the blob storage support doc link
Manually testd

Updated blob storage URL

---

src/components/v2/devtronStackManager/DevtronStackManager.component.tsx
src/components/v2/devtronStackManager/DevtronStackManager.tsx

Lag in installing state due to setTimeout fixed.
manually tested by installing multiple modules

setTimeout lag fixed

---

src/components/app/details/triggerView/ciMaterial.tsx

Blob storage configure doc url fix
Fixes # [(issue)](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/603)
Manually verified

blob storage Doc URL fix

---

src/components/app/grepSSEworker.ts

These changes will enable timestamps in logs.
Fixes - [AB#600](https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/Devtron%20Team/Issues/?workitem=600)

Enhancement - Showing timestamp in logs

---

src/components/ciPipeline/ExternalCIPipeline.tsx
src/components/ciPipeline/LinkedCIPipelineView.tsx
src/components/ciPipeline/types.ts
src/components/workflowEditor/Workflow.tsx
src/components/workflowEditor/workflowEditor.tsx

Added additional checks to handle the old empty workflows & delete the workflow after deleting the external/linked CI pipeline
Fixes - [AB#512](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/512)

Hotfix - additional checks for handling empty workflows

---

src/App.tsx

Fixes # [AB#528](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/528)
Manually tested by deploying multiple builds

528 force reload on navigation on service worker update

---

src/components/v2/appDetails/k8Resource/StatusFilterButton.component.tsx
src/components/v2/appDetails/sourceInfo/environmentStatus/AppStatusDetailModal.tsx

In case of no resource available for selected filter the filter is getting hidden and page shows empty. If there is no resource available for selected filter select the `All` filter and show all resources
Fixes # [(AB#679)](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/679)
Manually tested on inprogress status

Default to all in case of no resource for selected filter

---

src/components/app/details/triggerView/TriggerView.utils.ts
src/components/app/details/triggerView/cdMaterial.tsx
src/components/app/details/triggerView/triggerViewConfigDiff/TriggerViewConfigDiff.tsx
src/css/triggerView.css

Some enhancements & additional checks for the rollback feature.

[Patch] Rollback UX enhancements

---

Dockerfile

Increased timeout for yarn install

FIX: Increased timeout for yarn install

---

src/components/v2/appDetails/sourceInfo/environmentStatus/AppStatusDetailModal.tsx

Missing Error message on app status detail modal

app status detail modal error message fix

---

src/components/deploymentConfig/DeploymentConfig.utils.ts

Simplifying Deployment template: basic is getting locked in case of delete override
Fixes # [(AB#657](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/657)
Manually tested verified the base deployment template and deployment template override

Simplifying Deployment template bugfix

---

src/components/common/navigation/Navigation.tsx
src/components/common/navigation/NavigationRoutes.tsx
src/components/v2/devtronStackManager/DevtronStackManager.tsx

ServerInfo with status in case of stack manager

---

src/components/v2/appDetails/appDetails.type.ts
src/components/v2/appDetails/k8Resource/k8resources.scss
src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx

Reverts devtron-labs/dashboard#588

Revert "Pod restart count and age"

---

src/components/EnvironmentOverride/DeploymentTemplateOverride.tsx
src/components/deploymentConfig/DeploymentConfig.tsx
src/components/deploymentConfig/DeploymentConfig.utils.ts
src/components/deploymentConfig/DeploymentTemplateView.tsx
src/components/deploymentConfig/constants.tsx

Deployment template page breaks in case of no parent key presnt in YAML
Manually verified by creating the template and override

Deployment template hotfix

---

src/components/v2/appDetails/appDetails.type.ts
src/components/v2/appDetails/k8Resource/k8resources.scss
src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx

Added Restarts and Age for pods where we can see the pod age and restart count of pod.
FEAT # https://github.com/devtron-labs/devtron/issues/2469

Revert "Revert "Pod restart count and age""

---

src/components/common/error/ErrorBar.tsx
src/components/v2/appDetails/SyncError.component.tsx

In case of degraded/missing node info value is missing due to which page is breaking on app details
Fixes # [AB#1175](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/1175)
Manually tested by visiting app details page

fix: Added check of value in case of degraded/missing

---

src/components/app/list-new/AppList.tsx
src/components/app/list-new/HelmAppList.tsx
src/components/app/list/AppListView.tsx
src/components/app/list/DevtronAppListContainer.tsx
src/components/app/list/types.tsx

Showing message: "Syncing" instead of "Last synced few seconds ago" when loading app list page
Fixes https://github.com/devtron-labs/devtron/issues/2530  [AB#967](https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/Devtron%20Team/Issues/?workitem=967)

fix: App and Helm list last sync while loading

---

src/components/charts/discoverChartDetail/DiscoverChartDetails.tsx

Text Change:
In Chart detail Change Button text from ‘Deploy…’ to ‘Configure & Deploy'
Fixes https://github.com/devtron-labs/devtron/issues/2650  [AB#1201](https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/Devtron%20Team/Issues/?workitem=1201)
1. Go to Chart Store
2. Go to chart Detail
3. In Chart detail Change Button text from ‘Deploy…’ to ‘Configure & Deploy'

Fix: Rename Deploy… to Configure & Deploy

---

src/components/v2/headers/AppHeader.component.tsx
src/components/v2/headers/ChartHeader.component.tsx
src/components/v2/headers/header.scss

In Helm App detail > Rename Values tab with a gear icon to Configure
Fixes  [AB#1203](https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/Devtron%20Team/Issues/?workitem=1203)
1- Go to the Helm Chart
2- Go to second tab

fix: Rename Values to Configure

---

src/components/v2/appDetails/appDetails.api.ts
src/components/v2/appDetails/k8Resource/nodeType/NodeDelete.component.tsx
src/components/v2/appDetails/k8Resource/nodeType/nodeType.scss

These changes will add an option (checkbox) to provide users the ability to choose whether to delete the resource with `--force` flag - `true` or `false`; making the force delete optional by default.
Fixes - [AB#966](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/966)
All tests have been performed manually by,
- Visiting AppDetails for all 3 types - Devtron app, Devtron charts (helm apps), and external helm apps
- Try to delete the resources with `--force` flag set to `true` or `false`.

feat: Added option to make force delete resource optional

---

src/components/app/details/cIDetails/CIDetails.tsx
src/components/app/details/triggerView/cdMaterial.tsx
src/components/common/GitCommitInfoGeneric.tsx

Removed unnecessary brackets which caused errors in the code.

fix: remove unncessary bracket that caused error

---

src/components/ciPipeline/Webhook/WebhookDetailsModal.tsx
src/components/workflowEditor/workflowEditor.tsx
src/config/constants.ts

User already has a CI running in some platform (Jenkins, Circle CI etc.) and they want to use Devtron for deployment by leveraging their existing CI
Fixes # [AB#936](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/936)
- verified by creating new webhook CD
- deletion of webhook CD
- validated current flow working

fix: incoming webhook CI bugfixes

---

src/components/charts/ChartGroupUpdate.tsx
src/components/charts/ChartHeaderFilters.tsx
src/components/charts/list/DiscoverCharts.tsx
src/components/common/Accordian/Accordian.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
src/config/constants.ts
src/css/base.scss

Chart store 
1. Make list view as default
2. Grid/List option UI
3. Do not show GUI tab if GUI not available
Fixes # [ISSUE 1244](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/1244)

feat: Chart store UI enhancement 

---

src/components/externalLinks/ExternalLinks.tsx
src/components/externalLinks/ExternalLinks.type.ts
src/components/externalLinks/ExternalLinksCRUD/AddExternalLink.tsx
src/components/externalLinks/ExternalLinksCRUD/ConfigureLinkAction.tsx
src/components/externalLinks/ExternalLinksCRUD/IdentifierSelector.tsx

Added additional full-mode checks for external links.
Fixes - [AB#988](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/988)
All tests have been performed manually by changing server mode.

Enhancement - additional checks for full mode

---

src/components/deploymentConfig/DeploymentTemplateView.tsx
src/components/deploymentConfig/constants.tsx
src/components/deploymentConfig/validationRules.ts

Key is incorrect when saving environment variables in basic deployment template. it should be `name` instead of `key`
Fixes # [AB#1274](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/1274)
Manually tested by creating new apps and on existing apps

fix : Env variable key change from `key` to `name`

---

src/components/app/details/triggerView/cdMaterial.tsx
src/components/common/GitCommitInfoGeneric.tsx

User already has a CI running in some platform (Jenkins, Circle CI etc.) and they want to use Devtron for deployment by leveraging their existing CI
Fixes # [AB#936](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/936)
- verified by creating new webhook CD
- deletion of webhook CD
- validated current flow working

fix: Source info empty value check

---

src/components/EnvironmentOverride/DeploymentTemplateOverride.tsx
src/components/deploymentConfig/DeploymentConfig.tsx
src/components/deploymentConfig/DeploymentConfig.utils.ts
src/components/deploymentConfig/constants.tsx

this issue is coming only In case of deployment template without`ingress` key for oss it is giving basic locked and also lands on the basic
Fixes # [AB#1301](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/1301)
Manually tested on fresh cluster with OSS setup

fix: Basic view locked issue fixed

---

src/components/app/details/app.css
src/components/v2/headers/AppHeader.component.tsx
src/components/v2/headers/EAHeader.component.tsx
src/components/v2/headers/header.scss

Replace value to configure name in helm CLI apps
Fixes  [AB#1317](https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/Devtron%20Team/Issues/?workitem=1317)
Tested out with cli helm apps

fix: Replace value to configure name in cli helm apps

---

src/components/cdPipeline/CDPipeline.tsx

fix for gitops or helm option for cd pipeline. Validation was failing because default value was set to empty string.
Fixes #650 
1) enabled GitOps ot Helm option.
2) while creating CD pipeline checked that validation check is passed or not.

fix: validation failing while creating CD pipeline.

---

src/components/app/create/CreateApp.tsx

At the time of creation of app when host is not set, it is showing error toast .
Fixes # [AB#1350](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/1350)
Manually verified

fix: App creation auto set host url issue

---

src/components/ClusterNodes/NodeActions/CordonNodeModal.tsx
src/components/ClusterNodes/NodeActions/DeleteNodeModal.tsx
src/components/ClusterNodes/NodeActions/DrainNodeModal.tsx
src/components/ClusterNodes/NodeActions/EditTaintsModal.tsx
src/components/ClusterNodes/NodeActions/NodeActionsMenu.tsx
src/components/ClusterNodes/NodeDetails.tsx
src/components/ClusterNodes/NodeList.tsx
src/css/base.scss

This PR the testing bugfixes of node action

fix: Node action bugs

---

src/components/ClusterNodes/ClusterList.tsx
src/components/ClusterNodes/ClusterNodeContainer.tsx
src/components/ClusterNodes/ClusterTerminal.tsx
src/components/ClusterNodes/NodeDetails.tsx
src/components/ClusterNodes/NodeList.tsx
src/components/ClusterNodes/constants.ts
src/components/ClusterNodes/types.ts
src/components/common/helpers/Helpers.tsx

Fixes [#AB1617](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/1617/)
All the tests have been done manually

feat: Update image list on version

---

src/components/ClusterNodes/ClusterNodeContainer.tsx
src/components/ClusterNodes/NodeActions/NodeActionsMenu.tsx
src/components/ClusterNodes/NodeDetails.tsx
src/components/ClusterNodes/NodeList.tsx
src/components/ClusterNodes/types.ts

Added auth check on node actions
Fixes - [AB#1662](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/1662) 
https://github.com/devtron-labs/devtron/issues/2830
Tested with different user with and without access

fix: Auth check on node actions

---

src/components/ResourceBrowser/ResourceList/K8SResourceList.tsx
src/components/ResourceBrowser/ResourceList/ResourceList.tsx
src/components/common/header/PageHeader.tsx
src/components/common/navigation/Navigation.tsx
src/css/base.scss

These changes will enable a beta tag for the resource browser nav & page.
Fixes - [AB#1673](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/1673)

feat: added beta tag for resource browser

---

src/components/app/details/cdDetails/CDDetails.tsx
src/components/app/details/triggerView/MaterialSource.tsx
src/components/app/list-new/HelmAppList.tsx
src/components/ciConfig/CIAdvancedConfig.tsx

These changes will fix multiple issues observed during the testing of FE enhancements.
All tests have been performed manually by visiting respective pages

fix: FE enhancements - bug fixes around CI & CD details flow

---

src/components/app/details/appDetails/AppDetails.tsx
src/components/app/details/appDetails/SourceInfo.tsx
src/components/app/details/appDetails/appDetails.type.ts
src/config/constants.ts

These changes will enable deployment status card for helm type Devtron apps
Fixes - [AB#1845](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/1845)
All tests have been performed manually by accessing Devtron apps of type helm.

feat: Showing deployment status card for helm type Devtron apps

---

src/components/ResourceBrowser/ResourceList/ResourceList.tsx
src/components/common/navigation/Navigation.tsx

These changes will enable beta tag for resource browser
Fixes - [AB#1767](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/1767)
Checked manually by visiting resource browser

feat: beta tag for resource browser

---

src/components/ResourceBrowser/ResourceList/EventList.tsx
src/components/ResourceBrowser/ResourceList/K8SResourceList.tsx
src/components/ResourceBrowser/Types.ts

These changes will fix the pagination interaction & behaviour issue for Resource browser list
Fixes - [AB#1767](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/1767)

fix: Resource browser - pagination interaction & behaviour fix

---

src/components/security/SecurityScansTab.tsx

Fixed the issue of the filtered Cluster and environment going outside the page.
Fixes [#1876](https://github.com/devtron-labs/devtron/issues/1876)
- Tested by going to the page and seeing the desired result

security-scan-page-filtering-fix

---

src/components/app/types.ts

This PR has the fix for build fail
Fixes # [(AB#1733)](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/1733)
- Created new app and verified the new UI
- Open existing app go in App overview section
- Edit the tags and verify new UI

fix: build failed

---

src/components/userGroups/UserGroup.tsx

SSO configurations required for adding user.
Fixes #[AB1989](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/1989)

fix : EmptyState shown on group Permission on sso not configured

---

src/components/Environments/Environment.service.ts
src/components/app/details/triggerView/workflow.service.ts

Ab 1950 grouped build deploy filtered

---

src/components/Environments/Environment.service.ts

fixed bug where cd to postcd edge was missing

---

src/components/EnvironmentOverride/EnvironmentOverride.tsx
src/components/EnvironmentOverride/EnvironmentOverrides.type.ts
src/components/EnvironmentOverride/environmentOverride.scss
src/components/Environments/Constants.ts
src/components/Environments/EnvEmptyStates.tsx
src/components/Environments/EnvironmentConfig/AppOverrides.tsx
src/components/Environments/EnvironmentConfig/ApplicationRoutes.tsx
src/components/Environments/EnvironmentConfig/EnvConfig.tsx
src/components/Environments/EnvironmentDetailsRoute.tsx
src/components/Environments/EnvironmentListService.ts
src/components/Environments/EnvironmentOverview/EnvironmentOverview.tsx
src/components/Environments/List/EnvironmentListView.tsx
src/components/Environments/List/EnvironmentsList.scss
src/components/Environments/List/EnvironmentsList.tsx
src/css/base.scss

Minor fixes in applist api & envList api, UX/UI changes
Fixes #[AB1952](https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/OSS%20adoption/Stories/?workitem=1952)

fix: Fixed app grouping UI/UX

---

src/components/ApplicationGroup/List/EnvironmentsList.tsx
src/components/app/details/appDetails/appDetails.scss

Page scrolls when cluster filter select is on focus
Fixes [#2143](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/2143)

fix: Scroll issue in app-group list page

---

src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.api.ts

changed the api end point for events as BE doesn't need dynamic version value.the version should be v1 in the url.
All tests have been performed manually by visiting events tab.

fix: removed dynamic version & used v1 as valid

---

src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx
src/css/base.scss

Fix for resource, long message ui is broken
Fixes [#AB2214](https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/OSS%20adoption/Stories/?workitem=2214)

fix: ui fixes for resource long message ui 

---

src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/ApplicationGroup/List/EnvironmentsList.tsx
src/components/common/navigation/Navigation.tsx

1. Added beta tag in App group
2. Handling of API race condition when cicd in progress state and without  progress state
Fixes [#AB2267](https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/OSS%20adoption/Stories/?workitem=2267)
- Go to the App Group > Build & Deploy > status API must trigger after every 30sec
- While the app build is in progress status API must trigger after every 10sec

fix: env selector api race condition | app group beta tag

---

src/components/app/grepSSEworker.ts
src/components/v2/appDetails/appDetails.type.ts
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Terminal.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.css
src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.util.ts

These changes will fix InitContainer logs not visible issue for helm type apps.
Fixes - [AB#2270](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/2270)
All tests have been performed manually by visiting AppDetails page for apps of type helm.

fix: InitContainer logs not visible from app details page issue fix

---

src/components/ResourceBrowser/ResourceList/ResourceList.tsx
src/components/ResourceBrowser/Utils.ts

These changes will fix,
1. Loader issue after kind search
2. Empty state visible issue in resource list view after namespace change
Fixes - [AB#2325](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/2325)
All tests have been performed manually by visiting resource browser & performing different actions.

fix: loader issue fix for kind search & resource search retention

---

src/components/apiTokens/__tests__/ApiTokens.test.tsx
src/components/app/Overview/Overview.tsx
src/components/app/details/triggerView/__tests__/triggerview.test.tsx

These changes will fix the redirection loop from overview page.
All tests have been performed manually by visiting overview page from AppDetails & Jobs

fix: the overview redirection issue on 401

---

src/components/app/details/appConfig/AppConfig.tsx
src/components/common/navigation/NavigationRoutes.tsx
src/components/globalConfigurations/GlobalConfiguration.tsx
src/components/workflowEditor/workflowEditor.tsx

These changes will fix the default redirection issue on app list & global config.
All tests have been performed manually by visiting different routes after the changes.

fix: Default redirection on app list & global config issue fix

---

src/components/apiTokens/EditAPIToken.tsx
src/components/common/infocolourBar/InfoColourbar.tsx

Changed the margin of info bar in edit - token page from main main file to temporary class .
1: Manually on dashboard.

fix: info bar margin change

---

src/components/CIPipelineN/CIPipeline.tsx

this is a bug in the previous pr.
1.this has been tested locally by creating multiple pipelines.

bug:'fix in source type'

---

src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.api.ts

Resource browser manifest and event was breaking due a recently pushed release #804 
Verification of expected data in resource browser and app details for manifest and event data.

fix: Resource browser manifest and event breaking

---

src/components/app/details/cicdHistory/TriggerDetails.tsx

disabled the timer changes
Test performed manually

fix: timer changes

---

src/components/app/Overview/Overview.tsx
src/components/app/create/CreateApp.tsx
src/components/app/details/AboutTagEditModal.tsx
src/components/common/header/HelpNav.tsx
src/components/common/navigation/navigation.scss
src/css/base.scss

This PR consist the bug fixes of tags
Fixes # [AB#2557](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/2557)
Tested by creating multiple tags

fix: Tags fixe and enhancements

---

package.json

feat:package upgraded

---

package.json

Reverts devtron-labs/dashboard#878

Revert "feat:package upgraded"

---

src/components/app/details/cicdHistory/History.components.tsx
src/components/app/details/triggerView/MaterialHistory.tsx
src/components/app/details/triggerView/cdMaterial.tsx
src/components/app/details/triggerView/ciMaterial.tsx
src/components/ciPipeline/SourceMaterials.tsx
src/components/common/GitCommitInfoGeneric.tsx
src/components/common/GitMaterialInfo.tsx
src/components/material/MaterialList.tsx
src/components/material/MaterialView.tsx

Adding data-test-id for git repository flow

feat:"adding data-test-id"

---

src/components/app/details/cdDetails/CDDetails.tsx
src/components/app/details/cicdHistory/Artifacts.tsx
src/components/app/details/cicdHistory/TriggerDetails.tsx
src/components/app/details/cicdHistory/types.tsx

This PR include fix of wrong details of commit and image on CI/CD details page
Fixes # [AB#2646](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/2646)
Tested manually by creating CI and CD including post CD and Pre CD

fix: Commit details + Image details on CI/CD details page

---

src/components/app/details/main.tsx
src/components/app/details/triggerView/workflow/Workflow.tsx
src/components/app/details/triggerView/workflow/nodes/TriggerLinkedCINode.tsx
src/components/ciPipeline/LinkedCIPipelineEdit.tsx
src/components/common/formFields/Typeahead.tsx
src/components/workflowEditor/CDSuccessModal.tsx
src/components/workflowEditor/nodes/CINode.tsx

"datatestid for linked ci flow"

---

src/components/common/navigation/Navigation.tsx

These changes will fix the condition for hiding or showing any nav option.
Fixes - https://github.com/devtron-labs/devtron/issues/3254

fix: Jobs available in hyperion mode issue fix

---

src/components/cdPipeline/CDPipeline.tsx
src/components/workflowEditor/nodes/CDNode.tsx

added locators for cd-pipeline flow

---

src/components/ApplicationGroup/Details/EnvironmentConfig/__mock__/EnvConfig.mock.ts

This PR has fix for build issue

fix: build issue

---

src/components/ApplicationGroup/Details/EnvironmentOverview/__mock__/EnvironmentOverview.mock.ts
src/components/ApplicationGroup/List/__mocks__/EnvironmentList.mock.ts

This PR has fix for build issue

fix: build issue fixed

---

src/components/ClusterNodes/ClusterList.tsx
src/components/ClusterNodes/NodeList.tsx
src/components/ClusterNodes/clusterNodes.service.tsx

The PR includes bug fixes of optimization

fix: Api optimization bugfix

---

src/components/app/details/main.tsx
src/components/app/details/triggerView/MaterialHistory.tsx
src/components/app/details/triggerView/workflow/Workflow.tsx
src/components/app/details/triggerView/workflow/nodes/triggerCDNode.tsx
src/components/app/list/AppListView.tsx
src/components/ciConfig/CIAdvancedConfig.tsx
src/components/ciConfig/CIContainerRegistryConfig.tsx
src/components/ciConfig/CICreateDockerfileOption.tsx
src/components/ciConfig/CIDockerFileConfig.tsx
src/components/material/MaterialList.tsx

format fix

---

src/components/ResourceBrowser/ResourceList/ClusterSelection.tsx
src/components/ResourceBrowser/ResourceList/ConnectingToClusterState.tsx
src/components/ResourceBrowser/ResourceList/CreateResource.tsx
src/components/ResourceBrowser/ResourceList/K8SResourceList.tsx
src/components/ResourceBrowser/ResourceList/ResourceBrowserActionMenu.tsx
src/components/ResourceBrowser/ResourceList/ResourceFilterOptions.tsx
src/components/ResourceBrowser/ResourceList/ResourceList.tsx
src/components/ResourceBrowser/ResourceList/Sidebar.tsx
src/components/app/details/appDetails/AppDetails.tsx
src/components/app/details/triggerView/BranchRegexModal.tsx
src/components/ciPipeline/SourceMaterials.tsx
src/components/common/DynamicTabs/DynamicTabs.tsx
src/components/common/header/PageHeader.tsx
src/components/material/MaterialView.tsx
src/components/security/DeleteCVEModal.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/EventsTable.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx

"resource-browser-flow"

---

src/components/app/Overview/Overview.tsx
src/components/app/Overview/TagChipsContainer.tsx
src/components/app/details/AboutTagEditModal.tsx
src/components/charts/ChartGroupDetails.tsx
src/components/charts/ChartHeaderFilters.tsx
src/components/charts/MultiChartSummary.tsx
src/components/common/formFields/CustomInput.tsx
src/components/gitOps/GitOpsConfiguration.tsx
src/components/hostURL/HostURL.tsx
src/components/v2/common/ReactSelect.utils.tsx

fix: Data-TestIds-fix

---

src/components/EnvironmentOverride/ConfigMapOverrides.tsx
src/components/EnvironmentOverride/DeploymentTemplateOverride.tsx
src/components/app/details/appConfig/AppConfig.tsx
src/components/app/details/appDetails/DeploymentStatusBreakdown.tsx
src/components/app/details/cdDetails/CDDetails.tsx
src/components/app/details/cdDetails/CDEmptyState.tsx
src/components/app/details/cdDetails/DeploymentDetailSteps.tsx
src/components/app/details/cdDetails/deploymentHistoryDiff/DeploymentHistoryConfigList.component.tsx
src/components/app/details/cdDetails/deploymentHistoryDiff/DeploymentHistoryDiffView.tsx
src/components/app/details/cdDetails/deploymentHistoryDiff/DeploymentHistoryHeader.tsx
src/components/app/details/cicdHistory/History.components.tsx
src/components/app/details/cicdHistory/Sidebar.tsx
src/components/app/details/cicdHistory/TriggerDetails.tsx
src/components/app/details/cicdHistory/types.tsx
src/components/charts/discoverChartDetail/DiscoverChartDetails.tsx
src/components/deploymentConfig/ChartSelectorDropdown.tsx
src/components/deploymentConfig/DeploymentConfig.tsx
src/components/deploymentConfig/DeploymentTemplateView.tsx
src/components/workflowEditor/CDSuccessModal.tsx

Fixed Blanked Data Test Ids and Formatted the code Accordingly for Deployment History and Deployment Template.

fix: Data-Test Ids Fix For CD Deployment History

---

src/components/CustomChart/CustomChartList.tsx
src/components/CustomChart/UploadChartModal.tsx
src/components/charts/MultiChartSummary.tsx
src/components/ciConfig/CIAdvancedConfig.tsx
src/components/v2/common/message.ui.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.component.tsx
src/components/workflowEditor/NoGitOpsConfiguredWarning.tsx
src/config/constants.ts
src/util/Subject.ts

fix: fix for PR comments

---

src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/app/details/appDetails/AppDetails.tsx
src/components/app/details/triggerView/TriggerView.tsx
src/components/app/list/DevtronAppListContainer.tsx
src/components/app/list/appList.modal.ts
src/components/app/service.ts
src/components/cluster/Cluster.tsx
src/components/externalLinks/ExternalLinks.service.ts
src/services/service.ts

fix: Locator fix

---

src/components/app/list/__tests__/AppListView.test.tsx

fix'd id in unit test case

---

src/components/apiTokens/APITokenList.tsx
src/components/apiTokens/EditAPIToken.tsx
src/components/apiTokens/GenerateActionButton.tsx
src/components/userGroups/Group.tsx
src/components/userGroups/User.tsx
src/components/v2/common/message.ui.tsx
src/components/workflowEditor/workflowEditor.tsx

Added data test ids user & group permissions in global configuration page. And formatted the modified components.

feat: user auth data test ids

---

src/components/v2/appDetails/k8Resource/NodeTreeTabList.tsx
src/components/v2/appDetails/sourceInfo/environmentStatus/AppStatusDetailModal.tsx

app details page test ids

---

src/components/ApplicationGroup/AppGroupDetailsRoute.tsx
src/components/ApplicationGroup/List/EnvironmentListView.tsx
src/components/ApplicationGroup/List/EnvironmentsList.tsx

data-test-id for app group listing page and build history page 
All test are performed locally

feat:data-test-id for app group listing page and build history page 

---

src/components/ApplicationGroup/AppGroup.utils.ts
src/components/ApplicationGroup/AppGroupAppFilter.components.tsx
src/components/ApplicationGroup/AppGroupAppFilter.tsx
src/components/ApplicationGroup/AppGroupDetailsRoute.tsx
src/components/ApplicationGroup/CreateAppGroup.tsx
src/components/ApplicationGroup/Details/EnvCDDetails/EnvCDDetails.tsx
src/components/ApplicationGroup/Details/EnvCDDetails/__mock__/EnvCDDetails.mock.ts
src/components/ApplicationGroup/Details/EnvCDDetails/__test__/EnvCDDetails.test.tsx
src/components/ApplicationGroup/Details/EnvCIDetails/EnvCIDetails.tsx
src/components/ApplicationGroup/Details/EnvCIDetails/__mock__/EnvCIDetails.mock.ts
src/components/ApplicationGroup/Details/EnvironmentOverview/EnvironmentOverview.tsx
src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/ApplicationGroup/SearchBar.tsx
src/components/app/details/cIDetails/CIDetails.tsx
src/components/app/details/cIDetails/types.tsx

This PR includes the fix for all the QA cycle bugs of app group create update and delete. 
Fixes # [AB#2676](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/2676)
Manually tested by creating updating multiple app groups

fix: App group create update delete bugfix

---

src/components/ciPipeline/LinkedCIPipelineView.tsx

fix: sanity

---

src/components/ciConfig/CICreateDockerfileOption.tsx

Added a data-testid for automation.

feat: added a data-testid

---

src/components/charts/MultiChartSummary.tsx
src/components/charts/modal/CreateChartGroup.tsx

fix: Data-Testids for sanity

---

src/components/app/details/appDetails/AppDetails.tsx
src/components/app/details/appDetails/SourceInfo.tsx

These changes will fix `Not able to switch environment in app details page` issue.
Fixes https://github.com/devtron-labs/devtron/issues/3315

fix: env dropdown disabled fix

---

src/components/app/details/appConfig/AppConfig.tsx

date-testid for lock icon on app configuration page

---

src/components/v2/chartDeploymentHistory/ChartDeploymentHistory.component.tsx
src/components/v2/chartDeploymentHistory/chartDeploymentHistory.service.ts

Added and passed the deployedBy field in helm apps deployment history but not in the case of app deployed through external apps.
Fixes #[2847](https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/OSS%20adoption/Stories/?workitem=2847)
1: Created deployedBy in the preview to be passed.
2: Got that value from the database and recieved it on the frontEnd.
3: Checked through various apps whether the deployedBy field is coming on the preview and UI or not, it is working fine.

feat: added deployed by field in helm apps deployment history

---

src/components/app/details/triggerView/TriggerView.tsx

This PR contains the fix for loader issue on rollback image
manually tested

fix: loader issue on build rollback

---

src/components/ApplicationGroup/CreateAppGroup.tsx
src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx
src/components/ApplicationGroup/Details/TriggerView/BulkCITrigger.tsx
src/components/CIPipelineN/CIPipeline.tsx
src/components/ClusterNodes/ClusterList.tsx
src/components/ClusterNodes/NodeActions/EditTaintsModal.tsx
src/components/ClusterNodes/clusterNodes.scss
src/components/ResourceBrowser/ResourceList/CreateResource.tsx
src/components/app/create/CreateApp.tsx
src/components/app/details/cdDetails/cdDetail.scss
src/components/ciPipeline/Webhook/WebhookDetailsModal.tsx
src/components/ciPipeline/ciPipeline.scss
src/components/cluster/Cluster.tsx
src/components/dockerRegistry/Docker.tsx
src/components/gitOps/GitOpsConfiguration.tsx
src/components/gitProvider/GitProvider.tsx
src/components/hostURL/HostURL.tsx
src/components/project/ProjectList.tsx

This PR contains the multiple ui fixes
Fixes [AB#2892](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/2892)
Manually tested by opening all the cases in specific order

fix: UI issues

---

src/components/app/Overview/Overview.tsx

added one missing testid for cancel button

cancel button testid

---

src/components/app/details/triggerView/workflow/nodes/triggerCDNode.tsx
src/components/app/details/triggerView/workflow/nodes/triggerCINode.tsx

fix: node trigger status testid

---

src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/app/details/triggerView/TriggerView.tsx
src/components/app/details/triggerView/cdMaterial.tsx
src/components/app/service.ts
src/components/userGroups/UserGroup.tsx

These changes will fix issue with pre-deployment flow in workflow trigger view
Fixes - [AB#2753](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/2753)
All test have been performed manually.

fix: workflow - pre deployment issue fix

---

src/components/app/details/appDetails/DeploymentStatusCard.tsx
src/components/app/details/appDetails/SourceInfo.tsx
src/components/app/details/appDetails/appDetails.type.ts
src/components/v2/appDetails/sourceInfo/environmentStatus/EnvironmentStatus.component.tsx

deployment status card bug fix

fix: Deployment status devtron helm

---

src/components/app/list-new/AppList.tsx
src/components/app/list-new/AppListService.ts

export csv do not have any list after selecting clusters .
Fixes #[AB3365](https://github.com/devtron-labs/devtron/issues/3365#)
I have tested this locally.

fix:export csv do not have any list after selecting clusters and also project is not showing in csv .

---

src/components/app/details/appDetails/utils.tsx

fix for the previously deployed app

fix: for previously deployed app

---

src/components/bulkEdits/BulkEdits.tsx

Breaking with every incorrect yaml 
Fixes: https://github.com/devtron-labs/devtron/issues/3394

fix: bulk edit config map missing fix

---

src/components/app/details/appConfig/AppConfig.tsx
src/config/constantMessaging.ts

Fixes https://github.com/devtron-labs/devtron/issues/3398

fix: tippy message change

---

src/components/ClusterNodes/ClusterTerminal.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Terminal.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/Terminal.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/TerminalWrapper.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/terminal.type.ts
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/terminal.utils.tsx

Added testId in terminal of cluster terminal, resource browser, & k8s resources
Fixes [#AB3116](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/3116)

fix: Added testId for terminal

---

src/components/app/details/triggerView/workflow/nodes/triggerCDNode.tsx

data-testid for deployment strategy verification

---

src/components/app/details/appDetails/DeploymentStatusCard.tsx

fix:last updated heading testId

---

package.json

Common-lib-version-update
All the test cases have been tested manually.

fix: version-update-common-lib

---

src/components/app/list-new/AppList.tsx

Right now after export csv the apps , it only showing the apps present on UI per page on devtron.
Fixes #[AB3431](https://github.com/devtron-labs/devtron/issues/3431)
Have been tested Locally

fix:Export csv only show apps which are showing on UI rows per page. 

---

src/components/app/list-new/AppListService.ts
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/Terminal.tsx

Applist page break in Hyperion mode due to autocomplete API
Fixes [#AB)](https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/OSS%20adoption/Stories)

fix: Applist api break for hyperion mode

---

src/components/ciConfig/CIConfig.utils.ts

build configuration page breaking for newly created application.
- tested for devtron existing devtron apps and newly created apps

fix: Build config page break fix

---

src/components/material/CreateMaterial.tsx
src/components/material/UpdateMaterial.tsx

Value was getting saved even after unchecking the box. Fixed that.

fix: exclude-include-check-fix

---

src/components/app/details/appDetails/AppDetails.tsx
src/components/app/details/cdDetails/DeploymentDetailSteps.tsx
src/components/app/details/triggerView/cdMaterial.tsx
src/components/app/list-new/AppListService.ts
src/components/app/list/AppListView.tsx
src/components/cdPipeline/CDPipeline.tsx
src/components/cdPipeline/cdPipeline.scss
src/components/common/DeploymentTypeIcon/DeploymentTypeIcon.tsx
src/components/common/Select/Select.tsx
src/components/common/Select/select.css
src/components/common/helpers/Helpers.tsx
src/components/notifications/AddNotification.tsx
src/components/notifications/NotificationTab.tsx
src/components/notifications/notifications.service.ts
src/components/notifications/notifications.util.tsx
src/components/userGroups/UserGroup.tsx
src/components/v2/appDetails/AppDetails.component.tsx
src/components/v2/appDetails/sourceInfo/EnvironmentSelector.component.tsx
src/components/v2/chartDeploymentHistory/ChartDeploymentHistory.component.tsx
src/css/base.scss
src/css/workflow.scss

Some UI fixes & enhancement from UAT & QA around virtual cluster

fix: UI fixes & hide deploy for helm in virtual

---

src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/app/details/appDetails/AppDetails.tsx
src/components/common/DeploymentTypeIcon/DeploymentTypeIcon.tsx

V code smell

---

src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/app/details/triggerView/TriggerView.tsx

1. for the cd trigger incorrect image tag is being added to the package-name in some cases
2. multiple images are showing selected in preCD/CD trigger in some cases.

fix: Virtual bugs

---

src/components/cluster/ClusterForm.tsx
src/components/cluster/Environment.tsx

Production bug fix for kubeconfig story.
Issue # (https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/OSS%20adoption/Stories/?workitem=3602)

prod bug fix for kubeconfig

---

src/components/ApplicationGroup/AppGroup.types.ts
src/components/ApplicationGroup/Details/TriggerView/TriggerModalTableRow.tsx
src/components/ApplicationGroup/Details/TriggerView/TriggerResponseModal.tsx

minor keyword change for automation
Fixes #

fix: restricted keyword changed in props

---

src/components/cdPipeline/CDPipeline.tsx
src/components/cluster/Environment.tsx

1. Enable config in CD
2.  data test id fix for cd config

fix: enable cd config for virtual

---

src/components/ResourceBrowser/ResourceBrowser.scss

fix: height fixture in resource browser

---

src/components/ApplicationGroup/Details/TriggerView/TriggerResponseModal.tsx

Removed code smell for prev release #1041 

code smell fix

---

package.json
src/components/CIPipelineN/CIPipeline.tsx
src/components/CIPipelineN/PluginCardListContainer.tsx
src/components/CIPipelineN/PreBuild.tsx
src/components/CIPipelineN/TaskDetailComponent.tsx
src/components/app/details/triggerView/types.ts
src/components/app/details/triggerView/workflow.service.ts
src/components/ciPipeline/LinkedCIPipelineEdit.tsx
src/components/ciPipeline/ciPipeline.service.ts
src/components/ciPipeline/types.ts

CI Pipeline enforcement changes
Fixes # AB#3164
Tested manually with hardcoded data

fix: Plugin enhancements

---

package.json
src/components/app/details/triggerView/TriggerView.tsx
src/components/app/details/triggerView/ciMaterial.tsx
src/components/app/details/triggerView/types.ts
src/components/app/details/triggerView/workflow.service.ts
src/components/app/details/triggerView/workflow/Workflow.tsx
src/components/app/details/triggerView/workflow/nodes/TriggerLinkedCINode.tsx
src/components/app/details/triggerView/workflow/nodes/triggerCINode.tsx
src/components/common/GitInfoMaterial.tsx
src/css/base.scss
yarn.lock

These changes include plugin view & blocked states.
Fixes - [AB#3281](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/3281)

feat: Plugin views & blocked states

---

package.json
src/components/ApplicationGroup/Details/TriggerView/BulkCITrigger.tsx
src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/common/GitInfoMaterial.tsx

CI Pipeline enforcement changes
Fixes # AB#3164
Tested manually with hardcoded data

fix: App group fixes

---

src/components/CIPipelineN/CIPipeline.tsx
src/css/base.scss
yarn.lock

Contains multiple bug fixes & new/updated interactions.
Fixes - [AB#3281](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/3281)

feat: multiple fixes & new implementations

---

src/components/ApplicationGroup/Details/TriggerView/TriggerModalTableRow.tsx
src/components/app/details/triggerView/workflow/nodes/triggerPrePostCDNode.tsx
src/components/app/list-new/HelmAppList.tsx
src/components/v2/chartDeploymentHistory/ChartDeploymentHistory.component.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.component.tsx

Virtual cluster automation id added
Fixes [#AB3193](https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/OSS%20adoption/Stories/?workitem=3193)

fix: Added ids for chartStore

---

src/components/ApplicationGroup/Details/TriggerView/BulkCITrigger.tsx
src/components/app/details/cIDetails/CIDetails.tsx
src/components/app/details/cicdHistory/Sidebar.tsx
src/components/common/security/ScannedByToolModal.tsx
src/config/constantMessaging.ts
src/css/base.scss

1. getCIBlockState check added in bulkcitrigger page
2. Height  & scroll for long build history
3. Security no vulnerability text fix
4. Security Button UI fix

Fix: Multiple UI fixes

---

src/components/app/details/triggerView/workflow.service.ts
src/components/ciPipeline/LinkedCIPipelineView.tsx

This PR contains the fix of linked CI title issue on view linked CI page and linked CI node.
https://github.com/devtron-labs/dashboard/assets/95338474/cf327cf3-2404-4ca5-8b76-55be437458a9
- Tested by creating CI with `ci--prod` and then created child linked ci in different app
- Updated the name `ci--dev` and verified the values

fix: Linked ci title issue

---

package.json
src/components/app/details/cIDetails/ciDetails.scss
src/components/app/details/cicdHistory/ImageTags.tsx
src/components/app/details/cicdHistory/types.tsx
src/components/app/details/triggerView/cdMaterial.tsx
src/components/app/details/triggerView/types.ts
src/css/formulae.scss
src/css/triggerView.scss

Added UI fixes for image tagging task 
Fixes [#AB3842](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/3842)

fix: UI image tagging

---

src/components/app/details/cdDetails/CDDetails.tsx
src/components/v2/appDetails/k8Resource/nodeType/nodeType.scss
src/components/v2/chartDeploymentHistory/ChartDeploymentHistory.component.tsx

adhoc fixes
1. Generated package name
//imageTag is missing in name
2. Generated package name in Devtron App > Deployment history > Artifact
3.  Generated package name in App Group > Deployment history > Artifact

fix: Multi QA adhoc fixes

---

src/components/dockerRegistry/Docker.tsx

pwd is supposed to be sent in ''(quotes). fixed this issue in this PR
Fixes: https://github.com/devtron-labs/devtron/issues/3549#

fix : password sending in incorrect format

---

package.json
src/components/app/types.ts
src/components/cdPipeline/CDPipeline.tsx
src/components/cdPipeline/cdPipeline.service.ts
src/components/cdPipeline/cdPipeline.types.ts
src/components/common/helpers/Helpers.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.component.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.type.ts
src/components/v2/values/common/chartValues.api.ts
src/services/service.ts
src/services/service.types.ts

This PR contains the changes of radioGroup enhancement which is add disabled option on Radiogroup item
Fixes # [3509](https://github.com/devtron-labs/devtron/issues/3509)
Tested manually with multiple env with different different deployment type tool enforcement

feat: Deployment tool enforcement

---

src/components/CIPipelineN/AdvancedConfigOptions.tsx
src/components/CIPipelineN/Build.tsx
src/components/CIPipelineN/CIPipeline.tsx
src/components/app/details/triggerView/cdMaterial.tsx
src/components/ciConfig/CIConfig.tsx
src/components/ciConfig/CIConfigForm.tsx
src/components/ciConfig/CICreateDockerfileOption.tsx
src/components/ciConfig/CIDockerFileConfig.tsx
src/components/ciConfig/types.tsx
src/components/common/security/ScannedByToolModal.tsx

These changes include,
- Fix for Build config state issue when central api is failing or not reachable
- Fix for spacing issue in scan drawer
- Fix for misplaced trigger button for pre-post
Fixes - https://github.com/devtron-labs/devtron/issues/3536

fix: Build config state issue fix for central api & some other fixes

---

src/components/charts/AdvancedConfig.tsx
src/components/charts/ChartGroupAdvanceDeploy.tsx
src/components/charts/ChartGroupDeployments.tsx
src/components/charts/ChartGroupDetails.tsx

fix:test_id addition for chartstore

---

src/components/charts/AdvancedConfig.tsx

Added data testids for the helm app advanced option page.

feat: data test ids for helm app advanced option page 

---

src/components/charts/ChartGroupAdvanceDeploy.tsx

fix: Chartstore test id addition

---

src/components/cdPipeline/CDPipeline.tsx
src/components/common/helpers/Helpers.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.tsx

CD pipeline creation is breaking in the case of virtual deployment

fix: Virtual cluster CD create

---

src/components/charts/AdvancedConfig.tsx
src/components/charts/ChartGroupAdvanceDeploy.tsx
src/components/dockerRegistry/Docker.tsx
src/components/globalConfigurations/GlobalConfiguration.tsx
src/components/globalConfigurations/globalConfigurations.scss
src/config/constants.ts
src/css/forms.scss

Integrated OCI registries in global config registries and integrated the corresponding API for that.
Configure OCI registry in Global config.

feat:  OCI registry integration in global config

---

src/components/ClusterNodes/ClusterDetails.tsx
src/components/ClusterNodes/NodeDetails.tsx
src/components/ClusterNodes/clusterNodes.scss
src/components/app/list-new/HelmAppList.tsx
src/components/app/list/AppListView.tsx

1-Helm Apps List-Last deployed at' sorting missing
2-Show sort arrow on all sortable columns by default
Fixes #[3906](https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/OSS%20adoption/Stories/?workitem=3906)

fix: sort helm list by last deployed

---

src/components/dockerRegistry/Docker.tsx
src/components/globalConfigurations/GlobalConfiguration.tsx
src/components/globalConfigurations/globalConfigurations.scss
src/config/constants.ts
src/css/forms.scss

fixed UI bugs and updates for OCI registry integration in Global config.

fix: OCI registry integration UI bugs fixes and requirement updates

---

src/components/v2/headers/ChartHeader.component.tsx

fix: testid for helm app config link

---

src/components/app/details/appDetails/DeploymentStatusBreakdown.tsx
src/components/app/details/appDetails/DeploymentStatusDetailRow.tsx
src/components/app/details/appDetails/ErrorInfoStatusBar.tsx
src/components/app/details/appDetails/appDetails.type.ts

Css fixes for deployment status added.

 fix: UAT fixes for deployment status added.

---

src/components/v2/values/chartValuesDiff/ChartRepoSelector.tsx

Chore: testid addition for helm config

---

src/components/v2/chartDeploymentHistory/ChartDeploymentHistory.component.tsx

This will fix the values.yaml data format for helm apps of deployment type EA_ONLY
Fixes https://github.com/devtron-labs/devtron/issues/3612

fix: values are not shown in yaml format for apps of type EA_ONLY.

---

src/components/charts/ChartGroupUpdate.tsx

chore: testid-addition

---

src/components/app/details/cIDetails/CIDetails.tsx
src/components/app/details/cdDetails/CDDetails.tsx

fix: image tagging build history 

---

src/components/app/details/triggerView/EmptyStateCIMaterial.tsx

Unable to fetch empty state images during selecting images for build. 

fix: Image fetching issue in CI Build

---

src/components/notifications/AddNotification.tsx
src/components/notifications/ModifyRecipientsModal.tsx
src/components/notifications/notifications.service.ts

There was issue in adding recipient in modifying recipients on notification.
Fixes [#3607](https://github.com/devtron-labs/devtron/issues/3607)
Tested the cases by sending notifications across different cases on slack.

fix: webhook-notification-fix

---

src/components/login/SSOLogin.tsx

After saving any SSO configuration it's getting saved correctly, but after refreshing the page it shows some fixed values for all the SSO login services.
Fixes #https://github.com/devtron-labs/devtron/issues/3540

Fix: SSO configuration gets change after refreshing the page

---

src/components/CIPipelineN/PreBuild.tsx

This PR contains the change to fix the working of plugin. 
Fixes # [(3628)](https://github.com/devtron-labs/devtron/issues/3628#)

fix: Plugin issue

---

src/components/ClusterNodes/NodeDetails.tsx
src/components/app/details/triggerView/cdMaterial.tsx

Redirection of URL of pods in cluster section

fix: url namespace

---

src/components/v2/appDetails/k8Resource/nodeDetail/EphemeralContainerDrawer.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/nodeDetailTab.scss
src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.util.ts

fix: ephemeral Css feedback

---

src/components/app/create/validationRules.ts
src/config/constants.ts

Fixed validation for create app name as "." was valid from FE
Fixes [#AB4419](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/4419)

fix: Updated validation for appName

---

src/components/ApplicationGroup/Details/TriggerView/TriggerModalTableRow.tsx
src/components/CIPipelineN/CIPipeline.tsx
src/components/ResourceBrowser/ResourceList/CreateResource.tsx
src/components/apiTokens/APITokenList.tsx
src/components/apiTokens/__tests__/ApiTokens.test.tsx
src/components/app/details/cIDetails/CIDetails.tsx
src/components/app/details/cIDetails/cIDetails.util.tsx
src/components/app/details/triggerView/TriggerView.tsx

Multiple fixes around UI, empty state and app group Bulk CI
Fixes [#AB4423](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/4423)

fix: UI & bug fixes around empty state & appgroup

---

src/assets/icons/ic-ephemeral.svg
src/components/ClusterNodes/ClusterTerminal.tsx
src/components/ResourceBrowser/ResourceList/ResourceList.tsx
src/components/app/details/cIDetails/CIDetails.tsx
src/components/v2/appDetails/appDetails.type.ts
src/components/v2/appDetails/k8Resource/nodeDetail/EphemeralContainerDrawer.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Terminal.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/nodeDetailTab.scss
src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.api.ts
src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.type.ts
src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.util.ts
src/components/v2/appDetails/k8Resource/nodeDetail/sampleConfig.json
src/components/v2/common/ReactSelect.utils.tsx
src/config/constantMessaging.ts
src/css/base.scss

feat: Ephemeral container 
Fixes https://github.com/devtron-labs/devtron/issues/3662

feat: ephermeral container

---

src/components/CIPipelineN/Sidebar.tsx
src/components/cdPipeline/BuildCD.tsx
src/components/cdPipeline/NewCDPipeline.tsx
src/components/secrets/Secret.tsx
src/components/secrets/secret.utils.tsx

Some issues around cd container list, jobs secret

fix: Some issues around cd container list, jobs secret

---

src/components/EnvironmentOverride/ConfigMapOverrides.tsx
src/components/configMaps/ConfigMap.tsx

Fix regarding the data-type of ConfigMaps in jobs.

fix: job-config-map-dropdown-fix

---

src/components/ConfigMapSecret/ConfigMap/ConfigMapList.tsx
src/components/ConfigMapSecret/ConfigMapSecret.components.tsx
src/components/ConfigMapSecret/ConfigMapSecretForm.tsx
src/components/EnvironmentOverride/EnvironmentOverride.tsx
src/components/EnvironmentOverride/EnvironmentOverrides.type.ts
src/components/app/details/appConfig/AppConfig.tsx
src/components/app/details/appConfig/appConfig.type.ts
src/components/deploymentConfig/DeploymentConfig.tsx
src/components/deploymentConfig/types.tsx

This PR Contains the changes of ConfigMap and Secret draft view
Fixes # [AB#4120](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/4120), [AB#4121](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/4121)
Manually tested all the scenarios by creating different different cm and secret

feat: cm secret enhancements

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Terminal.component.tsx

In the resource browser & app details page, the terminal is not connecting as API is not called when component mounts
Fixes [#AB4561](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/4561)

fix: Terminal api is not called for the first time

---

src/components/v2/appDetails/appDetails.api.ts

User with Admin level access on Helm App can delete the app but can't delete any resource in it
Fixes [#AB304](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/304)

fix: Delete issue for admin user in helm app with gitops configured

---

src/components/ConfigMapSecret/ConfigMapSecret.components.tsx
src/components/EnvironmentOverride/DeploymentTemplateOverride.tsx
src/components/EnvironmentOverride/EnvironmentOverride.tsx
src/components/app/details/appConfig/AppConfig.tsx
src/components/app/details/appConfig/AppConfig.utils.ts
src/components/app/details/appConfig/EnvironmentOverrideRouter.tsx
src/components/deploymentConfig/DeploymentConfig.tsx
src/components/deploymentConfig/DeploymentConfigReducer.ts
src/components/deploymentConfig/DeploymentTemplateView/DeploymentConfigFormCTA.tsx
src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateEditorView.tsx
src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateOptionsTab.tsx
src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateView.component.tsx
src/components/deploymentConfig/types.tsx

These changes contain multiple fixes & enhancements
Fixes - AB#4092

feat: Config approval - some enhancements & additional changes

---

src/components/app/details/appDetails/AppDetails.tsx
src/components/v2/appDetails/AppDetails.component.tsx

Fixes #https://github.com/devtron-labs/devtron/issues/3410

fix: poll deployment status timeline only when status modal is opened

---

src/components/ConfigMapSecret/ConfigMap/ConfigMapList.tsx
src/components/ConfigMapSecret/ConfigMapSecret.components.tsx
src/components/ConfigMapSecret/ConfigMapSecretForm.tsx
src/components/ConfigMapSecret/Secret/SecretList.tsx
src/components/app/details/appConfig/AppConfig.tsx
src/components/app/details/appConfig/EnvironmentOverrideRouter.tsx

This PR Contains the bugfixes
Fixes # [AB#4120](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/4120), [AB#4121](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/4121)
Manually tested all the scenarios by creating different different cm and secret

fix: cm secret enhancements

---

src/components/common/Description/GenericDescription.scss
src/components/common/Description/GenericDescription.tsx
src/components/v2/values/chartValuesDiff/ChartValuesEditor.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.component.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.constants.ts
src/components/v2/values/chartValuesDiff/ChartValuesView.scss
src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.type.ts

Helm manifest comparision enabled
Fixes # [1169](https://github.com/devtron-labs/dashboard/issues/1169)

feat: Helm manifest compare

---

package.json
src/components/ApplicationGroup/AppGroupDetailsRoute.tsx
src/components/ApplicationGroup/Details/EnvironmentConfig/ApplicationRoutes.tsx
src/components/ApplicationGroup/Details/EnvironmentConfig/EnvConfig.tsx
src/components/CodeEditor/CodeEditor.tsx
src/components/ConfigMapSecret/ConfigMap/ConfigMapList.tsx
src/components/ConfigMapSecret/ConfigMapSecret.components.tsx
src/components/ConfigMapSecret/ConfigMapSecret.reducer.ts
src/components/ConfigMapSecret/ConfigMapSecret.scss
src/components/ConfigMapSecret/ConfigMapSecretDataEditorContainer.tsx
src/components/ConfigMapSecret/ConfigMapSecretForm.tsx
src/components/ConfigMapSecret/Secret/SecretList.tsx
src/components/ConfigMapSecret/Secret/secret.utils.tsx
src/components/ConfigMapSecret/Types.ts
src/components/EnvironmentOverride/DeploymentTemplateOverride.tsx
src/components/EnvironmentOverride/DeploymentTemplateOverrideForm.tsx
src/components/app/details/appConfig/AppComposeRouter.tsx
src/components/app/details/appConfig/AppConfig.tsx
src/components/app/details/appConfig/EnvironmentOverrideRouter.tsx
src/components/app/details/appConfig/appConfig.scss
src/components/app/details/cdDetails/deploymentHistoryDiff/DeploymentHistoryDiffView.tsx
src/components/app/details/cdDetails/deploymentHistoryDiff/types.ts
src/components/app/details/cdDetails/service.ts
src/components/deploymentConfig/ChartSelectorDropdown.tsx
src/components/deploymentConfig/DeploymentConfig.tsx
src/components/deploymentConfig/DeploymentTemplateView/DeploymentConfigFormCTA.tsx
src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateEditorView.tsx
src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateView.component.tsx
src/components/deploymentConfig/deploymentConfig.scss
src/css/base.scss

These PR contains all the bug fixes of deployment template, configmap & secrets.
Fixes - AB#4092
All tests have been performed manually by visiting deployment template, configmap & secrets views. And perform different actions.

fix: Config approval bug fixes

---

src/components/app/details/triggerView/cdMaterial.tsx
src/components/externalLinks/ExternalLinksCRUD/AddExternalLink.scss
src/components/externalLinks/ExternalLinksCRUD/AddExternalLink.tsx
src/components/externalLinks/externalLinks.component.scss

External Links Drawer was broken fixed it.
Fixes #[4714](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/4714)
Tested the cases manually.

fix: external links drawer-UI fix

---

src/components/gitProvider/GitProvider.tsx

Global config > Git account enable/disable switch doesn't work
Fixes #[1213](https://github.com/devtron-labs/devtron/issues/1213)

fix: git account enable/disable switch doesn't work

---

src/components/ClusterNodes/ClusterSelectionList.tsx
src/components/ResourceBrowser/ResourceList/ClusterSelector.tsx
src/components/ResourceBrowser/ResourceList/ConnectingToClusterState.tsx
src/components/ResourceBrowser/ResourceList/K8SResourceList.tsx
src/components/ResourceBrowser/ResourceList/ResourceFilterOptions.tsx
src/components/ResourceBrowser/ResourceList/ResourceList.tsx
src/components/ResourceBrowser/Types.ts

Added cluster page from cluster to resource browser
Fixes #[AB4625](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/4625)

feat: Added cluster page in resource browser

---

src/components/configMaps/ConfigMap.tsx

Config map Integer and float values get saved with block character

Fix: Config map Integer and float values get saved with block character

---

src/components/common/Description/GenericDescription.tsx

Scroll enabled in case of obverflow in about cluster page
Fixes # (https://github.com/devtron-labs/devtron/issues/3734)

fix: scroll enabled in about cluster page

---

src/components/app/details/triggerView/TriggerView.tsx

There was a issue from redirecting to approval-node from 'View Details' in Email notification.

fix: approval-node-redirection-fix

---

src/components/gitOps/GitOpsConfiguration.tsx

Update Gitops url validations for azure
Fixes https://github.com/devtron-labs/devtron/issues/3441

feat: Updated azure Gitops validation

---

src/components/chartRepo/ChartRepo.tsx
src/components/common/ValidateForm/ValidateForm.tsx
src/components/dockerRegistry/Docker.tsx
src/config/constants.ts
src/services/service.ts

Description
oci public changes in container registry
Fixes [#AB4425](https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/OSS%20adoption/Stories/?workitem=4425)
Type of change
Bug fix (non-breaking change which fixes an issue)
New feature (non-breaking change which adds functionality)
Breaking change (fix or feature that would cause existing functionality to not work as expected)
This change requires a documentation update
Checklist:
The title of the PR states what changed and the related issues number (used for the release note).
Does this PR require documentation updates?
I've updated documentation as required by this PR.
I have performed a self-review of my own code
I have commented my code, particularly in hard-to-understand areas
Please describe the tests that you ran to verify …

feat: Helm pull container registry validate/disable

---

src/components/dockerRegistry/Docker.tsx

fix for helm pull enterprise changes

feat: V3 registry helm push checkbox

---

src/components/ClusterNodes/ClusterEvents.tsx

when the user is at pod events tab by default and the image is updated. The pod events are not updated, even after the container is created.
1. open cluster terminal for any cluster.
2. click on pod events tab
3. change the image from ubuntu:kubernetes to alpine image.
4. move to pod event tab immediately, before pod creation.
5. check the pod events to be updated.
pod events should get updated as per below.
pod event not getting updated.
Fixes # [Issue](https://github.com/devtron-labs/devtron/issues/3417)

fix: bug fix for updating pod events

---

src/components/app/details/appDetails/AppDetails.tsx
src/components/app/details/appDetails/DeploymentStatusCard.tsx
src/components/app/details/appDetails/SourceInfo.tsx
src/components/app/details/appDetails/appDetails.type.ts
src/components/app/types.ts
src/components/v2/appDetails/AppDetails.component.tsx
src/components/v2/appDetails/sourceInfo/environment.type.ts
src/components/v2/appDetails/sourceInfo/environmentStatus/EnvironmentStatus.component.tsx

This PR includes the changes of delay in status fetch in deployment status detail popup
Manually tested for both type of apps

fix: Deployment status delay issue

---

src/components/dockerRegistry/Docker.tsx

Bugs included: 
1. We are not able to save Public ECR Registry because of wrong validation or URL
2. To maintain registry provider types

fix: Hp bugs 2

---

src/components/ClusterNodes/NodeDetails.tsx
src/components/app/details/cIDetails/CIDetails.tsx
src/components/app/details/cdDetails/CDDetails.tsx
src/components/app/details/triggerView/cdMaterial.tsx
src/components/configMaps/ConfigMap.tsx
src/components/deploymentConfig/DeploymentTemplateView.tsx

It introduces the below fixes for issues from sentry:
* Handle the case of error from API, for nodeDetails.
* Infinite polling on change of pipeline to pipeline with null workflows in CI details
* In case of new app, handle the error for undefined pipeline in ci-details
* Some minor type checks.

fix: sentry issues

---

src/components/configMaps/ConfigMap.tsx

Null values were being saved as "0" in cm and cs due to NAN condition.
* [] Does this PR require documentation updates?

Fix : Null values handling in cm-cs

---

src/components/configMaps/ConfigMap.tsx

Null and boolean values were rendered as "0" due to NAN condition.

Fix: Cm-cs boolean and empty values handling

---

src/components/charts/discoverChartDetail/About.tsx
src/components/charts/list/ChartListPopUp.tsx
src/components/charts/list/ChartListPopUpRow.tsx
src/components/charts/list/DiscoverCharts.tsx
src/components/dockerRegistry/Docker.tsx

fixed: registry and chart store bugs

---

src/components/charts/list/AddChartSource.tsx
src/components/charts/list/ChartListPopUp.tsx
src/components/charts/list/list.scss
src/components/common/Accordian/Accordian.tsx
src/components/dockerRegistry/Docker.tsx

Bugs included:
1. Virtual Cluster Should not visible in the list of clusters during auto inject of "registry credentials"
2. There should no "validate" button in case of GCP/GAR on container/OCI Registry
3. Chart Store: For empty chart list in chart store, the empty state hides the side bar on page refresh

fix: V3 bugs QA final

---

src/components/login/login.scss

Change India independence day creative

feat: Change India independence day creative

---

src/components/chartRepo/ChartRepo.tsx
src/components/chartRepo/chartRepo.scss
src/components/charts/discoverChartDetail/About.tsx
src/components/charts/list/AddChartSource.tsx
src/components/charts/list/ChartListPopUp.tsx
src/components/charts/list/ChartListPopUpRow.tsx
src/components/charts/list/list.scss
src/components/common/Accordian/Accordian.tsx
src/components/dockerRegistry/Docker.tsx
src/css/forms.scss

1. fix for save button(added validate call also)
2. UAT fixes

Helm pull uat

---

src/components/common/ValidateForm/ValidateForm.tsx
src/components/dockerRegistry/Docker.tsx

fix for validation on container registry

fix: Helm final

---

src/components/chartRepo/ChartRepo.tsx
src/components/charts/ChartGroupUpdate.tsx
src/components/charts/list/ChartListPopUpRow.tsx
src/components/charts/list/DiscoverCharts.tsx
src/components/login/login.scss

fix: UAT fixes

---

src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx

fix: added copy icon

---

src/components/app/details/appDetails/AppDetails.tsx
src/components/v2/appDetails/sourceInfo/rotatePods/RotatePodsModal.component.tsx
src/components/v2/appDetails/sourceInfo/rotatePods/RotateResponseModal.tsx
src/components/v2/appDetails/sourceInfo/rotatePods/rotatePodsModal.type.ts

These changes optimized the client code to prevent unnecessary API calls to "timelines" and "resourceTree".
Fixes [#3679 (devtron-labs/devtron)](https://github.com/devtron-labs/devtron/issues/3679)
All tests have been performed manually by visiting App Details page and performing different actions.

fix: prevented unnecessary API calls on AppDetails

---

src/components/app/details/appDetails/AppDetails.tsx
src/components/v2/appDetails/sourceInfo/rotatePods/RotatePodsModal.component.tsx
src/components/v2/appDetails/sourceInfo/rotatePods/RotateResponseModal.tsx
src/components/v2/appDetails/sourceInfo/rotatePods/rotatePodsModal.type.ts

These changes fix the resource-tree call getting incorrect data.

fix: resource-tree call is getting data in-correctly

---

src/components/ConfigMapSecret/ConfigMapSecret.components.tsx
src/components/ConfigMapSecret/ConfigMapSecretForm.tsx
src/components/ConfigMapSecret/Types.ts
src/components/deploymentConfig/DeploymentTemplateView/DeploymentConfigFormCTA.tsx

This PR contains the fix for disabled save draft button
Fixes # [3816](https://github.com/devtron-labs/devtron/issues/3816)
Manually tested by creating apps

fix: Disabled button for draft

---

src/components/CustomChart/CustomChartList.tsx
src/components/CustomChart/CustomChartList.utils.ts
src/components/CustomChart/__mocks__/CustomChartList.mock.ts
src/components/CustomChart/__test__/CustomChartList.test.tsx

Added Unit Test Cases for CustomChartList Component

added unit test cases

---

src/components/cdPipeline/NewCDPipeline.tsx
src/components/cdPipeline/cdPipeline.service.ts

Fix for cm cs duplicate name issue
Fixes https://github.com/devtron-labs/devtron/issues/3850

fix:  cm cs duplicate name issue

---

src/components/apiTokens/authorization.utils.ts
src/components/v2/appDetails/k8Resource/nodeType/PodHeader.component.tsx
src/components/v2/appDetails/k8Resource/nodeType/PodTabSection.tsx

The pod count is updated to Zero whenever switch between old/new pods
Fixes https://github.com/devtron-labs/devtron/issues/3865#

fix: Displaying running pod count 0 after clicking on old pods.

---

src/components/scopedVariables/Descriptor.tsx
src/components/scopedVariables/SavedVariables.tsx
src/components/scopedVariables/ScopedVariablesEditor.tsx
src/components/scopedVariables/ScopedVariablesLoader.tsx
src/components/scopedVariables/UploadScopedVariables.tsx
src/components/scopedVariables/VariablesList.tsx
src/components/scopedVariables/__tests__/ScopedVariablesEditor.test.tsx
src/components/scopedVariables/__tests__/VariablesList.test.tsx
src/components/scopedVariables/constants.tsx
src/components/scopedVariables/styles.scss
src/components/scopedVariables/utils.tsx

This PR is intended to bring a footer to display error messages in case of validation issues from backend.

Fix: upload variables messaging

---

src/components/scopedVariables/Descriptor.tsx

This PR includes minor content change for Tippy in Scoped Variables Help

feat: scoped variables constants

---

src/components/ResourceBrowser/ResourceList/K8SResourceList.tsx
src/components/ResourceBrowser/ResourceList/ResourceList.tsx

This PR contains the changes for bug fixes in cluster resource browser merge

fix: Cluster resource browser bugfixes

---

src/components/v2/values/chartValuesDiff/ChartValuesView.tsx

Configure Page for externally installed helm app is breaking. This PR will fix the issue

fix: configure page of external helm app is breaking

---

src/components/EnvironmentOverride/DeploymentTemplateOverride.tsx
src/components/EnvironmentOverride/DeploymentTemplateOverrideForm.tsx
src/components/deploymentConfig/DeploymentTemplateView/DeploymentConfigFormCTA.tsx
src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateView.component.tsx

This PR includes the  fix for chart version update in case of multiple envs.
Fixes # [3883](https://github.com/devtron-labs/devtron/issues/3883)
Manually verified by creating multiple envs

fix: Chart version not updating

---

src/components/common/ClipboardButton/__tests__/ClipboardButton.test.tsx
src/components/common/DebouncedSearch/DebouncedSearch.tsx
src/components/common/DebouncedSearch/__tests__/DebouncedSearch.test.tsx
src/components/common/FloatingVariablesSuggestions/FloatingVariablesSuggestions.tsx
src/components/common/FloatingVariablesSuggestions/SuggestionItem.tsx
src/components/common/FloatingVariablesSuggestions/Suggestions.tsx
src/components/common/FloatingVariablesSuggestions/SuggestionsInfo.tsx
src/components/common/FloatingVariablesSuggestions/__tests__/FloatingVariablesSuggestions.test.tsx
src/components/common/FloatingVariablesSuggestions/__tests__/Suggestions.test.tsx
src/components/common/FloatingVariablesSuggestions/__tests__/SuggestionsInfo.test.tsx
src/components/common/FloatingVariablesSuggestions/__tests__/SuggestionsItem.test.tsx
src/components/common/FloatingVariablesSuggestions/constants.ts
src/components/common/FloatingVariablesSuggestions/mocks.ts

This PR aims to bring unit tests for Floating Suggestions widget

Test: floater suggestions

---

src/components/ResourceBrowser/ResourceList/ConnectingToClusterState.tsx
src/components/ResourceBrowser/ResourceList/ResourceList.tsx
src/components/ResourceBrowser/Types.ts
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx

This PR contains the changes for bug fixes in cluster resource browser merge

fix: Minor fix around tab reset

---

src/components/common/Grid/types.ts
src/components/scopedVariables/SavedVariables.tsx
src/components/scopedVariables/VariablesList.tsx
src/components/scopedVariables/constants.tsx
src/components/scopedVariables/mocks.ts
src/components/scopedVariables/types.tsx
src/css/icons.scss

This PR brings changes to include short description and is-sensitive fields for scoped variables.
The changes are made in the types of the variables and in the variable list component to add a new field for sensitive data.

Fix: scoped variables short description

---

src/components/ResourceBrowser/ResourceList/ResourceList.tsx
src/components/ResourceBrowser/Utils.ts

Fixes #https://github.com/devtron-labs/devtron/issues/3691

fix: remove default from storageclass name

---

src/components/login/SSOLogin.tsx
src/components/login/ssoConfig.types.tsx

fix: OIDC configure id name

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.constants.ts
src/components/v2/values/chartValuesDiff/ChartValuesView.tsx

Added validation for empty yaml states for values (at helm app configure/update) and manifest (at resource browser).

feat: added validation for empty yaml

---

src/components/app/details/appConfig/appConfig.scss

Manually tessted on diff diff apps

fix: app config sidebar UI break

---

src/components/ClusterNodes/NodeDetails.tsx

this PR contains the fix for multiple tab opens on click of node detail pod

fix: Multiple tab opening from node details

---

src/components/v2/appDetails/k8Resource/nodeType/PodHeader.component.tsx

Reset new/old pod count incase of hibernate. 
Previous:
Fixed:

fix: reset pod counts in case of hibernate

---

src/components/charts/ChartGroupUpdate.tsx

fix: Unable to edit chart-group with edit access

---

src/components/userGroups/Group.tsx

bug fix for unable to add config approver role in payload on permission group page

fix: payload to add config approval role in permission grp

---

src/components/common/DeploymentTypeIcon/DeploymentTypeIcon.tsx

Code formatting and refactored the virtual env condition
Deployment Type: Devtron App

chore: code formatting

---

src/components/ResourceBrowser/ResourceList/ResourceList.tsx

Removed virtual environments filter from unnecessary places
This will go along with https://github.com/devtron-labs/devtron/pull/3960

feat: removed unnecessary virtual filter from API response

---

src/components/ApplicationGroup/Constants.ts
src/components/ApplicationGroup/Details/TriggerView/BulkSourceChange.tsx
src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.scss
src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/ApplicationGroup/Details/TriggerView/SourceUpdateResponseModal.tsx
src/components/app/details/triggerView/ciMaterial.tsx
src/components/app/service.ts
src/config/constants.ts

Ability to change branch for all selected applications during bulk build from Application Groups
Fixes https://github.com/devtron-labs/devtron/issues/3887

feat: Ability to change branch for all selected applications during bulk build from Application Groups

---

src/components/userGroups/UserGroup.tsx

The dropdown box is way greater than expected(i.e. inappropriate size). The dropdown box should be of appropriate size.
Fixes https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/5658/

fix: User permission UI break

---

src/components/app/Overview/Overview.tsx
src/components/app/details/appDetails/AppDetails.tsx
src/components/app/details/cdDetails/CDDetails.tsx
src/components/app/details/main.tsx
src/components/app/details/metrics/DeploymentMetrics.tsx
src/components/app/details/metrics/deploymentMetrics.types.ts
src/components/app/types.ts

This PR contains the changes of app environment filter on below Component
1- App details
2- Deployment metrics
3- App overview page
Manually tested by creating multiple envs in same app

feat: Implemented env filter on app details, overview and deployment metrics

---

src/components/app/details/appConfig/AppComposeRouter.tsx
src/components/app/details/appConfig/AppConfig.tsx
src/components/app/details/appConfig/appConfig.type.ts
src/components/app/details/cIDetails/CIDetails.tsx
src/components/app/details/main.tsx
src/components/app/details/triggerView/TriggerView.tsx
src/components/app/details/triggerView/types.ts
src/components/app/details/triggerView/workflow.service.ts
src/components/app/service.ts
src/components/workflowEditor/types.ts
src/components/workflowEditor/workflowEditor.tsx
src/services/service.ts

This PR contains the changes of app environment filter on below Component
1- Build and deploy page
2- build history
Manually tested by creating multiple envs in same app

feat: Env filter build deploy build history

---

src/components/dockerRegistry/Docker.tsx

Fixes https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/5770

fix: oci public validation for Azure & Quay

---

src/components/dockerRegistry/Docker.tsx

Enter any name including / , in the registry name .try to open the registry you created with that name , it won't open.
Fixes https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/5768/

fix: Slash validator

---

src/components/app/details/appConfig/AppConfig.tsx
src/components/app/details/triggerView/types.ts
src/components/app/details/triggerView/workflow.service.ts
src/components/cdPipeline/NewCDPipeline.tsx
src/components/workflowEditor/Workflow.tsx
src/components/workflowEditor/nodes/CDNode.tsx
src/components/workflowEditor/nodes/CINode.tsx
src/components/workflowEditor/nodes/WebhookNode.tsx
src/components/workflowEditor/types.ts
src/components/workflowEditor/workflowEditor.tsx
src/css/base.scss

This PR contains the changes of app environment filter on Workflow editor which includes disabling the he action button validating deletable pipeline
Manually tested by creating multiple envs in same app

feat: Env filter workflow editor

---

src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx
src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/app/details/triggerView/TriggerView.tsx
src/components/app/details/triggerView/cdMaterial.tsx
src/components/app/details/triggerView/types.ts

feat: Image tag search

---

src/components/ClusterNodes/ClusterSelectionList.tsx
src/components/app/details/appConfig/appConfig.scss
src/components/app/list-new/HelmAppList.tsx

Fixes around:
Helm app list last deployed at order
Workflow editor Left sidebar nav UI
Resource broser status

fix: revert fixes

---

package.json

Update fe-common-lib to 0.0.28

fix: add package json for fe-common lib

---

src/components/ApplicationGroup/AppGroup.service.ts
src/components/ApplicationGroup/AppGroup.types.ts
src/components/ApplicationGroup/AppGroupAppFilter.components.tsx
src/components/ApplicationGroup/AppGroupDetailsRoute.tsx
src/components/ApplicationGroup/Constants.ts
src/components/ApplicationGroup/CreateAppGroup.tsx
src/components/app/details/AppHeader.tsx
src/components/app/details/app.scss
src/components/app/details/main.tsx
src/components/workflowEditor/nodes/CDNode.tsx
src/components/workflowEditor/nodes/CINode.tsx
src/components/workflowEditor/nodes/WebhookNode.tsx
src/components/workflowEditor/workflowEditor.tsx

this pr contains the feature to add create filter modal in app details 

Feat: modal app details env filter

---

src/components/ApplicationGroup/AppGroupAppFilter.components.tsx
src/components/ApplicationGroup/CreateAppGroup.tsx

QA bug fixes for app details env filter

fix: app details env filter

---

.github/workflows/pr-issue-validator.yaml

Issue was with \r (new line character) getting appended. Have trimmed that out using tr utility.

chore: Update pr-issue-validator

---

src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/app/details/triggerView/TriggerView.tsx
src/components/app/details/triggerView/cdMaterial.tsx
src/components/app/details/triggerView/types.ts

this pr contains search and refresh functionality for data displayed as shown in the below img.

Feat: search & refresh deployments

---

src/components/app/details/triggerView/cdMaterial.tsx

In case when user has requested approval and block is excluded, then it comes twice, this PR intends to fix that issue.
Fixes https://github.com/devtron-labs/devtron/issues/4010

fix: remove reptition of excluded blocks

---

src/components/ResourceBrowser/ResourceList/ResourceList.tsx
src/config/searchWorker.ts

Cancel API request call when we switch between filtered namespace and sidebar tabs in resource browser

Fix: token cancel on filter

---

package.json

chore: update fe-common version

---

src/components/EnvironmentOverride/EnvironmentOverride.tsx

- Fix the data persistence issue when toggling between the same component across multiple environments in Environment Overrides.
Fixes https://github.com/devtron-labs/devtron/issues/4103

fix: data persistence issue in env overrides

---

src/components/app/details/triggerView/triggerViewConfigDiff/TriggerViewConfigDiff.tsx

fixes(qa) : floating-widget-variable-resolve

---

src/components/app/details/triggerView/cdMaterial.tsx
src/components/app/service.ts

Fixes auto selection of eligible image and empty state action button for no image.

Fix: auto selection of eligible image and empty state action button

---

src/components/CIPipelineN/CustomInputVariableSelect.tsx
src/components/CIPipelineN/InputPluginSelect.tsx
src/components/ConfigMapSecret/Types.ts

Issue with variableType on selected value

fix: Input variable type fix

---

src/components/CIPipelineN/CustomInputVariableSelect.tsx

fix for wrong corresponding task name for a variable
Fixes #4090

fix: wrong task name

---

package.json
src/components/CIPipelineN/ciPipeline.utils.ts
src/components/EnvironmentOverride/EnvironmentOverride.tsx
src/components/common/formFields/ButtonWithLoader.tsx
src/components/hostURL/HostURL.tsx
src/components/project/Project.tsx
src/components/userGroups/AppPermissions.tsx
yarn.lock

Fixes [# (issue)](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/6012)

fix: pre/post CI/CD, Preset plugin input variable got invisible after adding as condition fix

---

src/components/app/details/triggerView/cdMaterial.tsx

The deploy button was not getting enabled in cd pipeline when approved image is selected
Fixes #4122

fix: deploy button disabled in cd

---

src/components/ConfigMapSecret/ConfigMap/ConfigMapList.tsx
src/components/EnvironmentOverride/DeploymentTemplateOverride.tsx
src/components/app/details/appDetails/AppDetails.tsx
src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx

This PR contains the changes of the bug i.e. App details page showing incorrect pod's details. Changed the react state intervalID to js variable
Fixes #4119
Manually tested it for multiple apps on local

fix: App details page showing incorrect pod's details

---

src/components/CIPipelineN/CustomInputOutputVariables.tsx

bug fix for unwanted behaviour when adding input variable.
Fixes #4090

fix: input var bugs

---

src/components/app/details/triggerView/triggerViewConfigDiff/TriggerViewConfigDiff.tsx

fix: pg crash when new app undeployed

---

src/components/app/Overview/Overview.scss
src/components/app/Overview/Overview.tsx
src/components/app/Overview/TagChipsContainer.tsx
src/components/app/types.ts
src/css/formulae.scss

- Update the UI for the sidebar
- Move the Tags to the sidebar
- Add the overflow handling for the tags

feat: update the ui for overview sidebar for jobs and applications

---

src/assets/icons/ic-activity.svg
src/components/app/AppStatus.tsx
src/components/app/Overview/Overview.scss
src/components/app/Overview/Overview.tsx
src/components/app/Overview/TagChipsContainer.tsx
src/components/app/types.ts
src/config/constantMessaging.ts
src/config/constants.ts
src/css/base.scss
src/css/formulae.scss

- Add the tabs on Overview for Applications and Jobs
- This depends on https://github.com/devtron-labs/devtron-fe-common-lib/pull/41

feat: add the tabs for Application and Jobs

---

src/components/cluster/Cluster.tsx

Added null check for few properties which were being used in enterprise but not in oss which led to page breaking in oss
Fixes #4182

fix: added null check

---

public/index.html
src/components/ClusterNodes/ClusterOverview.tsx
src/components/ResourceBrowser/ResourceList/ResourceList.tsx
src/components/app/Overview/Overview.scss
src/components/app/Overview/Overview.tsx
src/components/app/create/CreateApp.tsx
src/components/app/create/validationRules.ts
src/components/app/types.ts
src/components/common/Description/GenericDescription.tsx
src/components/common/EditableTextArea/EditableTextArea.tsx
src/components/common/EditableTextArea/types.ts
src/config/constantMessaging.ts
src/css/base.scss
src/css/formulae.scss

fix: Overview revamp uat fixes

---

src/components/ClusterNodes/ClusterOverview.tsx
src/components/app/Overview/Overview.tsx
src/components/app/Overview/utils.tsx
src/components/app/types.ts
src/components/common/EditableTextArea/EditableTextArea.tsx
src/components/common/EditableTextArea/types.ts

- Integrate code source for Devtron App
- Add placeholder for description and improve the handling of empty state
- Re-fetch the app meta data configuration on tab back switch

feat: integrate code source and placeholder for description

---

src/components/ClusterNodes/ClusterOverview.tsx
src/components/app/Overview/Overview.scss
src/components/app/Overview/Overview.tsx
src/components/app/create/CreateApp.tsx
src/css/base.scss

- Fix tab max-width on the overview page
- Show the description error state on change
- Improve the dimensions for helm chart image on Overview page

fix: tab max width, error state on change, chart image dimentsions

---

src/components/ClusterNodes/ClusterSelectionList.tsx
src/components/ClusterNodes/clusterNodes.scss
src/components/ResourceBrowser/ResourceList/ResourceList.tsx
src/components/ResourceBrowser/Types.ts
src/components/common/DynamicTabs/useTabs.ts
src/components/v2/appDetails/appDetails.type.ts
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Terminal.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/nodeDetailTab.scss
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/Terminal.tsx

Fixes bugs and edge-cases related to the new implementation of retaining cluster terminal sessions.
Note - 
1. This PR also contains some minor refactor code in `ResourceList` component and `useTabs` hook.
Fixes #1422

fix: Bugs and edge cases related to implementation of retaining cluster terminal sessions

---

src/components/ClusterNodes/ClusterOverview.tsx
src/components/ClusterNodes/constants.ts
src/components/ResourceBrowser/ResourceList/ConnectingToClusterState.tsx
src/components/ResourceBrowser/ResourceList/ResourceList.tsx

UAT fixes in cluster overview in resource browser

fix: uat fixes in cluster overview

---

package.json
src/components/app/Overview/EnvironmentList.tsx
src/components/app/Overview/Overview.scss
src/components/app/Overview/Overview.tsx
src/services/service.types.ts

- Add docker icon in image
- Update the font family
- Update the hyper link URL for deployment history

fix: uat enhancements in environments list

---

src/components/app/details/cicdHistory/TriggerDetails.tsx

trimmed deployment history message.

deployment history message truncate

---

src/components/app/Overview/Overview.tsx

fix: url fix for job pipeline

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx

fix: pod terminal tab getting stuck

---

src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx
src/components/app/details/triggerView/cdMaterial.tsx

Added a banner for bulk CD deployment

feat: bulk cd banner

---

package.json
src/components/app/Overview/EnvironmentList.tsx
src/components/app/Overview/Overview.tsx
src/config/constants.ts

- Add dependency tab on app overview

feat: add dependency tab on app overview

---

src/components/app/Overview/Overview.tsx
src/components/app/Overview/constants.ts
src/config/constants.ts

- Update the overview tabs using search params

feat: update overview tabs using search params

---

src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx

Showing warning in case of security in bulk cd.

fix: bulk security warning

---

src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx
src/components/app/details/triggerView/cdMaterial.tsx

Fixes messaging in case of no image in bulk cd deployment.

fix: handle bulk no artifact

---

src/components/ResourceBrowser/ResourceList/ResourceList.tsx
src/components/v2/appDetails/k8Resource/NodeTreeTabList.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.util.ts

change default opt of pods in log analyser to first pod in individual pods 
Fixes #4222

fix: change default opt

---

package.json
src/components/common/RJSF/Form.tsx
src/components/common/RJSF/config.ts
src/components/common/RJSF/constants.ts
src/components/common/RJSF/index.ts
src/components/common/RJSF/rjsfForm.scss
src/components/common/RJSF/templates/BaseInput.tsx
src/components/common/RJSF/templates/Field.tsx
src/components/common/RJSF/templates/TitleField.tsx
src/components/common/RJSF/templates/index.ts
src/components/common/RJSF/widgets/Checkbox.tsx
src/components/common/RJSF/widgets/Select.tsx
src/components/common/RJSF/widgets/index.ts
src/message.json

feat: add support for rjsf

---

src/components/common/FloatingVariablesSuggestions/SuggestionItem.tsx

Handle word break on scoped variables tippy

fix: handle word-break for scoped variables tippy

---

package.json
src/components/ClusterNodes/ClusterOverview.tsx
src/components/app/Overview/Overview.scss
src/components/app/Overview/Overview.tsx
src/components/app/Overview/constants.ts

- update common lib, fix styling issue on apps

feat: update common lib, fix styling issue on apps

---

src/components/common/FloatingVariablesSuggestions/SuggestionItem.tsx

Earlier the tooltip was not handled as per proper UX for scoped variables, this PR intends to fix this by making it scrollable with max height 140px.
Fixes https://github.com/devtron-labs/devtron/issues/4272
UAT

fix: style for scoped variable tippy

---

src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx

The payload to change branch in env trigger used to contain invalid types like LinkedCI, Webhook, etc. Blocking them by filtering the data.

fix: restrict change branch

---

package.json
src/components/ClusterNodes/ClusterOverview.tsx
src/components/app/Overview/Overview.tsx
src/css/base.scss

- Add support for non-object catalog UI
- Handle null state for field label in Read only View and Form
- Handle UI issues with array type field

add support for non object catalog ui and handle null state for field label

---

src/components/app/details/appDetails/AppDetails.tsx
src/components/app/details/appDetails/AppMetrics.tsx
src/components/app/details/appDetails/AppStatusCard.tsx
src/components/app/details/appDetails/DeployedCommitCard.tsx
src/components/app/details/appDetails/DeploymentStatusCard.tsx
src/components/app/details/appDetails/IssuesCard.tsx
src/components/app/details/appDetails/SourceInfo.tsx
src/components/app/details/appDetails/appDetails.scss
src/components/v2/appDetails/AppDetails.component.tsx
src/components/v2/appDetails/appDetails.scss
src/components/v2/appDetails/k8Resource/NodeTreeTabList.scss
src/components/v2/appDetails/sourceInfo/environmentStatus/ChartUsedCard.tsx
src/components/v2/appDetails/sourceInfo/environmentStatus/EnvironmentStatus.component.tsx
src/components/v2/appDetails/sourceInfo/environmentStatus/HelmAppConfigApplyStatusCard.tsx
src/components/v2/appDetails/sourceInfo/environmentStatus/environmentStatus.scss

- Fix some style discrepancies for the app details cards
- Remove the Commit Info button from the App details page(as new Commit card has been added as part of main pr for these app details cards feature)

fix: UAT fixed for app details cards

---

src/components/app/Overview/Overview.tsx

- Update the dependencies list

feat: update the dependencies list

---

src/components/ApplicationGroup/AppGroup.service.ts
src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx

Fix for empty state not coming in app group in case of no workflows
Fixes #1516

fix:App group empty state handled

---

src/components/CIPipelineN/Build.tsx
src/components/app/details/triggerView/BranchRegexModal.tsx
src/components/cdPipeline/BuildCD.tsx
src/components/cdPipeline/CDPipeline.tsx
src/components/ciConfig/CICreateDockerfileOption.tsx
src/components/ciConfig/CIDockerFileConfig.tsx
src/components/ciPipeline/LinkedCIPipelineEdit.tsx
src/components/ciPipeline/LinkedCIPipelineView.tsx
src/components/ciPipeline/WebhookSelectorCondition.tsx
src/config/constantMessaging.ts
src/css/base.scss

Custom input bug fixes
Fixes [#7450](https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/OSS%20adoption/Stories/?workitem=7450)

feat: Custom input bug fixes

---

src/components/app/details/cicdHistory/History.components.tsx

fix: Missing source data in Webhook

---

src/components/app/details/appDetails/utils.tsx

fix: move the condition to add success where for argoCD sync if kubectl apply is there

fix: legacy deployments argo cd timeline status
