src/assets/icons/ic-checkbox-unselected.svg
src/components/chartRepo/ChartRepo.tsx
src/components/ciConfig/CIConfig.scss
src/components/ciConfig/CIConfig.tsx
src/components/cluster/Cluster.tsx
src/components/gitOps/GitOpsConfiguration.tsx
src/components/gitProvider/GitProvider.tsx
src/components/material/CreateMaterial.tsx
src/components/material/MaterialList.tsx
src/components/material/MaterialView.tsx
src/components/material/UpdateMaterial.tsx
src/components/material/material.css
src/components/material/material.types.ts
src/components/workflowEditor/workflowEditor.css
src/config/constants.tsx
src/css/forms.scss

Simplifying Git Material and Docker Build Config in `Applications >App configurations`
1.  Earlier all the fields in `Git Material` and `Docker Build Configuration`  were in the exposed state. It was difficult for the users to get to know about the required fields.
2. Recently we allowed directing the user's attention to a particular field in the form rather than looking at everything.
Please give examples of your use case, e.g. when would you use this.
This will be helpful while creating an application in the `App Configuration` tab. Users will not be required to brainstorm in any non-required field.
How do you think this should be implemented?
1. Exposing only basic Fields in front.
2. Grouped fields with appropriate headers.
Please describe the tests that you ran to verify your …

App config

---

src/components/app/details/appDetails/utils.tsx

Parsing of k8sVersion="v1.15.12-eks-31566f" was not supported. 
Test the grafana url of the following graphs:
App details
Graphs Modal

Added handling of k8sVersion format

---

src/components/ciConfig/CIConfig.tsx

1. Currently While configuring Docker Build Config (/app/<id>/edit/docker-build-config),  validation prompt that the Docker repository is a required field.
2. fixed: Docker repository field be optional so that a new repo can be created if it is left blank. 
https://github.com/devtron-labs/devtron/issues/392
-  [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

bug on docker repo

---

src/components/EnvironmentOverride/ConfigMapOverrides.tsx
src/components/EnvironmentOverride/SecretOverrides.tsx
src/components/app/details/appDetails/utils.tsx
src/components/common/helpers/compareVersion.ts
src/components/common/index.ts
src/components/configMaps/ConfigMap.tsx
src/components/deploymentConfig/DeploymentConfig.tsx
src/components/deploymentConfig/service.tsx
src/components/secrets/Secret.tsx
src/services/service.ts

Subpath and file permission were not required for chart versions 3.9.0 and below.
Configmap, Secrets and Environment Overrides have been tested for:

Handling subpath and file permission on configmap, secrets and env overrides for chart version 3.9.0 and below

---

src/components/userGroups/Group.tsx
src/components/userGroups/User.tsx
src/components/userGroups/UserGroup.tsx

Fixes devtron-labs/devtron#411
This PR also fixes issue 2 in devtron-labs/devtron#410 partially.
Toast messages on following actions has been tested:
User list
Group list

Issue #410 and #411. User Access Behaviour Fixed

---

src/components/app/ResourceTreeNodes.tsx
src/components/cdPipeline/CDPipeline.tsx
src/components/charts/modal/DeployChart.tsx
src/components/common/helpers/util.ts
src/components/globalConfigurations/GlobalConfiguration.tsx
src/components/userGroups/User.tsx
src/components/userGroups/UserGroup.tsx
src/components/userGroups/userGroups.types.ts

- Project and Environment dropdown is now typeahead.
- Option are sorted and are searchable.
- Muti-value string is now supported in email address typeahead.
- Resource deletion button label changed to `Delete`
- CD Pipeline update environment selection disabled on update
Fixes (https://github.com/devtron-labs/devtron/issues/479)
Fixes (https://github.com/devtron-labs/devtron/issues/485)

Typeahead support multiple values; 2 dropdowns on deploy chart changed to typeahead

---

src/components/charts/ChartGroupUpdate.tsx
src/components/charts/list/DiscoverCharts.tsx
src/components/charts/useChartGroup.ts

Not Showing deprecated charts In `chart group` section of `Charts`
Fixes: https://github.com/devtron-labs/dashboard/issues/129

[FIX] deprecated charts not visible  in chart group

---

src/components/login/SSOLogin.tsx
src/config/constants.ts

To Add SSO login Link 
Fixes https://github.com/devtron-labs/devtron/issues/658

[SSO LOGIN] added sso link

---

src/components/common/helpers/Helpers.tsx
src/components/dockerRegistry/Docker.tsx
src/components/globalConfigurations/globalConfigurations.scss
src/css/formulae.scss

docker-registry connection option integratio
n
Fixes: https://github.com/devtron-labs/devtron/issues/764

FIX: Advanced Registry URL connection options

---

src/components/EnvironmentOverride/ConfigMapOverrides.tsx
src/components/EnvironmentOverride/SecretOverrides.tsx
src/components/common/helpers/compareVersion.ts
src/components/configMaps/ConfigMap.tsx
src/components/secrets/Secret.tsx
src/services/service.ts

Chart version comparision inside configmap and secret override happens agains the chart version selected in the global deployment template and not against the chart version selected for this particular environment.
Fixes: devtron-labs/devtron#936
User selects chart version less than 3.9 in global deployment template
User changes the chart version in the deployment template for a particular environment to a number higher than 3.9
User tries to use subpath functionality of configmap
User should be able to use subpath

fix: fixed the chartversion for override

---

src/components/charts/modal/DeployChart.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
src/components/v2/values/DeployChart.tsx

Bugs reproduced by Shubham:
1. (7) In the case of 2 tabs for different pods, can select only one(In case of logs only). Switching from logs to other elements is applied on another tab.
2. (11) Just after deploying any chart, the app details page comes up with (deployed/ <chart-name>) Redirects to wrong URL (previous URL)
3. (13) After deleting a chart, it should redirect to Helm Apps. Currently redirecting to chart-store
4. (14) Position of "Manifest/Events not available" should be in the center.

External app support shu1

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx

autoselect container when option has only one container.

handle single container case

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Terminal.component.tsx

Fix: React select Dropdown,  tick on selected  container and pods is missing in terminal

Terminal react select UI fix

---

src/components/app/list-new/AppList.tsx

Devtron app list and Helm app list - After page load, if I click on sort icon, then first time it doesn't sort, second time onwards it works (as first time, there is no sortOrder in query param)

sorting fix for app list

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx

Fix for state issue when switching tabs between deployment & pod and then log analyzer & k8s resources. 
- Case 1: logs & terminal tabs are not visible for Pod when switching from the active Deployment tab
- Case 2: logs & terminal tabs are visible for Deployment when switching from the active Pod tab

EA: Internal Tabs - fix for state issue when switching internal tabs

---

src/components/v2/appDetails/appDetails.scss
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Events.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
src/config/constants.ts

1. When a user clicks on [apply changes] show loader with the text "Applying changes" instead of "Fetching manifest", some more cases around manifests.
2. K8 resources and log analyzer icon color should be --B500 while hovering over resp. tabs (icon blue on hover)
3. Capitalise events header
4. Height is not covering the full length in No Pod container view
5. Removing extra slash from getVersion API request URL
Fixes - devtron-labs/devtron#1157

fix: Some bug fixes

---

src/components/common/icons/Progressing.tsx
src/components/external-apps/ExternalAppService.ts
src/components/v2/common/message.ui.tsx
src/components/v2/deployment-history/ea/EADeploymentHistory.component.tsx
src/components/v2/deployment-history/ea/ea-deployment-history.scss
src/config/constants.ts
src/css/base.scss

Breakdown deployment history API to solve grpc max size error.
- Fetching YAMLs lazily instead of on page load using new API - `application/deployment-detail`.
- Updates in deployment tabs - added `values.yaml` & renamed `Applied YAML` to `Helm generated manifest`.
- Added error handling view containing CTA - 'Retry'.
Fixes # https://github.com/devtron-labs/devtron/issues/1155
All tests have been performed manually on the local server.

Feature: Deployment History - fetching YAMLs lazily using new API

---

src/components/app/list-new/AppList.tsx

For Hyperion mode, If there is only one cluster, then that cluster would be auto selected on app list. For that case namespace filter dropdown is empty.

namespace dropdown data issue fix if single cluster for EA_ONLY mode

---

src/components/CodeEditor/CodeEditor.tsx
src/components/EnvironmentOverride/ConfigMapOverrides.tsx
src/components/EnvironmentOverride/DeploymentTemplateOverride.tsx
src/components/cdPipeline/CDPipeline.tsx
src/components/common/helpers/Helpers.tsx
src/components/configMaps/ConfigMap.tsx

Indentation issues in Code editor in EA app detail - add 2 tab sizes/spaces in both read-only & edit mode
Fixes # https://github.com/devtron-labs/devtron/issues/1201
All changes have been tested manually.
- By loading different views/sections/components and manually checked & confirmed that editors using YAML mode/type are using tab size/space as 2. 
- Different components and their props are mentioned in this doc - [CodeEditor](https://docs.google.com/spreadsheets/d/1b2CrdOE51kGKCJodyxk74BZagSwq_5D4kpZMDLJ8HyM/edit?usp=sharing)

enhancement: CodeEditor - setting indentation to 2 spaces for YAML

---

src/components/common/dialogs/DeleteDialog.tsx
src/components/v2/appDetails/index.store.ts
src/components/v2/values/ChartValues.component.tsx
src/components/v2/values/DeployChart.tsx

Force delete modal on helm chart was  disabled
Fixes: https://github.com/devtron-labs/devtron/issues/1301

[FIX]: Force delete helm bug

---

src/components/gitOps/GitOpsConfiguration.tsx

Updated messaging for adding GitOps credentials. Users can now use their code repository as GitOps repo. A prefix can be added in the GitOps repo created by devtron automatically.

Updated messaging for adding GitOps credentials

---

src/components/v2/appDetails/k8Resource/nodeType/NodeTree.component.tsx

Currently, the user is not able to navigate back to Helm Apps from AppDetails using the browser's back button. This change fixes this issue by using the `replace` function from history instead of `push`.
Fixes # https://github.com/devtron-labs/devtron/issues/1282
All tests have been performed manually by visiting AppDetails from HelmApps and switching between sub URLs. Then trying to go back to HelmApps using the browser's back button.

Fix - Routing issue fix - Not able to go back to helm-apps from app-details

---

src/components/charts/ChartGroupUpdate.tsx
src/components/charts/list/Deployed.tsx
src/components/charts/list/DiscoverCharts.tsx
src/components/common/emptyState/ChartEmptyState.tsx
src/setupProxy.js

1. Earlier in case, no chart is available,  there was wrong messaging in empty state
2. Currently replaced earlier message with the image given below
Fixes https://github.com/devtron-labs/devtron/issues/1307

Empty chart has wrong messaging

---

src/components/charts/AdvancedConfig.tsx
src/components/charts/ChartGroupAdvanceDeploy.tsx
src/components/charts/charts.css
src/components/charts/list/DiscoverCharts.tsx

In Discover, The size of the error icon is larger than it should be.
Fixes # https://github.com/devtron-labs/devtron/issues/1280
All changes have been tested manually.

Warning icon size in charts discover

---

src/components/CodeEditor/CodeEditor.tsx
src/components/EnvironmentOverride/DeploymentTemplateOverride.tsx
src/components/charts/AdvancedConfig.tsx
src/components/deploymentConfig/DeploymentConfig.tsx
src/components/deploymentConfig/ReadmeConfig.tsx
src/components/deploymentConfig/deploymentConfig.scss
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx

Currently, the code editor height in the readme modal is fixed to a numeric value. We need to make the code-editor height dynamic based on available screen size.
Fixes # https://github.com/devtron-labs/devtron/issues/1318

Some CSS and code editor changes

---

src/components/chartRepo/ChartRepo.tsx
src/components/charts/modal/DeployChart.scss
src/components/charts/util/ChartValueSelect.tsx
src/components/common/dialogs/DeleteDialog.tsx
src/components/external-apps/ExternalAppService.ts
src/components/v2/common/message.ui.tsx
src/components/v2/values/DeployChart.tsx
src/components/v2/values/common/ChartValuesSelectors.tsx
src/components/v2/values/common/ReadmeColumn.component.tsx
src/components/v2/values/common/chartValues.api.ts
src/components/v2/values/common/chartValuesSelectors.type.ts
src/components/v2/values/ea/EAValues.component.tsx
src/config/constants.ts
src/css/base.scss

Currently, when a chart is an external chart deployed through helm install, it's giving an error on updating.
E.g. Chart name: bitnami/apache
To address this one of the proposed solutions is to put a check on UI whether is external or internal. If it is external then ask for linking (repo/version/chart/values) etc.. and save it in DB using updated/new APIs covered under - [#1270](https://github.com/devtron-labs/devtron/issues/1270).
It also contains a fix for the README bug. For the selected chart; currently, it shows Readme for the chart used for deployment, not the one selected. And updated the toast message on successfully adding the chart repo.
Fixes # https://github.com/devtron-labs/devtron/issues/1339
All tests have been performed manually. Ref - [Test Cases - …

Enhancements: UX/UI Changes for handling error on chart updation if chart is deployed from terminal

---

src/components/ciPipeline/CIPipeline.tsx

Line break issue in monaco editor in windows system.
Replaced '\n\r' to '\n' at the time of saving the config

FIX: Crlf to lf replace in pre/post script

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
src/components/v2/common/ReactSelect.utils.tsx
src/css/base.scss

Add grouping labels to differentiate between all pods for group & individual pods. Also, show tippy on hover containing the full name of the pod or pod group.
Fixes - https://github.com/devtron-labs/devtron/issues/1439

Tippy & Group label for log analyzer

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
src/components/v2/common/ReactSelect.utils.tsx

Added margin tippy on hover containing the full name of the pod or pod group based on scroller.
Fixes - https://github.com/devtron-labs/devtron/issues/1439

Enhancement - added margin based on scroller

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
src/components/v2/common/ReactSelect.utils.tsx

Pod grouping labels & tippy was added as part of https://github.com/devtron-labs/devtron/issues/1439. However, there's some extra spacing between dropdown & tippy. These changes will fix this issue.
Fixes # https://github.com/devtron-labs/devtron/issues/1463
All tests have been performed manually. The following are the steps, 
1. Go to Applications > Select Helm apps tab
2. Select any app > it'll redirect to the App Details page (Make sure the app has more than 6 pods)
3. Select the Log Analyzer tab
4. Click on Pods dropdown
5. Hover on any item
6. Observe
It should have less margin/spacing between dropdown & tippy similar to Pods dropdown having less than 6 pods.

Fix: Removed margin to fix tippy extra space issue

---

src/components/app/grepSSEworker.ts
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx

Currently, when trying to use grep in logs search with terms containing double quotes ("") or spaces, it's not working as expected. These changes will fix the issues.
Fixes # https://github.com/devtron-labs/devtron/issues/1389
1. Go to Applications > Select Helm apps tab
2. Select any app > it'll redirect to the App Details page
3. Select the Log Analyzer tab or open the logs tab for any specific pod.
4. Search logs with & without terms containing double quotes or containing spaces (/multiple words). **E.g.** grep Error, grep "Error" or grep "Service Error"
5. Observe
**Expected**: It should search & show logs for the searched terms containing double quotes or spaces.

Fix: Grep is not working with double quotes issue fix

---

src/components/v2/chartDeploymentHistory/ChartDeploymentHistory.component.tsx
src/components/v2/chartDeploymentHistory/chartDeploymentHistory.service.ts
src/config/constants.ts

Changes include integration of refactored/merged APIs for deployment history & roll back on the deployment history page instead of using different APIs for external & Devtron charts.
Fixes # https://github.com/devtron-labs/devtron/issues/1421
1. Case #1 - 
- Go to Applications > select Helm Apps tab
- Select cluster from the cluster filter in which the app is installed
- Select app > it’ll redirect to the AppDetails page
- Select the Deployment history tab
- Observe
2. Case #2 - values.yaml & helm generated manifest (for EA)
- Go to Applications > select Helm Apps tab
- Select cluster from the cluster filter in which the app is installed
- Select app > it’ll redirect to the AppDetails page
- Select the Deployment history tab
- Go to the desired …

Enhancement: Deployment History - Integrated merged APIs for history & rollback

---

src/components/CodeEditor/CodeEditor.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
src/util/Util.ts

Changes to remove some autogenerated fields from manifest while comparing in app detail.
Fixes # https://github.com/devtron-labs/devtron/issues/1497
Compare manifest on app detail.

Enhancement: cleaning kube manifest while comparing

---

src/components/cluster/cluster.type.ts
src/components/dockerRegistry/Docker.tsx
src/css/forms.scss

Enabled authentication type options for ECR registry type in global configuration. Available options will be,
- EC2 IAM Role **(default)** - if selected, it'll use the IAM role
- User auth - if selected, need to provide secrets to be used manually
Fixes # https://github.com/devtron-labs/devtron/issues/1509
All tests have been performed manually. 
1. Go to Global configurations
2. Go to Container registries
3. Add a new registry of type ECR or try updating the existing ECR registry
4. Observe
**Expected:** 
- It should show available `Authentication type` options
- `EC2 IAM Role` should be the default for adding a new registry & should not show account secrets inputs.
- For the existing, the registry can be switched to` EC2 IAM Role` from `User auth`
- It should successfully save the …

Enhancement: Container registries -  enabled authentication type options for ECR

---

src/components/v2/appDetails/k8Resource/nodeType/NodeDelete.component.tsx

View events and View container logs are not redirecting to the events and logs tab.
Fixes # https://github.com/devtron-labs/devtron/issues/1512
All tests have been performed manually. The following are the steps,
1. Go to Applications > Select Helm apps tab
2. Select any app > it'll redirect to the App Details page > Pods
3. Select the three-dot menu on the right of the individual pod
4. Click on view event or view container log
5. Observe
**Expected behavior**
It should have redirected the user to the event/log tab
**Screenshots**

Fixed broken view events & logs in Helm App detail

---

src/components/app/ResourceTreeNodes.tsx

On the Devtron app's AppDetails page, the `Ready` column header is misaligned and displayed over more options under NodeDetails when no external links are configured. These changes will fix this issue.
Fixes # https://github.com/devtron-labs/devtron/issues/1560
1. Make sure no external links are configured
2. Go to the Devtron app's AppDetails page
3. Scroll to node details for Pods
4. Observe
**Expected**: It should show the `Ready` column header over the count
1. Make sure pod level external links are configured
2. Go to the Devtron app's AppDetails page
3. Scroll to node details for Pods
4. Observe
**Expected**: It should show the `Ready` column header over the count

Fix - Ready column header is misaligned in NodeDetails issue

---

src/components/v2/appDetails/index.store.ts

Dropdown is missing for containers under pods for 30 sec
Fixes  - https://github.com/devtron-labs/devtron/issues/1575

Fixed dropdown is not visible for container in pods

---

src/components/app/details/appDetails/AppDetails.tsx
src/components/app/details/appDetails/appDetails.scss
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/CopyToast.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/LogViewer.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/Terminal.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/terminal.css

Terminal and log div is not taking dynamic height & not acquiring full height of view
Fixes - https://github.com/devtron-labs/devtron/issues/1668
**Describe the bug**
Terminal and log div is not taking dynamic height & not acquiring full height of view 
**To Reproduce**
1. User goes to devtron apps or helm apps 
2. User selects pods & select terminal or logs
3. Terminal and logs is not taking full height
**Expected behavior**
Terminal and logs should take full available height
**Current behavior** 
Terminal and logs is not taking full height
**Screenshots**

Fixed static height of Logs & terminal

---

src/components/CIPipelineN/ConditionContainer.tsx
src/components/CIPipelineN/CustomInputVariableSelect.tsx
src/components/CIPipelineN/TaskTypeDetailComponent.tsx
src/components/ciConfig/CIConfig.tsx
src/components/dockerRegistry/Docker.tsx
src/components/hyperion/EnvironmentSelect.tsx
src/components/material/MaterialView.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Terminal.component.tsx
src/components/v2/common/ReactSelect.utils.tsx

Text inside react - select is align to right
Fixes - https://github.com/devtron-labs/devtron/issues/1721

React-select right align fix

---

src/components/externalLinks/ExternalLinks.utils.ts
src/components/v2/appDetails/ea/EAAppDetail.component.tsx

These changes fix the issue when any key ({namespace}, {containerName}, etc. ) in an external link is used two or more times causing the URL/link to be not generated.
Fixes # https://github.com/devtron-labs/devtron/issues/1752
Tests have been performed manually,
1. Go to Global configurations
2. Go to the External Link section
3. Add new link as - https://devtron.info/grafana/{containerName}/test/{containerName}
4. Go to the AppDetails page
5. Observe the app level external link section
**Expected behavior**
It should generate the proper link even when the same key is used multiple times.

Fix - External link is not generated properly when same key is used multiple times

---

src/components/secrets/Secret.tsx

User is unable to save 'Secret/Secret Override' when Set SubPath is checked
Added check of subpath for Kubernetes External Secret only

Secret/Secret Override issue fix

---

src/components/globalConfigurations/GlobalConfiguration.tsx

Removed Custom charts option from EA_ONLY mode
Custom is available in EA_ONLY mode. which is not required there
Adde check for Custom chart

Removed Custom charts option from EA_ONLY mode

---

src/components/gitOps/GitOpsConfiguration.tsx
src/components/gitOps/gitops.type.ts
src/components/userGroups/User.tsx
src/components/userGroups/UserGroup.tsx

Saving GitOps in global configurations, if we only try to Validate, it also shows that it's trying to save too but at backend, it doesn't save which is confusing for the users | In usergroup select option remains at same position after scrolling page & Project select should show normal select interface instead of checkbox
Fixes - https://github.com/devtron-labs/devtron/issues/1592
**Describe the bug**
When saving GitOps in global configurations, if we only try to Validate, it also shows that it's trying to save too but at backend it doesn't save which is confusing for the users
**To Reproduce**
1. Setup a new devtron with cicd module
2. In global configuration, enter gitops credentials and instead of saving - Click `Validate`
3. On UI it also shows that configurations are being Saved as …

Fixed gitops-validation & usergroup select scroll issue

---

src/components/v2/chartDeploymentHistory/ChartDeploymentHistory.component.tsx
src/components/v2/chartDeploymentHistory/DockerListModal.tsx
src/components/v2/chartDeploymentHistory/chartDeploymentHistory.scss

In helm deployment history page breaks in case of too many image tags. So, adding popup tab to view all images with data
Fixes - https://github.com/devtron-labs/devtron/issues/2037

Added tab to show history image tags

---

src/assets/icons/ic-note.svg
src/components/v2/devtronStackManager/AboutDevtronView.scss
src/components/v2/devtronStackManager/AboutDevtronView.tsx
src/components/v2/devtronStackManager/DevtronStackManager.component.tsx
src/components/v2/devtronStackManager/DevtronStackManager.tsx
src/components/v2/devtronStackManager/DevtronStackManager.type.ts
src/config/constants.ts

Show Prerequisite modal before upgrade to new version, So that it is upfront visible to the user and don't get overlooked
* Show a prerequisite box separately below the install button
* Show a prerequisite modal on click of install button
* Proceed further only when user provides confirmation
Fixes # [(issue)](https://github.com/devtron-labs/dashboard/issues/450)

Added confirmation popup on release notes

---

src/components/app/details/appDetails/AppDetails.tsx
src/components/app/details/appDetails/AppMetrics.tsx
src/components/app/details/cIDetails/CIDetails.tsx
src/components/app/details/cdDetails/CDDetails.tsx
src/components/app/details/cdDetails/deploymentHistoryDiff/DeploymentHistoryConfigList.component.tsx

1. If application metrics not available then the card should be in a collapsed state
2. Build history: Page reloads when scrolling to bottom of build history list
3. Tab selection should retain the selection & No loader present when loading tab in deployment history
Fixes - https://github.com/devtron-labs/devtron/issues/2039, https://github.com/devtron-labs/devtron/issues/2040, https://github.com/devtron-labs/devtron/issues/2042

App metrics collapse | Build history page reload | Deployment history show loader

---

src/components/userGroups/AppPermissions.tsx
src/components/userGroups/UserGroup.tsx

These changes will address the issue where on the user permissions page, when a logged-in user doesn't have access to a certain project (E.g. dev-test) and tries to access a specific user who has access to it then NaN is being passed as teamId to the API causing the API to fail & isn't loading the projects/permissions list.
Fixes https://github.com/devtron-labs/devtron/issues/2142
All tests have been performed manually. The following are the steps,
1. Go to User Permissions on Global Configurations
2. Try to access another user which has access to a certain project but you (logged in) don't.
3. Open the network tab under developer tools
4. Observe
**Expected:**  It should not pass NaN as teamId to API & load the projects that the logged-in user has access to.

Fix - NaN is being passed issue

---

src/components/cluster/Cluster.tsx
src/components/userGroups/User.tsx

1. Toast when the user forgot to submit an email in user permission
2. Close the delete popup modal when the user delete the cluster
Fixes - https://github.com/devtron-labs/devtron/issues/2115, https://github.com/devtron-labs/devtron/issues/2116
Testing has been done manually

Added toast for gmail | Fixed delete popup remain after deletion

---

src/components/app/details/appDetails/AppDetails.tsx
src/components/app/details/appDetails/AppMetrics.tsx
src/components/app/details/appDetails/SourceInfo.tsx
src/components/app/details/appDetails/appDetails.scss
src/components/app/details/appDetails/utils.tsx

1. Throughput and Latency (99%) Metrics graph text overlay is clipped from bottom.
2. Error text take width more than full screen in app details page
Fixes - https://github.com/devtron-labs/devtron/issues/2124
**Describe the bug**
1. Throughput and Latency Metrics graph text overlay is clipped from bottom.
2. If error text length is more in that case the screen have more horizonatal length than screen inn app details page
**To Reproduce**
1. Enable App metrics
**Expected behavior**
1. Text should not be clipped
2. Error text should show some fixed length
**Current behavior** 
Text is clipped from the bottom
**Screenshots**

Fixed UI bug in app metrics | Fixed width bug in app details error

---

src/components/app/details/triggerView/cdMaterial.tsx
src/components/app/details/triggerView/types.ts
src/components/deploymentGroups/DeploymentGroupList.tsx
src/components/deploymentGroups/service.ts

These changes will fix the page break issue on clicking show source info while triggering deployment via deployment groups
Fixes - AB#215
All tests have been performed manually. Now, it's loading source info as expected.

Fix - Deployment groups: Page breaks on clicking on Show source info

---

src/components/app/details/appDetails/AppDetails.tsx
src/components/app/details/appDetails/SourceInfo.tsx
src/css/base.scss

These changes will fix the flow for the Scale pod to 0 option for helm type Devtron apps & move the app to hibernate state as expected
Fixes - [AB#646](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/646)
1. Create a new or go to an existing helm type Devtron app
2. Click on Scale pods to 0
3. Click hibernate app button
4. Observe
**Expected:** It should start scaling down the pod to 0 & move the app to hibernate state

Fix - Hibernating helm type devtron apps

---

src/components/CIPipelineN/CIPipeline.tsx
src/components/cdPipeline/CDPipeline.tsx
src/components/ciPipeline/ExternalCIPipeline.tsx
src/components/ciPipeline/LinkedCIPipelineEdit.tsx
src/components/ciPipeline/LinkedCIPipelineView.tsx

Escape Key to close modals in Workflow editor - Devtron UI
Fixes https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/Devtron%20Team/Issues
Fix https://github.com/devtron-labs/devtron/issues/2414

ci workflow esacpe fixed

---

src/components/CIPipelineN/CIPipeline.tsx

Not able to enter a custom value in the "Container-Image" field in pre/post CI tasks.
Solution: CI pipeline escape functionality removed
Fixes https://github.com/devtron-labs/devtron/issues/2472
Fix https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/Devtron%20Team/Issues

ci pipeline escape functionality removed

---

src/components/app/details/appDetails/AppDetails.tsx
src/components/app/service.ts

In a case of external CI there is no material info available due to which FE shows broken page. To fix this we have added a check to hide the commit info button in case of external CI
Manually tested by creating external CI

remove commit info button in case of external data source

---

src/components/common/helpers/Helpers.tsx
src/components/login/Login.tsx
src/config/constants.ts

Show "Please login again" toast on login page only when, we have invalidated existing cookie and redirected user to the login page. When users were coming directly on Devtron login page for the first time "Please login again" toast was appearing which was a bug, it should only appear in certain cases which are as follows:-
1. When there are multiple tabs of Devtron is open, if user logs out from one tab, performing any task in other tab will stop and will get redirected to login page with "Please login again" toast. 
2. When user is inactive for a long time, in that case their cookie(unique user token) will get deleted from the database and they will get redirected to the login page with "Please login again" toast. 
Please describe the tests that you ran to verify your changes. Provide …

fix: Login page bug fix for showing toast conditionally

---

src/components/ciConfig/CICreateDockerfileOption.tsx

This will fix the issue related to unexpected Dockerfile content parsing as YAML causing additional characters to be added or reformatting of the file as YAML content instead of Dockerfile content. Also contains one check fix around the framework.
Fixes - [AB#638](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/638)
All tests have been performed manually by saving different custom contents.

[HOTFIX] Passing noParsing flag to CodeEditor & framework check fix

---

src/components/deploymentConfig/deploymentConfig.scss

Save & Next button breaks on smaller screen width in Base Deployment Template in App Configurations section. It happens only when user try to create ci pipeline for first time for any app. Only required some padding changes in the CSS file
Image for the same problem:- https://app.usebubbles.com/dsj32qWRAmYfDfATZmMPqQ/untitled-bubble
Fixes https://github.com/devtron-labs/devtron/issues/2535

fix: Save&Next button break on small screen width fix

---

src/components/deploymentConfig/constants.tsx

Changed the chart name from CronJob & Job to Job & CronJob in constants file so that 'Learn More' link is functional. Previously, Learn More link was not showing as CronJob & Job name was changed at the backend to Job & CronJob.

fix: change CronJob & Job to Job & CronJob in constants file

---

src/components/app/details/cIDetails/CIDetails.tsx
src/components/app/details/triggerView/cdMaterial.tsx
src/components/common/GitCommitInfoGeneric.tsx

This happens in case an app is using multiple git repositories and if someone deletes a git repository from those, workflow doesn't get updated with the changes. It keeps showing the same git repositories which were before deletion of any one of them.
Even if you add the same repo again, Workflow doesn't update the id for the same. Triggered ci pipeline with multiple git repositories and when one of the git material is deleted, it should have affected multiple places but deletion was not reflecting at all anywhere.
In Ui when the git material is deleted, In ci and cd history the git material card was shown but with empty commit, hence fixes to be done there.
Places where git material deletion should be reflected are:-
1. Workflow editor
Deleted git repository node will be removed
Current …

fix: checks added in divs showing commit info (now showing empty commit info) when git materials were deleted 

---

src/components/charts/ChartGroupUpdate.tsx
src/components/charts/ChartHeaderFilters.tsx
src/components/charts/list/DiscoverCharts.tsx
src/components/common/Accordian/Accordian.tsx

This contains changes related to the following,
1. Switched chart store layout to Grid as default
2. Replaced the `Connect chart repository` note with the `Add chart repository` button under the Repository section
Fixes - [AB#1297](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/1297)
All tests have been performed manually by visiting the chart store & chart group edit view.

Enhancement: Switched chart store layout to Grid as default & related changes

---

src/components/cdPipeline/CDPipeline.tsx
src/components/cdPipeline/cdPipeline.types.ts
src/components/workflowEditor/workflowEditor.tsx

Unable to delete app without page refresh after deleting the webhook CD
Fixes # [AB#1315](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/1315)

fix: App delete issue fix

---

src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
src/config/constants.ts
src/config/index.ts
src/config/utils.ts

Block deletion of Devtron(devtron-operator chart) helm apps. Deletion of the default app comes with some unwanted behaviour so for default devtron app delete option must not be shown on the UI.
Fixes:- [#2708](https://github.com/devtron-labs/devtron/issues/2708)

fix: Block deletion of default devtron app(devtron-operator chart)

---

src/components/app/details/triggerView/workflow/Workflow.tsx
src/components/workflowEditor/Workflow.tsx

The deprecated warning should come only in case on old external CI
Fixes # [AB#1356](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/1356)
Manually tested on external and linked ci

fix: added check to prevent the warning on linked ci

---

src/css/base.scss

Fixed cluster row alignment is different compare to header row
Fixes [AB#1534](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/1534)

fix: cluster row ui alignment

---

src/components/ClusterNodes/NodeList.tsx
src/components/ClusterNodes/clusterNodes.service.tsx

Fixed cluster terminal page breaks when list API is pending
fixes #devtron-labs/devtron/issues/2803

fix: clusterName delay in cluster terminal

---

src/components/ClusterNodes/NodeActions/CordonNodeModal.tsx
src/components/ClusterNodes/NodeActions/DrainNodeModal.tsx
src/components/ClusterNodes/NodeActions/EditTaintsModal.tsx
src/components/ClusterNodes/NodeActions/NodeActionsMenu.tsx
src/components/ClusterNodes/NodeDetails.tsx
src/components/ClusterNodes/types.ts

These changes will add an action buttons to the cluster node details which will contain different actions like,
- Cordon node
- Drain node
- Edit taints
- Edit YAML
- Delete node
Fixes - [AB#1613](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/1613)
All tests have been performed manually by visiting `Clusters > Select cluster > Perform node actions`.

feat: Cluster node details action buttons

---

src/components/ClusterNodes/ClusterTerminal.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/Terminal.tsx

Changed polling time for cluster terminal from 3 sec to 5 sec & interval from 5 to 7 
Fixes [#AB1674](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/1674)

feat: Changed polling time in cluster terminal

---

src/components/app/details/cIDetails/CIDetails.tsx
src/components/app/details/cdDetails/CDDetails.tsx

This PR has the fix of CI/CD details page 2nd page scroll and autoselection of env/pipeline in case of single option
Fixes # [(AB#1846)](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/1846)
- verified by opening the build/deploymnent history when there is only 1 pipeline/env option available
- verified on build/deployment history when there are more than 20 history available and scrolled till bottom so that 2nd page gets loaded

fix: Scroll and autoselect on single item

---

src/components/app/details/triggerView/workflow.service.ts

In case of linked CI the local git material is also visible which should not be the case in case of linked pipelines, it should only reflect the parent pipeline and parent's git materials. Please see below image.
Fixes #723 

fix: Multigit linkedci local git material visible bugfix

---

src/components/app/details/cicdHistory/Artifacts.tsx

Show image tag copy icon while hovering over the entire card
Build history > Artifacts
Fixes #[AB1910](https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/CSAT/Stories/?workitem=1910)
All the test are done manually .
1. By clicking on copy item

feat: show image tag copy icon while hovering over the entire card

---

src/components/app/details/cIDetails/ciDetails.scss
src/components/app/details/cicdHistory/TriggerDetails.tsx
src/css/base.scss

Div in progress state and finished state dis-aligning after the addition of build duration feature
Fixes # [issue](https://github.com/devtron-labs/dashboard/issues/758)
Refrence image: [image](https://cdn.discordapp.com/attachments/819922034363727932/1074574604816879706/Screenshot_2023-02-13_at_11.25.51_AM.png)
It has been tested locally by seeing the changes in the localhost.

fix: Build page duration div width

---

nginx-default.conf

We have changed the nginx server port because of Kubernetes privilege port using exception with non-root user

fix: using port 8080 for nginx server

---

src/components/ciConfig/CIAdvancedConfig.tsx
src/components/ciConfig/CIBuildpackBuildOptions.tsx
src/components/ciConfig/CIContainerRegistryConfig.tsx
src/components/ciConfig/ciConfigConstant.ts
src/config/constants.ts
src/css/base.scss

These changes will enable user configuring a custom buildpack builder from select a builder dropdown.
Fixes https://github.com/devtron-labs/devtron/issues/3075
AB issue - [AB#2268](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/2268)
All tests have been performed manually by visiting App Configuration & saving custom builder option.

feat: Enabled configuring custom buildpack builder in dropdown

---

src/components/CodeEditor/CodeEditor.tsx

This error is coming on deployment history as onDidFocusEditorWidget is not available in editor instance whereas it's present in other multiple places like deploy chart, app config, etc. as I had a quick look.
Fixes - [AB#2343](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/2343)

fix: Add Check to editor for onDidFocusEditorWidget and onDidBlurEditorWidget

---

src/components/gitOps/GitOpsConfiguration.tsx

We should send the empty token when token is Default Secret Placeholder for updating or validating
Fixes #https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/2518
[x] Tested the code by deploying on cluster

fix: Gitops validate and update with empty token

---

src/components/ApplicationGroup/Details/EnvironmentConfig/EnvConfig.tsx

App-group > config page break when the user clicks on the back button
Fixes [#AB2547](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/2547)
1. Select any app from the app group list 
2. Click on config 
3. Click on the back button 
4. Check if page breaks or not 
5. Tried with app filtered

fix: App-group config back button

---

src/components/cdPipeline/CDPipeline.tsx
src/components/cdPipeline/cdPipeline.css
src/components/cdPipeline/cdpipeline.util.tsx
src/config/constantMessaging.ts
src/css/forms.scss

Create a differentiating label to differentiate config maps and secrets in both edit deployment and new deployment workflow ( in both pre and post deployment stage ) , on selecting a config name or a secret having same name as the other type both are disappearing.
Fixes # [2532](https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/OSS%20adoption/Stories/?workitem=2532)
1: To start with the , created label to differentiate config maps and secrets in the deployment stage.
2: On selecting the config map with secret , the latter does not disappear and vice versa.
3: The value of both config maps and secrets are passed correctly in the payload.

feat: differentiate config map secret in deployment stage

---

src/components/cluster/Cluster.tsx

on deleting any environment from cluster and environments page it was showing incorrect name .it got set to last environment name as delete component was inside map
Fixes #[3005](https://github.com/devtron-labs/devtron/issues/3005)

fix:incorrect env name on toast message when deleting

---

src/components/app/details/appDetails/SourceInfo.tsx

Restart workload should hide in case of the virtual cluster environment

fix: for restart workload in virtual environment

---

src/components/app/list-new/AppListService.ts

Now namespaces are optional when it comes to virtual clusters. So, added a check for an empty namespace for the filter list
Fixes [#AB3592](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/3592)
- Create a Virtual cluster & then an environment without a namespace
- Select the virtual cluster in the app list & then open the namespace

fix: Added fix for namespace  shows undefined for empty

---

src/components/app/details/cicdHistory/Artifacts.tsx

Hide image card for CD artifact in PRE/POST CD
Fixes [#AB3642](https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/OSS%20adoption/Stories/?workitem=3642)

fix: Hide image card for CD artifact

---

src/components/cluster/Cluster.tsx

It bugs out when you go to clusters and environments section in global configurations and edit any cluster.
It will show as prometheus not configured even if you have configured.
Before Fix
Clusters and Environments section should have shown as prometheus configured along with the endpoint and Authentication Type.
After Fix
Clusters and Environments section showing as prometheus not configured.
Fixes # (https://github.com/devtron-labs/devtron/issues/3520)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test …

fix: Promethes showing in toggled state 

---

src/components/dockerRegistry/Docker.tsx

while updating the container registry token, after saving the token isnt being saved in DB when passed empty
Fixes #https://github.com/devtron-labs/devtron/issues/3516

fix: Update with empty string for GCR an GCP container registry

---

src/components/ClusterNodes/NodeDetails.tsx

For the pod resources in Clusters section ,on clicking the resource we should be able to reach the manifest,logs ,terminal page of the resource.
Fixes # [#4288](https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/OSS%20adoption/Stories/?workitem=4288)
1.After making the changes in the code ,i have tested it on the local host
* [] Does this PR require documentation updates?

Fix: redirecting url of Pod in cluster Section

---

src/components/CIPipelineN/TaskList.tsx

we shouldn’t give option to move plugin in job for post build because no any uses for that feature on that place
Fixes # [AB4393](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/4393/)

fix: Removed move task option in jobs

---

src/components/common/navigation/NavigationRoutes.tsx

If user opening the dashboard with "/dashboard" URL app list page unable to open on same URL but it should be redirect on App list page.
Fixes [#AB4417](https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/4417)

fix: Page not redirecting from dashboard to app

---

src/components/app/details/triggerView/workflow.service.ts
src/components/app/details/triggerView/workflow/Workflow.tsx

Build and deploy page break when pre & post is added from old api
Fixes #

fix: Build & deploy page break on old data

---

src/components/chartRepo/ChartRepo.tsx
src/components/charts/charts.service.ts
src/components/charts/charts.types.tsx
src/components/charts/list/AddChartSource.tsx
src/components/charts/list/ChartListPopUp.tsx
src/components/charts/list/ChartListPopUpRow.tsx
src/components/charts/list/DiscoverCharts.tsx
src/components/common/helpers/Helpers.tsx
src/components/dockerRegistry/Docker.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.component.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
src/css/base.scss

Bug fixes:
1.  Chart Providers List: can also disable helm chart repositories with active deployments
2.  Chart Providers List: chart sync API is called for disabled chart provider
3. Chart Providers List: Toast chart sync API response
4. Duplicate pass/Token box showing in (Docker,quay,other,Azure) config while adding new container registry
5.  Chart deployed from OCI and visible in chart store as well but while deploying , Helm and gitops option should be not visible
6.  Chart Store: For empty chart list in chart store, the empty state hides the side bar on page refresh
7.  Chart Store EA Mode: Add chart source should redirect to chart repository only, currently can visit add registry page as well. Chart Store: Chart providers filter list is not visible for sub users
8. Chart version …

Hp bugs of chart store & container registry

---

src/components/chartRepo/ChartRepo.tsx
src/components/globalConfigurations/GlobalConfiguration.tsx

These changes fixed the "data validation error" when we enable/disable a chart repo and also fixed the issue where we can enable/disable a chart even when the chart is being used in a deployed helm app.
All tests have been performed manually by visiting Chart Repository and performing different actions.

fix: DATA VALIDATION ERROR and disabled toggle button for deployed apps in chart repo

---

src/components/charts/modal/CreateChartGroup.tsx

These changes fix the issue where, once the user creates a new chart group, he/she can't edit the chart description.
Fixes #
All tests have been performed manually by visiting Chart Store page and performing different actions.

fix: Unable to edit description in chart group [prod*]

---

src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/app/details/triggerView/TriggerView.tsx
src/components/app/details/triggerView/cdMaterial.tsx
src/components/app/details/triggerView/types.ts
src/components/app/service.ts

It bugs out when you go to application groups to deploy multiple applications.
It happens in a certain scenario when your active image is older than latest image. When you select the active image the topmost application from app group's image list gets populated.
👟 Reproduction steps
create 2 applications in same env.
make sure the 2nd application that appears in application groups is having active image older than latest image.
Select active image while trying to deploy both applications via application groups and deploy.
The 2nd application will pick a wrong image in this scenario.
👍 Expected behavior
It should have picked the correct image.
Fixes # [3718](https://github.com/devtron-labs/devtron/issues/3781#)
Please describe the tests that you ran to verify your changes. Provide …

fix: AppGroup image selection 

---

src/components/security/SecurityPolicyEdit.tsx

Page breaks while changing cve policy if user does not have permissions
repo steps -
1) Give user view only permission 
2) Go to security scan tab
3) Change CVE policy
- Page breaks
Fixes [#511](https://github.com/devtron-labs/devtron/issues/511)

fix: security scan page break fix

---

src/components/app/details/triggerView/TriggerView.tsx
src/components/common/GitInfoMaterial.tsx

commit hash search box refresh its state on double enter
Fixes [#3499](https://github.com/devtron-labs/devtron/issues/3499)
All tests are performed locally

fix: Commit hash search box breaks on double enter or incorrect query 

---

src/components/hostURL/HostURL.tsx
src/components/login/SSOLogin.tsx

1- Create a new cluster
1.1- open SSO login page
1.2- Verify SSO url login column
2- Open cluster with New host domain
2.1- then verify the Host YRL column 
Aspected
-Host URL and and SSO URL column should be autofill
Fixes (https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/5407

fix: Host URL and and SSO URL column should be autofill

---

src/components/CodeEditor/CodeEditor.tsx
src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateEditorView.tsx

Every reference chart have their own schema.json file . but here we are redirecting on wrong path.
Fixes https://github.com/devtron-labs/devtron/issues/3535

fix: Schema.json redirect wrong path in deployment template

---

src/components/cdPipeline/NewCDPipeline.tsx

Both Trigger-options of pre-cd get un-selected when we update cd configuration without any task.
All tests are performed locally.

fix: Both Trigger-options of pre-cd get un-selected in specific case 

---

src/components/ConfigMapSecret/ConfigMapSecret.reducer.ts
src/components/ConfigMapSecret/ConfigMapSecretDataEditorContainer.tsx
src/components/ConfigMapSecret/ConfigMapSecretForm.tsx
src/components/ConfigMapSecret/Types.ts

1: select any devtron app and create a config map for the same .
2: The correct format is for e.g "key":"sde" but you added key:sde .
3: A warning would be there regarding wrong format , click on save -> cm would get created .
4: open the cm again , you will see yaml like this "key":"0" 
Issue : - Allow us to save even there is warning and value is not right that we entered 

fix: config maps and secrets validation fix

---

src/components/workflowEditor/Workflow.tsx

Fixed: Link for overridden CI workflows sidebar is breaking.
Fixes https://github.com/devtron-labs/devtron/issues/4002
* [] I've updated documentation as required by this PR.

fix: overridden CI workflow link breaking

---

src/components/scopedVariables/VariablesList.tsx
src/css/base.scss

Removing word-break from default-tt and and adding it in the required places

chore: revert default tooltip without word break

---

src/components/ConfigMapSecret/ConfigMapSecretDataEditorContainer.tsx

Add params should not be in Kubernetes External config map.

fix: Add params should not be in Kubernetes External config map

---

src/components/ResourceBrowser/ResourceList/DeleteResourcePopup.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx

we have to add a refresh function after deletion so that directly we see manifest not found screen .
Fixes https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/5759/

fix: reload after deletion

---

src/components/v2/appDetails/AppDetails.component.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.tsx

These changes fix the issue of "no rows selected" warning when we configure any existing helm chart, click "update and deploy" button and navigate again to "configure" page when the page is still loading.

fix: no rows selected warning is coming on configure page of helm charts 

---

src/components/app/details/appDetails/AppDetails.tsx
src/components/app/details/appDetails/appDetails.type.ts
src/components/app/service.ts

1: add an environment in unreachable cluster .
2: deploy something on that app .
3: deployment will get failed .
4: now go to app detail page , it will be in loading state , click on env dropdown . it won't open 
Fixes https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/5849/

fix: Environment dropdown is not opening until resource tree is not coming 

---

src/components/app/details/cIDetails/CIDetails.tsx
src/components/app/details/cicdHistory/Artifacts.tsx
src/components/app/details/cicdHistory/types.tsx
src/components/app/service.ts
src/components/app/types.ts

Currently we only show latest image in case of ci job type but there can be multiple images from Plugin (Pull Images) which user wants to see and perform actions on.
Fixes #4028

feat: listing all artifacts in case of ci-job type

---

package.json
src/components/common/formFields/ButtonWithLoader.tsx
src/components/hostURL/HostURL.tsx
src/components/project/Project.tsx
src/components/userGroups/AppPermissions.tsx
yarn.lock

- Fix page refresh by pressing the enter key on the Add Project and Host URL page under Global Configuration
- Fix the process being undefined post hot reload on dev server (Ref: https://github.com/facebook/create-react-app/issues/11773#issuecomment-995933869)
- Fix `directPermissions` undefined sentry in app permissions
Fixes https://github.com/devtron-labs/devtron/issues/4088

fix: refresh issue on add project & host url update and process undefined on dev server

---

src/components/ResourceBrowser/ResourceList/ResourceList.tsx

It bugs out generally in subsequent request made to events page or pods page in resource browser section. The frontend displays the screen No result found after 2-3 seconds even if backend request is still processing.
Fixes #4109

fix: loading state in resource browser

---

src/components/ConfigMapSecret/ConfigMapSecretForm.tsx
src/components/cdPipeline/validationRules.ts
src/config/constantMessaging.ts
src/config/constants.ts

This pr aims at fixing the issue where a user can add any special characters in data volume path when adding a cm or cs via Data Volume. Added validation where special characters are not allowed, (.),(/),(-),(_) these characters are allowed.

fix: don't allow special chars in data vol in cm cs

---

src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx

-> On copying service URL from dashboard, it copies all the port numbers in the URL in comma separated way.
-> Incomplete service URL if you click on (+ more) button. It does not include the namespace in the service URL.
-> Shows duplicate service URL.
Fixes https://github.com/devtron-labs/devtron/issues/4025

fix:issue with service URL and port numbers

---

src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.scss
src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/css/base.scss

App list > Filter dropdown spacing fixtures and protection configuration background colour should be same while scrolling down which changes when it exceeds height beyond 100.
Fixes #1418

fix: CSS fix

---

src/components/ClusterNodes/ClusterOverview.tsx

Fix the cluster details and cluster note API calls aborting even before landing on the cluster overview page

fix: API calls aborting on landing cluster-overview page

---

src/components/ClusterNodes/ClusterSelectionList.tsx
src/components/ClusterNodes/ClusterTerminal.tsx
src/components/ClusterNodes/clusterNodes.scss
src/components/ClusterNodes/types.ts
src/components/ResourceBrowser/ResourceList/ResourceList.tsx
src/components/ResourceBrowser/Types.ts
src/components/cluster/cluster.type.ts
src/components/cluster/cluster.util.ts
src/components/common/DynamicTabs/useTabs.ts
src/components/common/helpers/Helpers.tsx
src/components/v2/appDetails/appDetails.type.ts
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Terminal.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/nodeDetailTab.scss
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/Terminal.tsx

**Steps:**
1. Open a terminal connection using the Resource Browser
2. Now open a new Resource 
3. switch back to the last terminal
**Actual Output:**
We are initiating the new session instead of resuming the old session of the terminal
**Implementation:**
Keep the terminal instance hidden behind the `visibility: hidden` css so that the session and the socket connection keep running in the background.
Fixes #1405
https://github.com/devtron-labs/dashboard/assets/146105157/1263172d-d794-4d95-a8b8-c659cccf937a

fix: Changes to persist cluster terminal session even on tab switches

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/Terminal.tsx

Persist cluster terminal logs on switching  back from pod terminal
Fixes #1422 

fix: Persist cluster terminal logs on switching back from pod terminal

---

src/components/app/Overview/Overview.tsx
src/components/app/Overview/constants.ts
src/components/common/Description/GenericDescription.tsx
src/css/base.scss

- fix overflow issue in MD Editor
- Set the shimmer loader rows to 3 for Environment List
- Add lg variant for the yaml switch

fix: overflow issue in md editor, set shimmer loaders rows to 3

---

src/components/dockerRegistry/Docker.tsx

Auto trim https:// or oci:// in registry URL 
Fixes https://github.com/devtron-labs/devtron/issues/4074

fix: Auto trim https:// or oci:// in registry URL 

---

src/components/ApplicationGroup/AppGroup.types.ts
src/components/ApplicationGroup/Details/EnvCIDetails/EnvCIDetails.tsx
src/components/app/details/cIDetails/CIDetails.tsx

In CI Details (Build History tab) if we are viewing any log and filter env that is attached to no-source app then the page would either break or data will be retained to sidebar.

fix: build history no pipeline

---

src/components/CIPipelineN/CustomImageTags.tsx
src/components/ConfigMapSecret/ConfigMapSecret.components.tsx

When saving a key-value pair with a decimal value in a ConfigMap, values with more than four decimal places are being truncated or rounded, resulting in a loss of data.
Fixes https://github.com/devtron-labs/devtron/issues/4345
testing with:
value1: 1
value2: |
1234\n
value3: "shivam\n1"
value4: |
dsdsdds\n\n
value5: 466
value6: |
123.2
value7: 1234555
value8: shivam\n1
value9: |
abc: 
xyz: 123

fix: ConfigMap Truncates for Long Integers

---

src/components/workflowEditor/nodes/CDNode.tsx

Adding stopPropagation for deleteCDNode for upfront delete in CDNode, this will stop the trigger happening in onClick of Link tag

fix: node delete propagation

---

src/components/ciConfig/CIConfig.tsx
src/components/ciConfig/CIConfigDiffView.tsx
src/components/ciConfig/CIConfigForm.tsx
src/components/ciConfig/types.tsx

Separating out component-names api call from ciConfig and moving it to modal on mount to save the state in case of error.

feat: separate configOverrideWorkflows api call from CIConfig

---

src/components/ciConfig/CIBuildpackBuildOptions.tsx
src/components/v2/appDetails/k8Resource/nodeType/nodeType.scss

In case of build pack, if we set custom builder and save modal, then on re-opening we had a arg with no key but value as version so would removing the value as well.

fix: build env custom key

---

src/components/common/GitCommitInfoGeneric.tsx

Fixed alignment issue selecting commit from select material modal, by aligning select to left.
Fixes https://github.com/devtron-labs/devtron/issues/4505
Dev testing

fix: align select text to end for ci materials

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/Terminal.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/terminal.utils.tsx

In terminal, we are using editable xterm component which covers scrollbar, so using js we are restricting its width same as readonly editor so that it doesn't overlap with scrollbar .
Fixes https://github.com/devtron-labs/devtron/issues/4519

fix: restrict width of xterm to make it scrollable

---

src/components/CIPipelineN/CIPipeline.tsx

If we force enable security scanning of images, some jobs that don't have anything to do with images will throw errors in the logs when the job is triggered. Therefore security scanning is disabled in case of jobs even when enforced by the FORCE_SECURITY_CHECK env variable. 
fixes https://github.com/devtron-labs/devtron/issues/4757

fix: disable scan validation on job in CIPipeline

---

src/components/common/security/ScanDetailsModal.tsx
src/components/security/SecurityScansTab.tsx

Security scanning modal used to get closed on clicking on its header and we were not able to open it through security tabs so had to add stopPropagation

fix: security scan modal stop propagation

---

src/components/ClusterNodes/ColumnSelector.tsx
src/components/ClusterNodes/NodeDetailsList.tsx
src/components/ClusterNodes/constants.ts
src/components/ClusterNodes/types.ts
src/components/ResourceBrowser/ResourceList/ResourceList.tsx

This PR fixes the issue that caused search to not be retained on page refresh on "Nodes" tab of "Resource Browser".
Additionally it also fixes the issue where the k8sVersion filter options are not shown unless we move to clusterOverview first.
Fixes https://github.com/devtron-labs/devtron/issues/4774

fix: retain search on reload in nodes tab of ResourceBrowser & show correct k8sVersion filter options

---

src/components/gitOps/GitOpsConfiguration.tsx

fixes the issue where even if Bitbucket Data Center is set as default the toggle is switched to Bitbucket Cloud.

fix: use active state to determine correct toggle state

---

src/components/v2/appDetails/k8Resource/K8Resource.component.tsx
src/components/v2/appDetails/k8Resource/NodeTreeTabList.scss
src/components/v2/appDetails/k8Resource/NodeTreeTabList.tsx
src/components/v2/appDetails/k8Resource/k8resources.scss
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Events.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/EventsTable.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/nodeDetailTab.scss
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/terminal.scss
src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.css
src/components/v2/common/message.ui.tsx

In resources tree tabs, when page is scrolled to the bottom the tabs hide behind the header.
The tabs should stick on the top of the page under header and the rest of the content should scroll without UI breaking.
Fixes https://github.com/devtron-labs/devtron/issues/5298

fix: resource tree tabs - hides when scroll to page bottom fix

---

package.json
src/components/CIPipelineN/CIPipeline.tsx
src/components/CIPipelineN/PluginDetailHeader.tsx
src/components/CIPipelineN/TaskDetailComponent.tsx
src/components/CIPipelineN/TaskTitle.tsx
src/components/CIPipelineN/ciPipeline.utils.tsx
src/components/cdPipeline/cdpipeline.util.tsx
src/components/scopedVariables/utils.tsx
src/components/workflowEditor/types.ts
src/css/base.scss
yarn.lock

This PR adds:
- removal of conditionDetails in case of no input variables.
- send optional updated plugin data store in validateStage and fix mandatory plugin validation by sending updated form data instead of previous form data

fix: validateStage function now accepts an optional pluginDataStore

---

package.json
yarn.lock

chore: update fe-common-lib dependency to version 0.2.6-beta-10

chore: update fe-common-lib dependency to version 0.2.6-beta-10

---

src/components/ClusterNodes/NodeDetailsList.tsx

When navigating from cluster overview by selecting a node version with an error, the node version is appended to the url but the node details list page does not sync its state with that present in the url.

fix: sync selected k8s version from url

---

src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/Terminal.tsx

Issue: currently once we enter fullscreen for terminal we can't exit it using the shortcut since the terminal is a `textarea`. Therefore override the ignoreTags property only in the case of terminal.

fix: override ignore tags for terminal shortcut

---

src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentTemplate/DeploymentTemplate.tsx

fix: stop unsaved changes prompt in case of readme click
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1145

fix: stop unsaved changes prompt in case of readme click

---

src/components/ApplicationGroup/AppGroup.types.ts
src/components/ApplicationGroup/AppGroup.utils.ts
src/components/ApplicationGroup/AppGroupAppFilter.components.tsx
src/components/ApplicationGroup/AppGroupAppFilter.tsx
src/components/ApplicationGroup/AppGroupDetailsRoute.tsx
src/components/app/details/main.tsx
src/components/common/helpers/Helpers.tsx
src/components/common/helpers/types.ts

fix: app group filter persist

---

package.json
src/components/ApplicationGroup/AppGroup.types.ts
src/components/ApplicationGroup/Details/TriggerView/BulkCITrigger.tsx
src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/CIPipelineN/CIPipeline.tsx
src/components/app/details/triggerView/TriggerView.tsx
src/components/app/details/triggerView/WebhookReceivedPayloadModal.tsx
src/components/cdPipeline/DeleteCDNode.tsx
src/components/common/helpers/Helpers.tsx
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
yarn.lock

fix: dt 24 misc

---

src/components/ApplicationGroup/AppGroup.types.ts
src/components/ApplicationGroup/AppGroup.utils.ts
src/components/ApplicationGroup/AppGroupAppFilter.components.tsx
src/components/ApplicationGroup/AppGroupAppFilter.tsx
src/components/ApplicationGroup/AppGroupDetailsRoute.tsx
src/components/app/details/main.tsx
src/components/common/helpers/Helpers.tsx
src/components/common/helpers/types.ts

fix: app group filters makes api call again
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1416

fix: app group filters makes api call again

---

src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentTemplate/DeploymentTemplate.tsx
src/Pages/Applications/DevtronApps/Details/AppConfigurations/MainContent/DeploymentTemplate/deploymentTemplateReducer.ts

fix: add toast and lock diff modal after isLockConfigError is true while updating draft

fix: add toast and lock diff modal after isLockConfigError is true while updating draft

---

.github/semantic.yml
.github/workflows/pr-issue-validator.yaml

1. added `sync` to semantic.yaml and pr validator 
2. removed issue status dependency in pr-validator

misc: remove issue status dependency in pr-validator

---

src/Pages/Applications/DevtronApps/Details/AppConfigurations/Navigation/AppNavigation.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretContainer.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretDryRun.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretForm.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretProtected.tsx
src/Pages/Shared/ConfigMapSecret/types.ts

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1675

refactor: ConfigMapSecret -update form submission handlers and improve error handling in dry run

---

src/components/app/details/triggerView/ciMaterial.tsx

To remove unnecessary get save call on regex modal
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1784

fix: To remove unnecessary get call on regex save modal

---

src/components/ResourceBrowser/ResourceList/BaseResourceList.tsx
src/components/ResourceBrowser/ResourceList/utils.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1456

fix: resource browser breaking due to undefined kind

---

src/components/ClusterNodes/NodeActions/DeleteNodeModal.tsx
src/components/ClusterNodes/NodeDetails.tsx
src/components/ClusterNodes/types.ts
src/components/ResourceBrowser/ResourceList/BaseResourceList.tsx
src/components/ResourceBrowser/ResourceList/DeleteResourcePopup.tsx
src/components/ResourceBrowser/ResourceList/NodeActionsMenu.tsx
src/components/ResourceBrowser/ResourceList/ResourceBrowserActionMenu.tsx
src/components/ResourceBrowser/Types.ts
src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1825

fix: retain bulk selection in resource browser if there is search text change and only clear it if resource list call is re-called

---

src/Pages/Shared/ConfigMapSecret/ConfigMapSecretContainer.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretProtected.tsx

fix: disable name edit for inheriting cm/cs
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1858

fix: disable name edit for inheriting cm/cs

---

src/Pages/Shared/ConfigMapSecret/ConfigMapSecretContainer.tsx
src/Pages/Shared/ConfigMapSecret/ConfigMapSecretProtected.tsx

fix: cm/cs name should not be editable on app override.
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1858

fix: cm/cs name should not be editable on app override.

---

src/components/app/details/appDetails/AppDetails.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.component.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.reducer.ts

default deployment app type for helm chart should be "" if hide helm or gitops is enabled
Fixes https://github.com/devtron-labs/sprint-tasks/issues/1855

fix: helm chart deployment type

---

package.json
src/components/common/DynamicTabs/constants.ts
src/components/common/DynamicTabs/types.ts
src/components/common/DynamicTabs/useTabs.ts
src/components/common/DynamicTabs/utils.ts
src/components/common/navigation/NavigationRoutes.tsx
yarn.lock

Fixes https://github.com/devtron-labs/sprint-tasks/issues/1920

fix: remove data hazard in local storage for useTabs

---

src/components/ApplicationGroup/AppGroup.types.ts
src/components/ApplicationGroup/Details/TriggerView/BulkCITrigger.tsx
src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.scss
src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
src/components/CIPipelineN/CIPipeline.tsx
src/components/app/details/triggerView/CiWebhookDebuggingModal.tsx
src/components/app/details/triggerView/TriggerView.tsx
src/components/app/details/triggerView/WebhookReceivedPayloadModal.tsx
src/components/app/details/triggerView/triggerView.scss
src/components/app/details/triggerView/types.ts
src/components/cdPipeline/CDPipeline.tsx
src/components/ciConfig/CIConfig.scss
src/components/ciPipeline/Webhook/WebhookDetailsModal.tsx
src/components/ciPipeline/Webhook/webhookDetails.scss
src/components/ciPipeline/ciPipeline.scss
src/components/common/helpers/GitInfoMaterialCard/GitInfoMaterial.tsx
src/css/triggerView.scss

fix: bulk ci webhook

---

src/components/v2/values/chartValuesDiff/ChartValuesView.tsx

- Gitops configure warning rendering on every mount
- Manifest link is missing from the left bar of Configure 
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2039

chore: gitops configure warning rendering on every mount

---

src/components/v2/values/chartValuesDiff/ChartValuesView.tsx

Fixes Fixes https://github.com/devtron-labs/sprint-tasks/issues/2039

fix: gitops configure warning rendering on every mount 

---

src/components/v2/values/chartValuesDiff/ChartValuesView.tsx

a. On Update Gitops configure warning rendering on every mount of Chart Configure
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2039

fix: On Update Gitops configure warning rendering on every mount of Chart Configure 

---

src/components/cdPipeline/CDPipeline.tsx

This PR includes fix for flow to fetch plugin details in template view when a plugin is present in pre/post CD. Currently we are not fetching the details due to wrong early return
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2137
Dev tested

fix: flow to fetch plugin details in case of template view

---

src/components/app/list/expandedRow/ExpandedRow.tsx

fix: add overflow hidden in expanded status to cater absence of overflow-clip-margin: content-box in safari. Plus have added some alignment fixes as well.
Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-clip-margin

chore: add overflow hidden in expanded status to cater absence of overflow-clip-margin: content-box in safari

---

.eslintignore
index.html
package.json
src/App.tsx
src/Pages/App/CreateAppModal/ApplicationInfoForm.tsx
src/Pages/App/CreateAppModal/ProjectSelector.tsx
src/Pages/GlobalConfigurations/Authorization/SSOLoginServices/SSOLogin.component.tsx
src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx
src/components/app/details/triggerView/cdMaterial.tsx
src/components/charts/ChartHeaderFilters.tsx
src/components/common/navigation/NavRoutes.components.tsx
src/components/common/navigation/NavigationRoutes.tsx
src/components/common/navigation/constants.ts
src/components/v2/values/chartValuesDiff/ChartValuesView.component.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.constants.ts
src/components/v2/values/chartValuesDiff/ChartValuesView.scss
src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
src/components/v2/values/chartValuesDiff/ChartValuesView.type.ts
src/css/base.scss
src/css/formulae.scss
yarn.lock

Fixes https://github.com/devtron-labs/sprint-tasks/issues/2406

feat: show initial loading inside app container and animate navbar

---

src/Pages/GlobalConfigurations/ClustersAndEnvironments/ClusterForm.tsx
src/Pages/GlobalConfigurations/ClustersAndEnvironments/DeleteClusterConfirmationModal.tsx
src/Pages/GlobalConfigurations/ClustersAndEnvironments/cluster.type.ts

fix: handle success for cluster deletion
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2428

fix: handle success for cluster deletion

---

src/components/common/navigation/NavigationRoutes.tsx
src/components/v2/devtronStackManager/DevtronStackManager.service.tsx

fix: update getGrafanaModuleStatus to handle errors and return null on failure
Fixes https://github.com/devtron-labs/sprint-tasks/issues/2485

fix: update getGrafanaModuleStatus to handle errors and return null on failure

---

src/components/ClusterNodes/ClusterList/ClusterListView.tsx
src/components/ClusterNodes/ClusterList/ClusterSelectionBody.tsx
src/components/ClusterNodes/ClusterList/types.ts
src/components/ResourceBrowser/ResourceBrowser.tsx

This pull request enhances the cluster selection workflow in the resource browser by introducing bulk selection identifier support and improving error handling. The changes ensure that cluster selection and bulk actions are more robust and that error screens provide a reload option for a better user experience.
* Updated the `ClusterListView` and `ClusterSelectionBody` components to support and pass a new `identifierMap` prop for bulk selection, utilizing the `BulkSelectionIdentifiersType` type. This enables more efficient handling of bulk cluster selection actions. [[1]](diffhunk://#diff-9802e0de00fe57ae3a6dce6a4ceecada8a5ebbf178637939376351603db04770L95-R96) [[2]](diffhunk://#diff-9802e0de00fe57ae3a6dce6a4ceecada8a5ebbf178637939376351603db04770L152-R153) …

fix: kubeconfig modal loading state

---

package.json
src/App.tsx
src/components/common/ClusterNotReachableDialog/ClusterNotReachableDialog.tsx
src/components/common/ClusterNotReachableDialog/ClusterNotReachableDialog.type.ts
src/components/externalArgoApps/ExternalArgoAppDetail.tsx
src/components/v2/appDetails/ea/EAAppDetail.component.tsx
src/components/v2/appDetails/sourceInfo/EnvironmentSelector.component.tsx
src/components/v2/index.tsx
yarn.lock

This pull request introduces improvements to error handling, API timeout configuration, and user feedback during resource deletion actions across several components. The main changes focus on better tracking of API error codes, especially on first load and 404 errors, propagating loading states to dialogs and buttons during delete actions, and setting a global API timeout from environment variables.
* Added `handledFirstCall` tracking and improved error code handling for initial API calls and 404 errors in `ExternalArgoAppDetail`, `EAAppDetail.component`, and `index.tsx`, ensuring error codes are set correctly on first load and when resources are not found. [[1]](diffhunk://#diff-daa3f12867fe5f3ee17dd221e7e8b63b02b262dca1d5082c0c048190446b09b7R45-R46) …

feat: add loading state to deletion dialogs and set global API timeout
